### ISSUE TITLE
Apple Signin not working on ios 13.5.1

### ISSUE THREAD

**Issue by puneetkansal04** [invertase/react-native-apple-authentication#103]
I am using apple signin and it is working on the first time and show me option for share my email popup. But when i logout and try to login again it doesn't show me share email option as well as i am not able to login again using the apple login. Can you provide me detail.

  appleAuth.performRequest({
        requestedOperation: AppleAuthRequestOperation.LOGIN,
        requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
      })

I am using above code for getting user info. and it is working fine on simulators and i am doing logout and then try to login then it works fine. but on the real device ios version 13.5.1 it is giving me error.

@mikehardy

**Comment by mikehardy** [comment]
Yo have not provided the error.
The library works in all cases I've tested, though behavior is possibly counter-intuitive.
Once you've allowed access to your app via your apple id, you actually manage that connection in your iCloud ID settings, apart from the app
And unless you revoke permission there you will never see the popup again.

**Comment by puneetkansal04** [comment]
Hi,

Thanks for your reply. I am trying to add revoked function so that every
time it will show share my email popup. But revoked function is not working.

**Comment by Lucasark** [comment]
I saw many issues about this error here, and all closed by @mikehardy. Only say that library works and maybe is a error in settings about Apple ID is not helpful, and nothing is metioned in instruction install. I faced same error, but I know that is not about iOS version, because I have other app in same Iphone and use Sign Apple. So, is helpful attach here, or closed issues how to configure Apple ID or other third-party configuration in console apple.

**Comment by mikehardy** [comment]
@Lucasark I close issues quite quickly when not provided any useful information to test, yes. Leaving them open as if something will happen is a disservice to everyone as it might provide false expectations.

The message presented vs your settings does seem incorrect. Can you provide a repo based on the example code that reproduces it?

**Comment by Lucasark** [comment]
Maybe I am not clear in my last message. What I wanna say is that erro message is not good to track the real problem, which is about certification on Apple Developer Console, this is talk about in this step: 
**"Once you're sure you've met the above, please follow our Initial development environment setup guide.**  
But, see this error we understand that is about version of device. I have a video exemplo compile twice using SAME project code, SAME device and SAME Xcode and only diference is my signing configuration in both compile. 
![ezgif-6-78dc6fda7dac](https://user-images.githubusercontent.com/31750882/86837070-c1e57080-c074-11ea-8d1f-d2146c2abf75.gif)
One I have sucess to use Sign in with Apple and other don't with this error.

**Comment by mikehardy** [comment]
Very interesting - forgive me while I "active listen" here - I am going to try to say what you said, to see if I understand it

If you have not done the full iOS Developer Console setup for the app to enable apple sign in, then when you go to use it you get an error message about not having the right iOS version

Is that right? I am not 100% sure on the first part, but I am pretty sure I understand you've found the thing that causes a iOS version not supported message when really it has nothing to do with a version. Hopefully we can fix it

**Comment by Lucasark** [comment]
> Very interesting - forgive me while I "active listen" here - I am going to try to say what you said, to see if I understand it
> 
> If you have not done the full iOS Developer Console setup for the app to enable apple sign in, then when you go to use it you get an error message about not having the right iOS version
> 
> Is that right? I am not 100% sure on the first part, but I am pretty sure I understand you've found the thing that causes a iOS version not supported message when really it has nothing to do with a version. Hopefully we can fix it

Yes, it is my point! 
Just to compare, in Google API Login, if we do mis configuration in Google Console (sha, key, or other thinks) we have code 10 error. But, if we trying use in unsupported device we have code 320. So, we can figure out where we do it wrong.
I suggestion to open a issue about that just to not lose this improve.

**Comment by alammoiz** [comment]
I am using apple signin and it is working on the first time. But when i logout and try to login again it doesn't show me share email option as well as i am not able to login again using the apple login. Can you provide me detail.

appleAuth.performRequest({
requestedOperation: AppleAuthRequestOperation.LOGIN,
requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
})

I am using above code for getting user info. and it is working fine on simulators and i am doing logout and then try to login then it works fine. but on the real device ios version 13.5.1 it is giving me error.


Facing Same issue @mikehardy 

CC: @puneetkansal04

**Comment by mikehardy** [comment]
You only get the email the first time. You'll want to familiarize yourself with the underlying library documentation and implementation guides @alammoiz

**Comment by puneetkansal04** [comment]
> I am using apple signin and it is working on the first time. But when i logout and try to login again it doesn't show me share email option as well as i am not able to login again using the apple login. Can you provide me detail.
> 
> appleAuth.performRequest({
> requestedOperation: AppleAuthRequestOperation.LOGIN,
> requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
> })
> 
> I am using above code for getting user info. and it is working fine on simulators and i am doing logout and then try to login then it works fine. but on the real device ios version 13.5.1 it is giving me error.
> 
> Facing Same issue v13.5.1 @mikehardy
> 
> @puneetkansal04 Have you resolved that?

Not Able to resolve it. As it also give me same error. As First times it works fine but as if you do login again. It is showing different popup and state not returning the data.

**Comment by mikehardy** [comment]
Apple sign in state is managed by user and Apple in icloud settings. If you want to reset a user to pristine you have to delete your server user and remove the app from icloud settings

**Comment by puneetkansal04** [comment]
@mikehardy didn't get you how to remove the app from iCloud settings within the app using this package or any library. As Manually removal will be very much bulkier. Each timer user have to remove it manually.

**Comment by mikehardy** [comment]
Apple sign in is user focused, like Android notification channels. Once they are set up they are under user control. It's the way it is.
