### ISSUE TITLE
responseObject.fullName is null after sign in with Apple ID

### ISSUE THREAD

**Issue by bcbcbcbcbcl** [invertase/react-native-apple-authentication#11]
Xcode version: 11.2.1
React Native version: 0.60.3
@invertase/react-native-apple-authentication version: 0.1.1

Here is an example of my code
```
async function onAppleButtonPress() {
  // sign in request
  const responseObject = await appleAuth.performRequest({
    requestedOperation: AppleAuthRequestOperation.LOGIN,
    requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
  });

  //authorization state request
  const credentialState = await appleAuth.getCredentialStateForUser(responseObject.user);

  if (credentialState === AppleAuthCredentialState.AUTHORIZED) {
    //user is authorized
    console.log(responseObject)
    console.log(responseObject.fullName)
    alert("authorized")
  }
}
```

responseObject.fullName return null after successfully sign in with Apple ID.
<img width="162" alt="empty name" src="https://user-images.githubusercontent.com/39854319/70851678-122b9400-1ed3-11ea-8c5c-7364c55518f2.png">

**Comment by bcbcbcbcbcl** [comment]
This behaves correctly, user info is only sent in the ASAuthorizationAppleIDCredential upon initial user sign up. Subsequent logins to your app using Sign In with Apple with the same account do not share any user info and will only return a user identifier in the ASAuthorizationAppleIDCredential. It is recommened that you securely cache the initial ASAuthorizationAppleIDCredential containing the user info until you can validate that an account has succesfully been created on your server. - [Source](https://stackoverflow.com/questions/57545635/cannot-get-name-email-with-sign-in-with-apple-on-real-device)

**Comment by mikehardy** [comment]
what I think is amusing about this is that if they sent it every time, I would never persist that data. But since they only send an id I now *have* to persist the identifying info in non-Apple storage. I must admit I do not understand the security and privacy tradeoffs at play here

**Comment by akhlopyk** [comment]
@bcbcbcbcbcl 
Alright, but how can I get user name and email? I'm confused here.
Thanks for help!

**Comment by mikehardy** [comment]
@akhlopyk you really must consult the source documentation from apple.

The email will come through one time. The first time only. And it may be anonymized. That's just the way it is.

You may not get a single other thing other than a 'userid'.

That's just the way it works.

**Comment by akhlopyk** [comment]
@mikehardy 
Thanks for help! Will check that.

**Comment by tiffanym19** [comment]
even its first time login the responseObject return null :(

**Comment by muhammednazil** [comment]
Anyone have a solution for this

**Comment by Romick2005** [comment]
The solution is to read Readme.md. There you will find:

For testing purposes, to be receive these again, go to your device settings; Settings > Apple ID, iCloud, iTunes & App Store > Password & Security > Apps Using Your Apple ID, tap on your app and tap Stop Using Apple ID. You can now sign-in again and you'll receive the full name and `email

**Comment by ricarrrdoaraujo** [comment]
@Romick2005 It is not working for me, the full name is still null

**Comment by mikehardy** [comment]
It's documented as nullable - https://developer.apple.com/documentation/authenticationservices/asauthorizationappleidcredential/3180384-fullname?language=objc - I think the user can opt to not share it? Unsure - haven't probed this area in quite a while sorry

**Comment by Romick2005** [comment]
> @Romick2005 It is not working for me, the full name is still null

What exactly is not working for you? Can please provide more details? Have you tried to unlink apple account from the app as described in readme?
