### ISSUE TITLE
IOS simulation Error

### ISSUE THREAD

**Issue by yusufsal** [invertase/react-native-apple-authentication#110]
Hi, in ios 13.2.2 simulation I have taken an error like this,
![Simulator Screen Shot - iPhone 8 - 2020-07-09 at 20 30 21](https://user-images.githubusercontent.com/25872651/87071580-162e5300-c223-11ea-920a-a80c6594d866.png)
Is it working in simulation?

Thanks & Regards...

**Comment by mikehardy** [comment]
It definitely works in simulation.
I think you might be running into this #108 
Confirm you have done all the configuration correctly in ios developer console correctly then try again?

**Comment by approached** [comment]
try
```
cd ios
pod install

than =>

yarn ios
```

**Comment by yusufsal** [comment]
@approached Thank you solved my problem...
