### ISSUE TITLE
AppleAuthRequestScope not picking up email / name

### ISSUE THREAD

**Issue by enigmablue** [invertase/react-native-apple-authentication#115]
Work fine on the simulator

On my real device i am using the finger-print auth. When i use my fingerprint i get the below with empty name and email

```
'auth response ', { user: 'xxx',
  email: null,
  authorizedScopes: [],
  fullName: 
   { namePrefix: null,
     givenName: null,
     familyName: null,
     nickname: null,
     middleName: null,
     nameSuffix: null },
  identityToken: 'xxx',
  authorizationCode: 'xxx',
  realUserStatus: 1,
  state: null,
  nonce: 'F9omuX9_F.ItI1-cerNSLYU5zQPwBt7t' }
```

Anyone else having this issue?

**Comment by mikehardy** [comment]
I don't believe you have read the docs - it seems you have unfounded expectations on what will be returned by Apple.
There are plenty of similar issues in the issues list.
You only get email the first time ever. I don't believe you ever get name
