### ISSUE TITLE
"Not supported" error message is very misleading

### ISSUE THREAD

**Issue by ToyboxZach** [invertase/react-native-apple-authentication#116]
This package throws a "not supported" error message in most cases that this package is just not set up correctly. 

I just wasted a good deal of time trying to figure out what was going on. I would suggest maybe adding in details about making sure the package is setup correctly (pod install, xcode config etc) could save a lot of time for a lot of developers.

**Comment by mikehardy** [comment]
duplicate #108 - as mentioned there, pull requests happily accepted (docs pull requests are as easy as filing an issue...)
