### ISSUE TITLE
I can't pass the password prompt

### ISSUE THREAD

**Issue by sdandois** [invertase/react-native-apple-authentication#117]
I've followed the steps in the description, but once I get to the password prompt, I fill my password, press "Continue",
the button grays up for some time and a spinner appears. But then it goes back to its normal color and nothing else happens.

Some other times, I see the 2FA screen, but after inserting the SMS Code I get the same result.

My password is correct. I tried using an incorrect password and a "banging" animation is shown.
I'm using `iPhone 11 iOS 13.6` simulator.

Is someone else having this issue?

```js
console.log(it's executed);
const appleAuthRequestResponse = await appleAuth.performRequest({
        requestedOperation: AppleAuthRequestOperation.LOGIN,
        requestedScopes: [AppleAuthRequestScope.EMAIL,
        AppleAuthRequestScope.FULL_NAME]
});
console.log('it's never executed');

```

![Simulator Screen Shot - iPhone 11 - 2020-07-27 at 12 36 06](https://user-images.githubusercontent.com/44205472/88561560-f4e0ab80-d005-11ea-9879-d240dea3ee96.png)
![Simulator Screen Shot - iPhone 11 - 2020-07-27 at 12 36 18](https://user-images.githubusercontent.com/44205472/88561569-f7430580-d005-11ea-92a3-ef5b8bf0400e.png)

**Comment by yash-sage** [comment]
I'm experiencing the same problem on emulator while running it on xcode 11.6, simulator with iOS version 13.6

**Comment by mikehardy** [comment]
@yash-sage if you can reproduce with the example app fresh cloned from now, please let us know

**Comment by MarkFranceschini** [comment]
@sdandois 
I'm hitting the same exact issue in my code
```
    console.log('before');
    const appleAuthRequestResponse = await appleAuth.performRequest({
      requestedOperation: AppleAuthRequestOperation.LOGIN,
      requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
    });
    console.log('after');
```
When I enter the correct password the nothing happens. If I type in the incorrect password I get the banging animation. Either way my `console.log('after')` is never executed

**Comment by MarkFranceschini** [comment]
Wanted to give a follow up.
I was able to solve the problem by going into my apple developer account and turning `Sign in with Apple` off then back on again
![image](https://user-images.githubusercontent.com/5872914/90183740-035af100-dd82-11ea-8c5a-7c6f68f4e2e9.png)
Not sure why it wasn't working but toggling it off then on has fixed it

**Comment by nimrodbens** [comment]
hey @MarkFranceschini , i tried it but nothing changed. did i miss something? i configured an identifier, a key and a provisioning profile.

**Comment by Simranjit1080** [comment]
> Wanted to give a follow up.
> I was able to solve the problem by going into my apple developer account and turning `Sign in with Apple` off then back on again
> ![image](https://user-images.githubusercontent.com/5872914/90183740-035af100-dd82-11ea-8c5a-7c6f68f4e2e9.png)
> Not sure why it wasn't working but toggling it off then on has fixed it

Can you please explain where is this checkbox for sign in with apple?

**Comment by anthlasserre** [comment]
@MarkFranceschini @sdandois please refer to this comment.
https://github.com/invertase/react-native-apple-authentication/issues/141#issuecomment-698430361

**Comment by NazeerBZ** [comment]
@sdandois have you resolved this issue?
