### ISSUE TITLE
What button type should be chosen for logo-only button?

### ISSUE THREAD

**Issue by matveychuk** [invertase/react-native-apple-authentication#118]
Or how I can reach this goal not via button type? May be setting text as an empty string?

**Comment by mikehardy** [comment]
The Apple UI guidelines about apple auth are pretty clear I think - they do not offer this level of control. The level of control they allow is which type of button you want (continue, sign in, inverse or not) and how much corner rounding. And....that's it if I understand correctly

If you attempt to do it yourself you may not pass approval process for the app store

**Comment by gabrieljoelc** [comment]
my comment was intending to contradict your original comment:

> Apple UI guidelines about apple auth are pretty clear... they do not offer this level of control...

this is incorrect. your last comment is correct but with a dash condescension. 🤷

**Comment by apponthebeach** [comment]
@matveychuk You can do it by specifying height and width with the same value  :

```
<AppleButton
            buttonStyle={AppleButton.Style.BLACK}
            buttonType={AppleButton.Type.DEFAULT}
            style={{
               width: 50,
               height: 50
            }}
            onPress={onAppleButtonPress} />
```
