### ISSUE TITLE
apple signin cancelled

### ISSUE THREAD

**Issue by chaudhary** [invertase/react-native-apple-authentication#119]
When a user cancels the apple signin in between the flow, we do not get any response from performRequest. Ideally, if we get some response corresponding to signin cancelled, we can remove the loader that we are adding earlier from the screen

**Comment by mikehardy** [comment]
PRs happily accepted

**Comment by b8ne** [comment]
@chaudhary This can be handled by wrapping in a try/catch block and using the `AppleAuthError` object.
See [this article](https://hackernoon.com/signing-in-with-apple-in-react-native-app-a-how-to-guide-qk6j32y8) for a good example.
