### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by idkjs** [invertase/react-native-apple-authentication#122]
Are there typing available for this project?

I noticed the `type-check.tsx` file but was not able to get it to give me types. If that is intended, do you mind sharing the command?

Thank you.

**Comment by mikehardy** [comment]
Yes!
I use it like so and it works?

my login button screen
```typescript
import AppleAuth, { AppleButton } from '@invertase/react-native-apple-authentication';
```

my back-end where I do the authentication
```typescript
import AppleAuth, {
  AppleAuthError,
  AppleAuthRequestScope,
  // AppleAuthRealUserStatus,
  // AppleAuthCredentialState,
  AppleAuthRequestOperation,
} from '@invertase/react-native-apple-authentication';
```
