### ISSUE TITLE
'Share My Email' - I get private email

### ISSUE THREAD

**Issue by ealexseen** [invertase/react-native-apple-authentication#123]
I have two emails to choose from - https://prnt.sc/tvssrv
And i go login and i get token with private email.
Maybe there are solutions for this?

**Comment by mikehardy** [comment]
Hi @ealexseen - I think this will come down completely to how the native APIs behave, and I suggest a good read of the relevant apple documentation for the APIs in question (you can see them by browsing the source here - ASAuthentication stuff to search in)

I don't believe the module does a single thing in this respect, it just says the equivalent of "hey Apple APIs, can you do an auth?", and then it consumes the response
