### ISSUE TITLE
[xcode linker error] ld: library not found for -lAppAuth when upgrading to RN62

### ISSUE THREAD

**Issue by enigmablue** [invertase/react-native-apple-authentication#126]
I'm trying to upgrade my react native from 61.2 to 62.
However i am hitting this error. Anyone can advise how to troubleshoot?

`    ld: library not found for -lAppAuth`

My Linker Search path is already having ${inherited} 
I am pasting the library structure below (left side)

![image](https://user-images.githubusercontent.com/35584085/89845996-95ac9a80-dbb2-11ea-8241-767e16ce47fc.png)

**Comment by mikehardy** [comment]
I can only say that 62 worked as does 63. React-native-clean-project perhaps? Reoriduce with the sample app?

**Comment by enigmablue** [comment]
Oh i never heard of the clean project i'd try that. And see how to reproduce.

Also am on legacy build (because was having issues with my realm + bugsnag on the new). But then 61.2 worked fine on legacy too with appauth.

**Comment by enigmablue** [comment]
mm when i switched it to new build system it worked. 

earlier on i had it at legacy because of some issues with other packages. but spent quite a lot of time to fix those now and things are back to normal!

**Comment by mikehardy** [comment]
Glad to hear that! Yes, legacy build seemed to be a thing before, but somewhere around a year ago everything is tolerant of the new build system that I've seen

**Comment by YesSkyscrapers** [comment]
I got the same problem, but with some differents:
`ld: library not found for -lAppAuth`
But i cant change build system, cuz my other libraries dont work with new build system. So I found different solution. I added
`"${PODS_CONFIGURATION_BUILD_DIR}/RNAppleAuthentication"`
to Build Settings > Library Search Paths
Hopes it ll help u!

**Comment by reposocial** [comment]
I was upgrade my react native to 63.4
And use this packages feom 0.1.1 to latest version
However i am hitting this error. Anyone can advise how to troubleshoot?

ld: library not found for -lAppAuth

My Linker Search path is already having ${inherited}

And i was try how to solve this by documentation or article
https://stackoverflow.com/questions/63136505/react-native-0-63-2-ios-build-error-with-ld-library-not-found-for-lappauth
https://stackoverflow.com/questions/62409358/xcode-11-clang-error-linker-command-failed-with-exit-code-1-use-v-to-see-in
FormidableLabs/react-native-app-auth#118
react-native-community/upgrade-support#52

but still NOT SOLVED
And i was stuck 5days.

![105702161-f26ff780-5f3d-11eb-9dc3-b0516a96ee62](https://user-images.githubusercontent.com/34335974/105749273-c3757800-5f75-11eb-86c5-0cfbc1a867d4.png)


Please help me 
@mikehardy

**Comment by mikehardy** [comment]
`npx react-native-clean-project` ? I don't know - definitely works in my work project, definitely works with the example here

**Comment by BogdanTaranenko** [comment]
make sure you open `.xcworkspace` and not `.xcodeproj`
