### ISSUE TITLE
needed pod install??

### ISSUE THREAD

**Issue by keisan1231** [invertase/react-native-apple-authentication#13]
did not work.

Do I need pod install???

**Comment by Ehesp** [comment]
Yes, `cd ios && pod install --repo-update`.

**Comment by keisan1231** [comment]
What should I write on podfile？

**Comment by keisan1231** [comment]
What should I write on podfil

**Comment by Salakar** [comment]
> What should I write on podfile？

With RN 60.+ you shouldn't need to add anything to your podfile as autolinking should pick it up, you just need to pod install as above.
