### ISSUE TITLE
Duplicate interface definition for class 'RNAppleAuthButtonViewManagerWhiteSignUp' when compiling for ios 14

### ISSUE THREAD

**Issue by dbarner1** [invertase/react-native-apple-authentication#130]
Ran a fresh build for an app that's leveraging this repo for apple authentication.

Runs fine on ios 13.

When running on ios 14, with xcode 12 beta 5 getting this error:

<img width="1528" alt="Screen Shot 2020-08-21 at 12 22 46 AM" src="https://user-images.githubusercontent.com/23145200/90852199-db046100-e344-11ea-8e43-06daef048acb.png">

**Comment by mikehardy** [comment]
Hi @dbarner1 - thanks for pointing this out. Seems your the first to try the compile on the beta toolchain

The image is incomplete, but it looks like it helpfully points out where the duplication is on the left there, out of view in the graphic. You can reach right into node_modules and edit the thing until Xcode is happy with it, then use patch-package to make it persistent in your project and maybe propose the change as a PR?

**Comment by dbarner1** [comment]
Thanks @mikehardy - I'm up for the challenge. Will update here on how it goes.

**Comment by dbarner1** [comment]
@mikehardy hold the phone - wasn't on the latest version.  v1.0.6 works perfectly. 🥳

**Comment by mikehardy** [comment]
whew! Had a sense of impending doom about the Xcode12/ios14 release but now I'm feeling better. Thanks for following up
