### ISSUE TITLE
Problem with building on iOS 14

### ISSUE THREAD

**Issue by romanbarzyczakgelato** [invertase/react-native-apple-authentication#133]
<img width="1112" alt="Screenshot 2020-09-04 at 08 59 48" src="https://user-images.githubusercontent.com/52915391/92211599-ffa62000-ee90-11ea-8d0b-d96225c1ffd9.png">
<img width="612" alt="Screenshot 2020-09-04 at 08 59 38" src="https://user-images.githubusercontent.com/52915391/92211606-02a11080-ee91-11ea-981d-b7b1e6a112fd.png">

**Comment by mikehardy** [comment]
Hello!
Text is vastly superior to images for bug reports.
Information you would want, if you were debugging would be versions in use of everything, including a package.json is useful, as well as Xcode version and iOS version
Try `npx react-native-clean-project`

But more than anything, use the example project first and make sure it works, to ensure this is not project-specific

**Comment by colin-oos** [comment]
Any update on this? I'm having the same issue on iOS 14

**Comment by mikehardy** [comment]
1- Why would there be an update on a closed issue?
2- no one ever has the same issue
3- no details on the issue you're having (and this issue was filed with images - terrible for debugging)

I use this module in my work project. My work project compiles fine. That's important to note because if you are having a problem it's 99% that the problem is in your project.

Verify the same using the example app to show it compiles, then if you still have troubles please post a clean reproduction based off `react-native init` so we can troubleshoot

**Comment by colin-oos** [comment]
The issue is with the version. I discovered this is a duplicate of #130 

Upgrading to v1.0.6 resolved it for me and I suspect will also resolve it for @romanbarzyczakgelato

**Comment by mikehardy** [comment]
Ah, interesting. Yes, current stable always before reporting a bug - with the understanding that sometimes this moves quickly, still an important first step. Good luck with your project

**Comment by Goodoose** [comment]
change variable: @interface RNAppleAuthButtonViewManagerWhiteSignUp => @interface RNAppleAuthButtonViewManagerWhiteOutlineSignUp
and this: @implementation RNAppleAuthButtonViewManagerWhiteSignUp => @implementation RNAppleAuthButtonViewManagerWhiteOutlineSignUp
it solve my problem!

**Comment by ShakeebIqbal** [comment]
Any Update on This Issue.  #130

**Comment by mikehardy** [comment]
@ShakeebIqbal why would there be an update? It's a closed issue, there is no current reproduction of an issue like that on current stable code. As far as I know there are exactly zero problems building or using this module with the sole exception that it will not work on ios14 *simulators* (works great on real device, works great on ios13 simulators). Any problem you are having is going to be local / project specific
