### ISSUE TITLE
How to integrate on React Native Versions 0.59

### ISSUE THREAD

**Issue by SyedHaris94** [invertase/react-native-apple-authentication#134]
Hello, is there any work around to integrate react-native-apple-authentication on React Native version 0.59 ?

**Comment by mikehardy** [comment]
There is no support provided for RN<0.60
There was some traffic in the issues if you search, I think some have successfully done it, but I can't see how you can reasonably support modern versions of iOS and Android without upgrading at this point
https://react-native-community.github.io/upgrade-helper/
