### ISSUE TITLE
Invarient Violation: Tried to register two views of the same name RNAppleAuthButtonViewManagerWhiteSignIn

### ISSUE THREAD

**Issue by SyedShehrozSohail** [invertase/react-native-apple-authentication#135]
My XC version is 11.7 and running it on simulator 13.7. I just have imported `import { AppleButton } from '@invertase/react-native-apple-authentication';
` and `View>
            <AppleButton
              buttonStyle={AppleButton.Style.WHITE}
              buttonType={AppleButton.Type.SIGN_IN}
              style={{
                width: 160, // You must specify a width
                height: 45, // You must specify a height
              }}
              onPress={() => onAppleButtonPress()}
            />
          </View>`
![Simulator Screen Shot - iPhone 8 - 2020-09-09 at 10 33 45](https://user-images.githubusercontent.com/49972483/92558676-7f186280-f288-11ea-84c6-d5e2031c7197.png)

**Comment by mikehardy** [comment]
Can you reproduce this with the example? https://github.com/invertase/react-native-apple-authentication/tree/master/example

**Comment by SyedShehrozSohail** [comment]
> Can you reproduce this with the example? https://github.com/invertase/react-native-apple-authentication/tree/master/example
