### ISSUE TITLE
Should the iOS version be > 13.0?

### ISSUE THREAD

**Issue by SrBrahma** [invertase/react-native-apple-authentication#138]
I am not familiar with XCode. The REAME says:

"You are using Xcode version 11 or higher. This will allow you to develop using iOS version 13 and higher, when the APIs for Sign In with Apple became available."

So, should I in my XCode (that is version > 11) select the iOS version to be at least 13 (was 10)?

**Comment by dburdan** [comment]
You can still target a lower iOS version (10, in your case) for your project. The readme is just emphasizing that you need Xcode 11 to build for iOS 13, which is the first iOS version to support Sign In with Apple.

**Comment by SrBrahma** [comment]
Thanks for the quick reply. However, still not clear to me the "which is the first iOS version to support Sign In with Apple". What will I lose if building for v10? Isn't the point of this lib sign in with apple?

**Comment by dburdan** [comment]
This library simply exposes a native iOS feature that wasn't introduced until iOS 13. So users who haven't upgraded yet will be unable to use Sign In with Apple. That's a limitation of the OS, not this library.

The minimum iOS version you choose in Xcode is the lowest version your app will run on; similar to minimum SDK version for Android.

**Comment by mikehardy** [comment]
The example app is instructive. Note that it build for 9:

https://github.com/invertase/react-native-apple-authentication/blob/208ac6378adcf90a90ee7c68956d580f2a27a9b7/example/ios/Podfile#L1

Note that it checks for API support before offering the option to use the other APIs, that's where iOS version support is checked:

https://github.com/invertase/react-native-apple-authentication/blob/208ac6378adcf90a90ee7c68956d580f2a27a9b7/example/app.ios.js#L116-L122
