### ISSUE TITLE
Resetting user authentication state; forgetting "Hide my email"

### ISSUE THREAD

**Issue by allthetime** [invertase/react-native-apple-authentication#144]
Hi,  I'm using sign in with apple on a few apps and have found an issue:  

If the user selects "Hide my email" and then signs out and tries to sign in again, they don't get the option to choose whether to Hide or Show again, it just continues to use the anonymous email.  

 In my case, when the email is hidden certain aspects of the app do not work so we encourage the user to share their email.   

I need the user to be able to logout and then "undo" the hide, but it is not obvious how to do this or if it's even possible programmatically.

**Comment by mikehardy** [comment]
Apple had to do everything different with their sign in solution
To reset everything the user will need to:

- open settings on phone
- open their apple id (top item of settings) settings
- open passwords and security
- open apps using apple id
- hit the "edit" button
- remove your app

**Comment by allthetime** [comment]
@mikehardy 

gross. thanks for the response!

**Comment by denissdubinin** [comment]
For some reason this does not help me, even deleting app still only allows to enter a password
