### ISSUE TITLE
Android compile error - RNAppleAuthentication does not exist

### ISSUE THREAD

**Issue by tempius** [invertase/react-native-apple-authentication#145]
While trying to compile for android, I'm getting the following error.

> android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:15: error: package com.RNAppleAuthentication does not exist
> import com.RNAppleAuthentication.AppleAuthenticationAndroidPackage;
> 
> android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:81: error: cannot find symbol
>       new AppleAuthenticationAndroidPackage(),
>              ^
>   symbol:   class AppleAuthenticationAndroidPackage
>   location: class PackageList

**Comment by mikehardy** [comment]
@tempius something is wrong with your auto-linking (or manual linking, if you are trying to use this with RN59 I suppose, though I wouldn't recommend that). It definitely works, as you can see by using the example.

If you can reproduce this with the example, we can reopen

**Comment by tempius** [comment]
Thanks, indeed, the problem was in my project.
I was getting this error mesage "Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt" with classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version") version 1.3.10, I have upgraded to version 1.3.72 and now it works!
