### ISSUE TITLE
Authenticating via Firebase on Android

### ISSUE THREAD

**Issue by Sebastian-Neubert** [invertase/react-native-apple-authentication#149]
Hello there,

I have successfully set up the Firebase login process on iOS but is there a way to do this on Android as well? I tried passing the *id_token* and the *code* to `AppleAuthProvider.credential()` but that resulted in this error:
```
Something unexpected happened while signing in with Apple NativeFirebaseError: [auth/invalid-credential] The supplied auth credential is malformed, has expired or is not currently supported.
```
Am I missing something or is it actually not possible at the moment?

Regards

**Comment by mikehardy** [comment]
I'm not sure anyone has tried it, you might be first! Unfortunately that means you are the current leading edge of knowledge in the area :sweat_smile:

**Comment by mikehardy** [comment]
This is definitely one of those issues in between the two libraries but might be best in the react-native-firebase library, 

It is supposed to work thought now that I look more deeply:

https://github.com/invertase/react-native-firebase/blob/b84e718f15b9254cffb0202ea956e47014c181a2/packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java#L1400

@dburdan - did you integrate with react-native-firebase for Android Apple auth or are you using something else? If so, do you have it working and it's just an API usage issue here? If not, we'll keep digging

@Sebastian-Neubert the best I can suggest is going into node_modules around the line that I linked there and logging out all the inputs and outputs to the underlying API call to start tracing the data and comparing it vs the assumptions in the code to see where things go off the rails

**Comment by dburdan** [comment]
@mikehardy My implementation was fully bespoke; I'm unfamiliar with Firebase Auth or the RN library, but I'm happy to lend a hand here.

@Sebastian-Neubert Did you pass your nonce value through to Firebase? If I'm not mistaken, I believe Firebase needs just the id_token and nonce.

**Comment by Sebastian-Neubert** [comment]
@dburdan In the iOS implementation I indeed passed the id_token and nonce to Firebase but on Android I don't get a value named nonce from the library. The only available values in the response are: `user`, `state`, `code` and `id_token`

**Comment by dburdan** [comment]
Have you tried generating the nonce before hand and providing it to both libraries as seen in the Android example? The nonce can be any unique, random set of characters, like a UUID.

I will take a deeper look at the return values on Android to make sure they match iOS.

**Comment by Sebastian-Neubert** [comment]
No, I haven't generated the nonce before hand. The iOS-part of the library does that somehow automatically and provides it for me.

**Comment by ghivert** [comment]
Hi, I was stuck with the same problem. I got it working like this:

```javascript
const getRandomString = length => {
  let randomChars =
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
  let result = ''
  for (let i = 0; i < length; i++) {
    result += randomChars.charAt(Math.floor(Math.random() * randomChars.length))
  }
  return result
}

export const appleLogin = async () => {
  return Platform.select({
    ios: iosAppleLogin(),
    android: androidAppleLogin(),
  })
}

const iosAppleLogin = async () => {
  const appleAuthRequestResponse = await appleAuth.performRequest({
    requestedOperation: appleAuth.Operation.LOGIN,
    requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
  })
  if (!appleAuthRequestResponse.identityToken) {
    throw 'Apple Sign-In failed - no identify token returned'
  }
  const { identityToken, nonce } = appleAuthRequestResponse
  const appleCredential = auth.AppleAuthProvider.credential(
    identityToken,
    nonce,
  )
  return auth().signInWithCredential(appleCredential)
}
const androidAppleLogin = async () => {
  // Generate secure, random values for state and nonce
  const rawNonce = getRandomString(20)
  const state = getRandomString(20)

  // Configure the request
  appleAuthAndroid.configure({
    clientId: 'THE SAME SERVICE ID AS APPLE DEV AND FIREBASE CONSOLE',
    redirectUri: 'THIS IS THE SAME AS APPLE DEV CONSOLE',
    responseType: appleAuthAndroid.ResponseType.ALL,
    scope: appleAuthAndroid.Scope.ALL,
    nonce: rawNonce,
    state,
  })
  const response = await appleAuthAndroid.signIn()
  if (response.state === state) {
    const credentials = auth.AppleAuthProvider.credential(
      response.id_token,
      rawNonce, // Passing the rawNonce here do the trick.
    )
    return auth().signInWithCredential(credentials)
  }
}
```

The idea is to generate the nonce ourselves and just passing it to Firebase to let it check if what give Apple is the same as what we give in the nonce.

**Comment by mikehardy** [comment]
Appears this might a documentation / example issue then, or we could decide to handle it internally for Android. I'd take PRs for either

for iOS we do handle it internally (with the ability to disable) - here's a PR that added the ability to disable nonce for ios if people are interested in seeing all the places nonce is touched https://github.com/invertase/react-native-apple-authentication/pull/52

**Comment by dburdan** [comment]
I submitted a [PR (#153)](https://github.com/invertase/react-native-apple-authentication/pull/153) that adds support for automatic nonce generation on Android. While I ran it through various tests, I don't personally use this feature, so additional checks would be appreciated.

Hopefully this provides more parity with the iOS half of the library.

**Comment by alesmraz** [comment]
Hi, i'm facing this issue too. I try to go by documentation and by @ghivert answer but without success. Is there someone with working solution for Firebase? 🙏

web login is open, user fill login info and function `await appleAuthAndroid.signIn()` return object with some data (`user`, `state`, `code` and `id_token`). But when i try to set this data into auth().signInWithCredential() function then it return error: `The supplied auth credential is malformed, has expired or is not currently supported.`

I know this is not stackoverflow but...

there is my code and Firebase config: 

```JS
import { appleAuthAndroid } from '@invertase/react-native-apple-authentication'
import uuid from 'uuid'

const rawNonce = uuid()
const state = uuid()

appleAuthAndroid.configure({
	clientId: 'APPLE_CLIENT_ID',
	redirectUri: 'REDIRECT_CALLBACK',
	responseType: appleAuthAndroid.ResponseType.ALL,
	scope: appleAuthAndroid.Scope.ALL,
	nonce: rawNonce,
	state,
})

const response = await appleAuthAndroid.signIn()

if (response.state === state && response.id_token) {
	const providerData = auth.AppleAuthProvider.credential(
					response.id_token,
					rawNonce // or response.code -> without success
	)

	await auth().signInWithCredential(providerData)
} else {
	throw new Error('Apple sign-in error')
}
```

<img width="677" alt="Screenshot 2020-10-20 at 15 46 45" src="https://user-images.githubusercontent.com/16062058/96596102-a84afa80-12ec-11eb-91d7-782231c85b17.png">

Packages:
...
"@invertase/react-native-apple-authentication": "^2.0.2",
"@firebase/auth": "^0.13.5",
"react-native": "0.63.2"
...

**Comment by ghivert** [comment]
Hi @alesmraz,

It looks like an issue with Firebase. Are you sure you provide the Apple Service ID in Firebase Dashboard ? You can find it on Apple developers Dashboard under service section. I had this error at first because I was providing bundle app ID and not service ID.

**Comment by Sebastian-Neubert** [comment]
It still does not work for me as well. I have everything set up correctly (I guess), even the OAuth settings, but I always get the error:
```
AppleAuth is not supported on the device. Currently Apple Authentication works on iOS devices running iOS 13 or later. Use 'AppleAuth.isSupported' to check...
```

**Comment by mikehardy** [comment]
@Sebastian-Neubert  https://github.com/invertase/react-native-apple-authentication/blob/ac6fa6f4c21f1c6d6d44f0a09fd518df56c31397/example/app.android.js#L101

**Comment by Sebastian-Neubert** [comment]
@mikehardy But why is it not supported?

**Comment by mikehardy** [comment]
@Sebastian-Neubert it is, that line runs and executes correctly. Note it is on a different imported type

**Comment by Sebastian-Neubert** [comment]
@mikehardy You are right, it is supported. But the login with Firebase does still not work. Even the solution from @ghivert does not work for me.

**Comment by alesmraz** [comment]
@ghivert  Thanks for advice! I double checked configuration in Firebase and Apple Developers and it's same. I also try hash (SHA256) nonce before go to apple service server but without success. Also function isSupported return true.

OAuth setting is completed. We already has Apple auth on web (not React native) connected to same firebase without any issues. I assume that is work same (please correct me if its wrong) on web and on non-apple devices?

**Comment by ghivert** [comment]
Hum, that’s weird… It should work in the same for web and Android because it uses OAuth to authenticate in a web-browser. In Android, it’s just a matter of handling the redirect URL correctly. 

The error `The supplied auth credential is malformed, has expired or is not currently supported.` seems like an issue with Firebase itself if `await appleAuthAndroid.signIn()` is working. I think Apple is sending correct informations, but Firebase is not handling them as needed. I had this error when Firebase Auth wasn’t properly configured. I would say that you should double-check Firebase Auth with Apple IDs and Key IDs, and if it really doesn’t work, try to ask the Firebase team directly? If `appleAuthAndroid.signIn()` is working, then it’s not a bug with `react-native-apple-authentication`.

**Comment by matthova** [comment]
@alesmraz any luck? I'm stuck on the same workflow.

**Comment by Samaritan1011001** [comment]
@alesmraz 
I think it is not a firebase issue. The Apple sign in on iOS also uses firebase's `signInWithCredential` and it works. 
I tried using a predefined nonce like the example above but having the same problem. 
Does it have to do something with the `id_token` we get back as response from `await appleAuthAndroid.signIn()` ?

**Comment by MattHorriganSunrise** [comment]
Also having the same issue doing this:
```js
      const response = await appleAuthAndroid.signIn();
      const { id_token } = response;

      const androidCredential = firebase.auth.OAuthProvider.credential(
        id_token,
        rawNonce,
      );

      const userCredential = await firebase
        .auth()
        .signInWithCredential(androidCredential);
```
Looks like I get everything I need with `androidCredential` the:
```
providerId: string;
token: string;
secret: string;
```

but the userCredential doesn't return a UID from Firebase like it does Apple, it doesn't return anything.

**Comment by mikehardy** [comment]
I think you have to decode the idtoken - see #160

**Comment by Samaritan1011001** [comment]
@mikehardy decode the id_token how? That comment in the issue you shared does not mention that.

**Comment by ghivert** [comment]
Did you try with `firebase.auth.AppleAuthProvider.credential` instead of `firebase.auth.OAuthProvider.credential`? I think the `AppleAuthProvider` does the decoding work for you.

**Comment by Horus888** [comment]
I was stuck with the same problem.

**Comment by Shaninnik** [comment]
For me adding correct Services ID to firebase apple auth settings solved the issue, it is optional for iOS so I had it empty. I am using `auth.AppleAuthProvider.credential` and generate nonce manually. Can confirm that it works, if you see apple login page but get the `The supplied auth credential is malformed, has expired or is not currently supported.` then it is probably some issue with your configs.

**Comment by isaactan001** [comment]
Hi, did anyone successfully solved this issue? I am still getting `The supplied auth credential is malformed, has expired or is not currently supported` error when I run firebase.auth().signInWithCredential(credentials). The firebase I am import from `import firebase from 'react-native-firebase'`.

I have ensure that my service id in console.firebase.google.com, developer.apple.com, and source code (clientId) are the same.

**Comment by ghivert** [comment]
It looks like you're using an old version of Firebase. You should try with the latest up to date package `@react-native-firebase/auth` instead of `react-native-firebase`.

**Comment by isaactan001** [comment]
@ghivert Hi, I may not feasible to perform the upgrade as it will cause breaking changes. Currently my version is `"react-native-firebase": "^5.6.0",` may I know what's your working version?

**Comment by ghivert** [comment]
I’m using `"@react-native-firebase/auth": "^12.0.0"`
It will be hard for you if you stay out of sync with the packages.

**Comment by mikehardy** [comment]
Happy to take PRs to resolve issues / extend functionality but as current maintainer the library currently handles my use cases, which means I do not have an interest in volunteering unpaid labor myself for use cases I don't need.

Happy to take those PRs and merge them though if anyone paying attention to this issue is motivated to develop them.

In the meantime closing this as stale
