### ISSUE TITLE
Button text and icon size

### ISSUE THREAD

**Issue by ganesh-papola** [invertase/react-native-apple-authentication#151]
Is the Button text and icon size ratio is good ?
<img width="349" alt="Screenshot 2020-10-14 at 11 56 47 AM" src="https://user-images.githubusercontent.com/19851598/95951591-57329680-0e14-11eb-8006-3051e5217962.png">
device - Iphone 11 pro max

It looks a little big fontSize as compare to the icon.
The standard icon and fontsize -
<img width="301" alt="Screenshot 2020-10-14 at 12 09 29 PM" src="https://user-images.githubusercontent.com/19851598/95952649-205d8000-0e16-11eb-9282-36cad077c4e8.png">

<img width="350" alt="Screenshot 2020-10-14 at 12 01 30 PM" src="https://user-images.githubusercontent.com/19851598/95952027-00798c80-0e15-11eb-9cdf-6432f50d54e8.png">

**Comment by mikehardy** [comment]
If there is something we need to adjust with the library to conform to Apple User Interface Guidelines, we'll happily merge PRs
