### ISSUE TITLE
Getting Error - Cannot read property 'LOGIN' of undefined 

### ISSUE THREAD

**Issue by imsaurabhdixit** [invertase/react-native-apple-authentication#155]
I have follow all the step given here [https://github.com/invertase/react-native-apple-authentication](url) and my login function is 

`try {
      // performs login request
      const appleAuthRequestResponse = await appleAuth.performRequest({
        requestedOperation: AppleAuthRequestOperation.LOGIN,
        requestedScopes: [
          AppleAuthRequestScope.EMAIL,
          AppleAuthRequestScope.FULL_NAME,
        ],
      });

      if (appleAuthRequestResponse['realUserStatus']) {
        this.setState({
          isLogin: true,
        });
      }
    } catch (error) {
      if (error.code === AppleAuthError.CANCELED) {
      }
      if (error.code === AppleAuthError.FAILED) {
        alert('Touch ID wrong');
      }
      if (error.code === AppleAuthError.INVALID_RESPONSE) {
        alert('Touch ID wrong');
      }
      if (error.code === AppleAuthError.NOT_HANDLED) {
      }
      if (error.code === AppleAuthError.UNKNOWN) {
        alert('Touch ID wrong');
      }
    }`

**Comment by imsaurabhdixit** [comment]
`loginWithApple = () => {
    // make sign in request and return a response object containing authentication data
    return appleAuth
      .performRequest({
        requestedOperation: AppleAuthRequestOperation.LOGIN,
        requestedScopes: [
          AppleAuthRequestScope.EMAIL,
          AppleAuthRequestScope.FULL_NAME,
        ],
      })
      .then((appleAuthRequestResponse) => {
        // retrieve identityToken from sign in request
        let { identityToken, email } = appleAuthRequestResponse;
      });
  };`

**Comment by mikehardy** [comment]
You have most likely either not integrated the module correctly (like, forgot `pod install`) or you are not importing it successfully

Please clone the example and run it, if you can reproduce this with the example we can reopen

**Comment by imsaurabhdixit** [comment]
I have already done the pod install and add the add the capability Sign In With Apple .

**Comment by martsie** [comment]
For those having this issue - it looks like something changed in later version where you need to scope types to appleAuth core import. So it'll look like this:

import appleAuth from '@invertase/react-native-apple-authentication';

and then use `ppleAuth.Operation.LOGIN` instead of `AppleAuthRequestOperation.LOGIN`
