### ISSUE TITLE
Sign in with Apple stucks after inputting password

### ISSUE THREAD

**Issue by nguyenvm-valuence** [invertase/react-native-apple-authentication#158]
Hi everyone,
We were able to use Apple sign in before the release of iOS 14.
But after the release of Xcode 12 and iOS 14, the function no longer works on devices with iOS 14.x **on both simulators and real devices**.
It just stops after inputting password and the spinning wheel runs infinitely and does not come back to our application, so the function `performRequest` has not been passed and we have not found out what's wrong.
```js
            appleAuth.performRequest({
                requestedOperation: appleAuth.Operation.LOGIN,
                requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
            });
```

We had checked again with simulator with ios 13.x and it still works.

Have anyone come up with the issue, please help?

Regards.

**Comment by rizbud** [comment]
This issue happens to me. How you fix this?

**Comment by rahmanharoon** [comment]
didyou fixed this issue
