### ISSUE TITLE
Expo support

### ISSUE THREAD

**Issue by Doychev** [invertase/react-native-apple-authentication#16]
Hey all!
Straight to the point - does this support Expo projects? I gave it a quick attempt but I'm getting to some errors which look like it doesn't.
And a follow up in case it doesn't - is it possible to make it work with Expo? If not, what would be a (simple) workaround for that? 

Thanks in advance for any input :)

**Comment by mikehardy** [comment]
Given existence of https://github.com/expo/expo/tree/master/packages/expo-apple-authentication this seems unnecessary

**Comment by Doychev** [comment]
@mikehardy Maybe it's a dumb question, but how do you combine that with a firebase auth solution?

**Comment by mikehardy** [comment]
https://github.com/invertase/react-native-firebase/issues/2884#issuecomment-561219693

I just made a comment on the gist linked there explaining current status as I think most things have been integrated and released now.

But that code actually worked at the time, so as a basis it's solid

**Comment by mikehardy** [comment]
I will add for expo things in general, that ecosystem is so specific and alters so many things that in general it is hard for non-expo projects to puzzle out problems, so we typically refer folks to expo for support

**Comment by Doychev** [comment]
@mikehardy Cool, I'll check that out :) Thanks! If some trivial solution pops-up, please let me know :)

**Comment by arshiuh** [comment]
@mikehardy I just looked into that gist from invertase/react-native-firebase#2884 (comment) and I noticed that you tried to connect react-native-firebase with expo-apple-authentication, but Expo cannot support react-native-firebase due to it being a native module.

Are you sure this worked? Or did it stop working recently?

**Comment by mikehardy** [comment]
It worked great. It's a good module. That module works with ejected (or bare workflow I think is also a correct phrase?) projects. Of course it doesn't work with expo non-ejected (managed workflow?) projects.
