### ISSUE TITLE
how to get user item from appleAuthAndroid response ?

### ISSUE THREAD

**Issue by kidmysoul** [invertase/react-native-apple-authentication#160]
I have implemented sign in with apple in ios and I saved the user to database by "user" item (like 001234.*********.****) from the response.

But when implement SIWA in android I found I cannot get the same user item from appleAuthAndroid response.

```
AndroidResponse:

* code: ***********
*  id_token: "a very long string" 
* state: "**********"

AppleResponse:
{ 
user: '001234.*********.****',
  email: '******',
  authorizedScopes: [],
  fullName: 
   { namePrefix: null,
     givenName: null,
     familyName: null,
     nickname: null,
     middleName: null,
     nameSuffix: null },
  identityToken:  "a very long string same as android" ,
  realUserStatus: 1,
  state: null,
  nonce: '********' }
```

I have to identify the same user both in ios and in android so how can i get the user item in android response ?
Do i have to make another request with idtoken?

**Comment by kidmysoul** [comment]
OK I found I can retrieve sub and email from idtoken by decoding it and the sub is the same as user item in ios response.

**Comment by mikehardy** [comment]
Great - thanks for sharing the process, good luck with your project!

**Comment by Samaritan1011001** [comment]
@kidmysoul How did you decode the idtoken? Can you please share? Thank you.

**Comment by kidmysoul** [comment]
@Samaritan1011001 
I searched from google and found this:
```
function parseJwt(token) {
  let base64Url = token.split('.')[1]
  let base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/')
  let jsonPayload = decodeURIComponent(
    atob(base64)
      .split('')
      .map(function (c) {
        return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2)
      })
      .join('')
  )
  return JSON.parse(jsonPayload)
}
```

and use the above method
```
  const response = await appleAuthAndroid.signIn()
  const { id_token } = response
  const { sub, email } = parseJwt(id_token)
```

**Comment by kidmysoul** [comment]
@Samaritan1011001
I found that the above method doesnot work in my real android device and I finally decide to use auth0/jwt-decode library to decode it.

**Comment by mikehardy** [comment]
@kidmysoul - just for completeness, you import auth0/jwt-decode, then you send the "id_token" element of the JSON response from appleAuthAndroid.signIn() through it, and you get an object with sub and email in it?

This is a very common question by people ("how do I get the email after the first login?") so I want to be 100% sure

Thanks!

**Comment by kidmysoul** [comment]
@mikehardy 

yes that’s right.
