### ISSUE TITLE
Not working on Real device

### ISSUE THREAD

**Issue by jaySoni9292** [invertase/react-native-apple-authentication#161]
tried to integrate but it is working on simulator not on real device

**Comment by azesmway** [comment]
"@invertase/react-native-apple-authentication": "^2.1.0",

`this.onAppleButtonPress = async () => {
      const { setUser, onPressButtomAuth, onCloseAuth, setAppleConfig } = this.props
      let userData = {}

      try {
        const appleAuthRequestResponse = await appleAuth.performRequest({
          requestedOperation: appleAuth.Operation.LOGIN,
          requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME]
        })

        const { user: newUser, email, nonce, identityToken, realUserStatus, fullName, authorizationCode } = appleAuthRequestResponse
        const credentialState = await appleAuth.getCredentialStateForUser(newUser)

        userData.user_os = 'ios'
        userData.user_os_id = appleAuthRequestResponse.user
        userData.device_id = DeviceInfo.getUniqueId()
        userData.email = email ? email : ''
        userData.first_name = fullName.givenName ? fullName.givenName : ''
        userData.last_name = fullName.familyName ? fullName.familyName : ''

        if (identityToken && credentialState === appleAuth.State.AUTHORIZED) {
            setAppleConfig(result, appleAuthRequestResponse)
        }
      } catch (error) {
        if (error.code === appleAuth.Error.CANCELED) {
          console.log('User canceled Apple Sign in.')
        } else {
          console.log(error)
        }
      }`

it works on real device - doesn't work in simulator with ios14
with iOS 13 - work fine

**Comment by mikehardy** [comment]
it works on a real device, you can see with the example
