### ISSUE TITLE
AppleButton does not render on iOS 13.6

### ISSUE THREAD

**Issue by eXist-FraGGer** [invertase/react-native-apple-authentication#163]
**Specs:**

- Xcode Version 12.1 (12A7403)
- iOS 13.6 Simulator
- "react-native": "0.60.5",
- "@invertase/react-native-apple-authentication": "2.1.0",

**Wanted Behaviour**

A Singin with Apple button gets rendered

**Current Behaviour**

Although it is visible in the components tree, there is no button on UI

**Code**

`{IS_IOS ? (
                            <AppleButton
                                onPress={() => this.props.appleLogin()}
                                buttonStyle={AppleButton.Style.WHITE}
                                buttonType={AppleButton.Type.SIGN_IN}
                                style={{
                                    width: 160, // You must specify a width
                                    height: 45, // You must specify a height
                                }}
                                {...commonProps}
                            />
) : null}`

**Misc**

- Perhaps it's worth mentioning that we have other buttons on the page which introduce different ways to log on, have no clue how it might be related though.
- IS_IOS resolves to true
- Strangely enough, it renders on Android with no issue
- https://github.com/invertase/react-native-apple-authentication/issues/14 This issue is out of the question because we have constraints specified

**Comment by mikehardy** [comment]
this likely will be project specific, not sure what is going on but I use this library and it renders - if you can provide a reproduction based on the example app we could see if there is a problem in the library

**Comment by eXist-FraGGer** [comment]
Well, after upgrading @react-native-firebase/app to 9.0.0 and doing pod install --repo-update the issue resolved itself somehow. Might be irrelevant but still, it worked out.
