### ISSUE TITLE
Apple authentication from Web page

### ISSUE THREAD

**Issue by Romick2005** [invertase/react-native-apple-authentication#166]
Hi,
I am trying to implement apple authentication for my old iPhone 5S (max iOS version is 12.4.9).
I was trying to do it using react-apple-signin-auth module. But when importing it I got:
Unable to resolve module ['./AppleSigninButton.css'](https://github.com/A-Tokyo/react-apple-signin-auth/blob/8a13c28494a42abbb73be20481aab76ad1631830/src/AppleSigninButton/AppleSigninButton.js#L8) from eact-apple-signin-auth module.

How I can actually use react-apple-signin-auth in my react-native app? Any examples would help.

Also I was thinking if you have android login enable so why iOS < 13 could not have apple login via web page. Can you please elaborate on this what is the actual problem there and if you could please provide some links for more information that would be great!

The last question is how can I change apple sign in button text from "Sign in with Apple" to translated version fro example "Iniciar sesión con Apple" or some other text. Is there any restriction from apple? Just curious. Thank you!

By the way thank you for the nice library!

**Comment by mikehardy** [comment]
Hi there! Not sure about the import, that's going to be project-specific or perhaps a bug here but we'll need a reproduction based on the example

Great question about web login support for ios < 13, I think it's just historic at this point and lack of implementation. Specifically, Android was not supported until someone posted a PR for it, and web fallback for ios < 13 could be supported but it would also need someone from the community to post a PR as it's not a maintenance priority.

I am committed to doing whatever is necessary to help a contributor though - if you post up a PR for it I will work with you to get it merged, definitely

**Comment by mikehardy** [comment]
Happy to take PRs to resolve issues / extend functionality but as current maintainer the library currently handles my use cases, which means I do not have an interest in volunteering unpaid labor myself for use cases I don't need.

Happy to take those PRs and merge them though if anyone paying attention to this issue is motivated to develop them.

In the meantime closing this as stale

**Comment by mikehardy** [comment]
I rebased it and pushed the result to #335 - it needs testing, and I believe there are comments here that were not addressed

The way to move this forward is to test it, as mentioned on #335, and to look at any of my old comments here and resolve them

Would be cool to see it go in
