### ISSUE TITLE
Add logo only button type

### ISSUE THREAD

**Issue by ha3** [invertase/react-native-apple-authentication#169]
Hello,

Is there a plan to add a logo only option to button types? I'm trying to implement it in a project but I'm confused by SVG related stuff.

Thank you,

**Comment by mikehardy** [comment]
There is no requirement whatsoever to use any Button type included in the library. You can replace them completely with whatever you can come up with using standard react-native elements

As far as I know, we support all the existing button types provided by the official Apple APIs, and there are none that are logo only.

However! Note that if it does not conform to the guidelines issued by Apple for the button, they are free to deny your app
