### ISSUE TITLE
Apple Sign in full name and email getting null

### ISSUE THREAD

**Issue by aqib1604** [invertase/react-native-apple-authentication#17]
I have tried with apple sign in but in response i just got the following response values

user : "045724.ffbe415432436t3653565656435.1539"
identityToken : "eyJraWQiOiJBSURPUEsxIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLnRhbmdvLm"
**email : null**
**fullName:
{ namePrefix: null,
givenName: null,
familyName: null,
nickname: null,
middleName: null,
nameSuffix: null },**
authorizationCode : "fwdsdffsfc414c55ecccd74912bc42d3b8757ff744.0.nxsu.RD8zl-in4lrAPErGexxr2w"

realUserStatus: 1
**state: null,**
authorizedScopes: [],

**so here is the problem i got email,fullName are null.**

So anyone have solution. ?
thanks in advanced.

**Comment by JonathanVegasP** [comment]
I have the same issue!

**Comment by mikehardy** [comment]
If you read the apple sign-in docs I think you'll see that they don't return this information after the initial login, on purpose. All you get after first login is uid. Going to tentatively close but please check and respond to make sure that's correct

**Comment by JonathanVegasP** [comment]
@mikehardy Thanks I read the docs and I removed the app from Password & Security -> Apps that use your Apple id and logged again and it works fine.

**Comment by mikehardy** [comment]
@JonathanVegasP that is actually a neat trick, I had not considered the case where when developing you might want it a second time (after clearing out something from your app). Might make for a good docs PR if you could find a spot for it? I think this will be a frequent question so could save future devs (and maintainers) a bunch of time

**Comment by JonathanVegasP** [comment]
@mikehardy Perhaps i might do this on my free time. Thanks for the the suggestion!

**Comment by mikehardy** [comment]
sure - just for reference, github makes markdown PRs in particular super easy, they handle the whole fork flow so it's like opening a normal web editor, and then when you commit it takes you right to a PR page. Code's not easy but docs are almost fun

**Comment by raymond-finityone** [comment]
> If you read the apple sign-in docs I think you'll see that they don't return this information after the initial login, on purpose. All you get after first login is uid. Going to tentatively close but please check and respond to make sure that's correct

Can someone explain the reason behind this design? Why would it be helpful?

**Comment by fasih-123** [comment]
I still got this issue, when i can press the send button of Gmail.The value is null and didn't sends the mail in IOS

**Comment by Robiullah2244** [comment]
> Might make for a good docs PR

Hi @JonathanVegasP the same thing. But still getting null.

**Comment by Robiullah2244** [comment]
> @JonathanVegasP that is actually a neat trick, I had not considered the case where when developing you might want it a second time (after clearing out something from your app). Might make for a good docs PR if you could find a spot for it? I think this will be a frequent question so could save future devs (and maintainers) a bunch of time

Hi @JonathanVegasP the same thing. But still getting null.

**Comment by tonquocviet1** [comment]
> @mikehardyCảm ơn tôi đã đọc tài liệu và tôi đã xóa ứng dụng khỏi Mật khẩu & Bảo mật -> Ứng dụng sử dụng id Apple của bạn và đăng nhập lại và nó hoạt động tốt.

This is definitely the best way to solve the problem. I followed and succeeded. 👌👌
