### ISSUE TITLE
AppleAuth.isSupported

### ISSUE THREAD

**Issue by djalfirevic** [invertase/react-native-apple-authentication#171]
Hello,

Currently, I'm experiencing this message:

`Error: AppleAuth is not supported on the device. Currently Apple Authentication works on iOS devices running iOS 13 or later. Use 'AppleAuth.isSupported' to check device is supported before calling any of the module methods.`

I'm using iPhone 7 with 14.2. Interestingly, 10 days ago, I was not having any issues with this - same phone, same code.

I've tried iPhone X with 14.2 - same thing.

Any thoughts?

**Comment by mikehardy** [comment]
That is really unexpected, I'm not sure I've checked my real device in the last 10 days! I'll see if I can reproduce.
Does it still work on an simulator with iOS 13.x? (simulator with 14.x was a known issue but 13.x should work). Curious if it is a total failure or what.
Also what version of the plugin are you using, version of Xcode etc etc - all the stuff you'd want if you were trying to reproduce...

**Comment by djalfirevic** [comment]
Hi @mikehardy. Oh, I didn't know if I can test it in the simulator in the first place. Thanks for letting me know what. Will try it right away.

Xcode 12.2
"@invertase/react-native-apple-authentication": "^2.1.0"

**Comment by mikehardy** [comment]
I am using Xcode 12.2 and v2.1.0 of this package and I cannot reproduce this on the simulator with ios13.x and the example app, it is working. It successfully says it is not supported with an ios11 emulator, and (as unfortunately expected) on ios14 simulator it tries to login and accepts the password but then just sits there on the password prompt, re-enabling the button again because ios14 simulator is still busted

on a real device with ios14.2 it works fine.

So, I think something else is going on - what? - not sure at all but it is definitely working for me.

**Comment by AliRehman7141** [comment]
I have no real device and didn't have that much space to download the older version of iOS. It's a risk to send the build to the client without testing it. I have shared the build for now but there should be a way to test it on the latest simulator.

![Screen Shot 2021-01-14 at 12 50 02 PM](https://user-images.githubusercontent.com/33172988/104560457-b9937100-5667-11eb-8e64-ee29a9a6382b.png)

**Comment by mikehardy** [comment]
@AliRehman7141 exactly what are we supposed to do about it? Propose a remedy and I'm interested. Generating notifications for everyone with "should"s does not advance things though...

**Comment by AliRehman7141** [comment]
@mikehardy Sorry! It is possible to test it on the latest simulator?

**Comment by mikehardy** [comment]
You have apparently spent no time reading this issue. So writing more is wasted time on my part, sorry

**Comment by asadMumtaz-YSTL** [comment]
Hi everyone! hope you're fine.

Same error/issue I'm facing on android device & windows OS for coding.
kindly assist me how it resolve.

Thanks

**Comment by mikehardy** [comment]
So you are having the same issue except it is not iOS it is Android and it is not from a macOS computer it's windows, so it's not the same issue at all? That does not seem to make sense on this issue, it seems different.
