### ISSUE TITLE
AppleButton is not displayed on iOS 12.4

### ISSUE THREAD

**Issue by DIGITALSQUAD** [invertase/react-native-apple-authentication#174]
````
<View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: "#fff" }}>
  <AppleButton
    buttonStyle={AppleButton.Style.BLACK}
    style={{ width: 200, height: 50 }}
    onPress={() => this.onAppleButtonPress()}
  />
  <Button
    style={{ width: 200, height: 50 }}
    onPress={() => this.props.toggler(false)}
    title={I18n.t("buttons.cancel")}
  />
</View>
````
**iOS 12.4**
<img src="https://user-images.githubusercontent.com/6149827/101624912-062ecf80-3a5e-11eb-957b-7acb3fd98985.png" width="300px">

**iOS 14.2**
<img src="https://user-images.githubusercontent.com/6149827/101624919-09c25680-3a5e-11eb-81c6-ff5d93e11ca4.png" width="300px">

**Comment by mikehardy** [comment]
:thinking: How exactly do you expect an API introduced in iOS13 to work on iOS12? Check isSupported (it will be false on iOS12) and do not attempt to show the button

This is expected behavior
