### ISSUE TITLE
Apple login is not authorized by touch id on iPhone 8

### ISSUE THREAD

**Issue by ahmedsoror-sbs** [invertase/react-native-apple-authentication#176]
Hello

I tried to apple login on iPhone 8

when apple login, I used touch id without a manual password

but it says that it is not AUTHORIZED

can you help how to fix this issue

**Comment by mikehardy** [comment]
Is this with the example app? If you can reproduce it in the example app let me know, also - make sure it's a real device and the operating system version is important, no?

**Comment by ahmedsoror-sbs** [comment]
```
handleAppleSignIn = async () => {
    const { zip } = this.state;
    try {
      const appleAuthRequestResponse = await appleAuth.performRequest({
        requestedOperation: appleAuth.Operation.LOGIN,
        requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
      });
      console.log('appleAuthRequestResponse', appleAuthRequestResponse);

      const {
        user,
        email,
        fullName,
        nonce,
        identityToken,
        realUserStatus,
      } = appleAuthRequestResponse;

      const credentialState = await appleAuth.getCredentialStateForUser(user);
      // use credentialState response to ensure the user is authenticated
      if (credentialState === appleAuth.State.AUTHORIZED) {
        // user is authenticated
        AsyncStorage.setItem('AppleEmail', email);
        this.setState(
          {
            fname: fullName.givenName,
            lname: fullName.familyName,
            emailId: email,
            appleId: user,
            zip: zip,
          },
          () => {
            this.SignUpApiCall(2);
          },
        );
      }
    } catch (error) {
      if (error.code === appleAuth.Error.CANCELED) {
        console.warn('User canceled Apple Sign in.');
      } else {
        console.error(error);
      }
    }
  };
```

**Comment by ahmedsoror-sbs** [comment]
according to apple login with manual password, it works perfectly
But when apple login with touch id, credentialState is not AUTHORIZED.
I tested on iPhone 8

**Comment by ahmedsoror-sbs** [comment]
```
const {
        user,
        email,
        fullName,
        nonce,
        identityToken,
        realUserStatus,
 } = appleAuthRequestResponse;
```
According to this code, I can get `user`
but `email` and `fullName` is null

**Comment by ahmedsoror-sbs** [comment]
![appleLogin](https://user-images.githubusercontent.com/75054296/102007519-c6831480-3cf7-11eb-8095-4cf6e1c56ce4.gif)
as you can see in this gif file, the apple login is succeeded
but `credentialState` is not AUTHORIZED

**Comment by ahmedsoror-sbs** [comment]
I tested on the Real device (iPhone 8)

**Comment by mikehardy** [comment]
> Is this with the example app? If you can reproduce it in the example app let me know, also - make sure it's a real device and the operating system version is important, no?

**Comment by mikehardy** [comment]
> ```
> const {
>         user,
>         email,
>         fullName,
>         nonce,
>         identityToken,
>         realUserStatus,
>  } = appleAuthRequestResponse;
> ```
> 
> According to this code, I can get `user`
> but `email` and `fullName` is null

This is a common misunderstanding of how the library works. Previous issues contain details if you search

**Comment by ahmedsoror-sbs** [comment]
https://github.com/invertase/react-native-apple-authentication/issues/173#issuecomment-740658755
I have read this article

**Comment by ahmedsoror-sbs** [comment]
> device's preferences
> tap in to your user settings
> tap into password & security
> tap in to apps using apple id
> tap in to the app in question
> tap stop using apple id

**Comment by ahmedsoror-sbs** [comment]
can you guide me with the screenshots? I can't follow the above instruction

**Comment by mikehardy** [comment]
I think you have a misconception about how open source works, and the level of service provided
This library was entirely written by one person in approximately 1 day, and has more or less worked completely correctly since then, no problem related to it should last more than a day

Get adventurous: Dive into the source code, add console logging statements, search the issues lists etc

I will not provide screenshots, sorry - also I'll be out the entire rest of the day so won't be responding, sorry

**Comment by ahmedsoror-sbs** [comment]
> device's preferences
> tap in to your user settings
> tap into password & security
> tap in to apps using apple id
> tap in to the app in question
> tap stop using apple id

I followed this guide and it is resolved

Thank you
