### ISSUE TITLE
Not working for Android 

### ISSUE THREAD

**Issue by Pradeep0801** [invertase/react-native-apple-authentication#184]
I am getting an error when trying to use the sign in with apple on android device 

  Error  1 :  TypeError: undefined is not an object (evaluating '_reactNativeAppleAuthentication.appleAuthAndroid.ResponseType.ALL')
  
  Error 2 : TypeError: undefined is not a function (near '..._reactNativeAppleAuthentication.appleAuthAndroid.configure...')
  
  Sample code : 
    const rawNonce = uuid();
    const state = uuid();
    appleAuthAndroid.configure({
      clientId: 'xxxxxx',
      redirectUri: 'xxxxxxx',
      responseType: appleAuthAndroid.ResponseType.ALL,
      scope: appleAuthAndroid.Scope.ALL,
      nonce: rawNonce,
      state,
    });

  try{
  const response = await appleAuthAndroid.signIn();
  if (response) {
    const code = response.code; // Present if selected ResponseType.ALL / ResponseType.CODE
    const id_token = response.id_token; // Present if selected ResponseType.ALL / ResponseType.ID_TOKEN
    const user = response.user; // Present when user first logs in using appleId
    const state = response.state; // A copy of the state value that was passed to the initial request.
    console.log("Got auth code", code);
    console.log("Got id_token", id_token);
    console.log("Got user", user);
    console.log("Got state", state);
  }
} catch (error) {
  if (error && error.message) {
    switch (error.message) {
      case appleAuthAndroid.Error.NOT_CONFIGURED:
        console.log("appleAuthAndroid not configured yet.");
        break;
      case appleAuthAndroid.Error.SIGNIN_FAILED:
        console.log("Apple signin failed.");
        break;
      case appleAuthAndroid.Error.SIGNIN_CANCELLED:
        console.log("User cancelled Apple signin.");
        break;
      default:
        break;
    }
  }
}

 "@invertase/react-native-apple-authentication": "^2.1.0"
   "react": "16.13.1",
   "react-native": "0.63.3",

**Comment by mikehardy** [comment]
How did it go when you tried the example? It works last I checked, indicating you have a project-specific issue

**Comment by Pradeep0801** [comment]
TypeError: undefined is not a function (near '..._reactNativeAppleAuthentication.appleAuthAndroid.configure...')

i am getting this error

@mikehardy

**Comment by mikehardy** [comment]
I just checked out the example on my computer and tried it. Seems to work fine.
You have a project-specific error. Most likely react-native auto-linking either not set up correctly in general or not set up for this app.
I suspect you did not actually run the example app? It should have worked

**Comment by Pradeep0801** [comment]
it is working now, I have to do some manual linking in react-native version 0.63.
@mikehardy thanks for the quick response, I really appreciate it.

also, is there any way to get email and user name on every sign in ??

**Comment by mikehardy** [comment]
> it is working now, I have to do some manual linking in react-native version 0.63.

Glad you are moving forward but needing manual linking of any kind is a likely sign of something wrong with your project. It bears examination. This module does not need manual linking of any kind, as the example demonstrates

> also, is there any way to get email and user name on every sign in ??

This is frequently asked, search the issues list and documentation, where there is example code even.

**Comment by Pradeep0801** [comment]
Yes we have upgraded our project from 0.59 to 0.63, that's why we are facing such issues

**Comment by mikehardy** [comment]
this https://github.com/facebook/react-native/blob/6bfd89d27724f2aac602fa2acbf4753950f4152e/template/android/app/build.gradle#L84

and this https://github.com/facebook/react-native/blob/6bfd89d27724f2aac602fa2acbf4753950f4152e/template/android/app/build.gradle#L222

do auto-linking

If you haven't seen https://react-native-community.github.io/upgrade-helper/ you should check it out - very helpful
