### ISSUE TITLE
Error: AppleAuth is not supported on the device. 

### ISSUE THREAD

**Issue by dawntommm** [invertase/react-native-apple-authentication#185]
Getting error saying 
`Error: AppleAuth is not supported on the device. Currently Apple Authentication works on iOS devices running iOS 13 or later. Use 'AppleAuth.isSupported' to check device is supported before calling any of the module methods.`
I am running expo react native app on Xcode, with my iPhone 11 on iOS 14.3
I believe it should be supported, is there any reason why that happens?

**Comment by mikehardy** [comment]
No reason that should happen.
Have you reproduced with the example app?

**Comment by dawntommm** [comment]
Please close this, this is my bad.
I forgot to pod install.
However the error message is confusing, I would expect something like 'You forgot to install the library'

**Comment by mikehardy** [comment]
That is a terrible user experience - sorry for that. Sure you have to remember to pod install but Pods can be missing for any number of reasons besides just plain forgetting (which is also common) and an error message that is more specific would be nice. I tagged you on an issue we have open that is related, FWIW. Good luck with your project

**Comment by MilosR** [comment]
Same case here, however I didn't get any message, pop-up is not sowing and `AppleAuth.isSupported ` was false. (iPhone8 - Simulator). Forgot to do `pod install`

**Comment by zoobibackups** [comment]
I have two time done pod install but the  console.log(appleAuth.isSupported); is always false

**Comment by ArthurCNR** [comment]
Check if you correctly executed yarn add package and pod install (or clean pods & build and install again)
