### ISSUE TITLE
Apple sign in Could Not Connect error

### ISSUE THREAD

**Issue by onatvaris** [invertase/react-native-apple-authentication#188]
Hello, I added an apple entry at the request of apple in my react native project. They did not detect an error when I submitted it to the apple side with the same codes in a different project and they allowed me to publish my application.

However, they found such a problem in this project and sent it.

![Ekran Resmi 2021-01-20 01 53 54](https://user-images.githubusercontent.com/51972191/105104372-29b85180-5ac3-11eb-9334-5fc6fc2c283a.png)

When I test it in debug mode, it stays like this on the screen.

<img width="423" alt="Ekran Resmi 2021-01-20 01 53 42" src="https://user-images.githubusercontent.com/51972191/105104293-05f50b80-5ac3-11eb-8bb1-a44930c1dc76.png">

```
"dependencies": {
    "@invertase/react-native-apple-authentication": "^2.1.0",
    "@react-native-community/checkbox": "^0.5.6",
    "@react-native-community/google-signin": "^5.0.0",
    "@react-native-firebase/admob": "^10.1.1",
    "@react-native-firebase/app": "^8.4.7",
    "@react-native-firebase/auth": "^9.3.2",
    "@react-native-firebase/firestore": "^7.9.1",
    "@react-native-firebase/storage": "^10.0.0",
    "@react-native-picker/picker": "^1.9.8",
    "native-base": "^2.13.14",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-countdown-circle-timer": "^2.3.10",
    "react-native-drawer": "^2.5.1",
    "react-native-fbsdk": "^2.0.0",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-iap": "^5.2.1",
    "react-native-image-picker": "^2.3.4",
    "react-native-progress-circle": "^2.1.0",
    "react-native-reanimated": "^1.13.2",
    "react-native-router-flux": "^4.2.0",
    "react-native-screens": "^2.16.1",
    "react-native-svg": "^12.1.0",
    "react-native-video": "^5.1.0-alpha8",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
```

```
onAppleButtonPress = async () => {
    // Start the sign-in request
    const appleAuthRequestResponse = await appleAuth.performRequest({
      requestedOperation: appleAuth.Operation.LOGIN,
      requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
    });

    // Ensure Apple returned a user identityToken
    if (!appleAuthRequestResponse.identityToken) {
      throw 'Apple Sign-In failed - no identify token returned';
    }

    // Create a Firebase credential from the response
    const {identityToken, nonce} = appleAuthRequestResponse;
    const appleCredential = auth.AppleAuthProvider.credential(
      identityToken,
      nonce,
    );

    console.log('appleCredential :>> ', appleCredential);
    // Sign the user in with the credential
    return auth().signInWithCredential(appleCredential);
  };

```
This onPress Fuction --> 

```
if (appleAuth.isSupported === true) {
                  this.onAppleButtonPress().then((res) => {
                    this.props.succesLoginUser(res);
                    console.log('Signed in with Apple!', res);
                  });
                } else {
                  Alert.alert(
                    'Your iOS version must be 13.0 and above',
                    '',
                    [
                      {
                        text: 'OK',
                        onPress: () => console.log('OK Pressed'),
                      },
                    ],
                    {cancelable: false},
                  );
                }
```

**Comment by mikehardy** [comment]
I tested this just today and it worked. You must tell them to use an ios13 emulator when testing, Apple has an error in their ios 14 simulators that causes it to hang, you can search other issues - I'm pretty sure this is it.

If you can reproduce an issue with the example in this project, we can reopen and examine

**Comment by FRizzonelli** [comment]
@mikehardy I've just got the same rejection error this morning (but on our devices is working smoothly). You're telling me that I'd say to Apple that they have a bug in their simulators to have my application accepted? 😢

**Comment by mikehardy** [comment]
@FRizzonelli yep! That's exactly it. It feels dumb to type but I don't get rejected, I have a reviewer note that says "If you test Sign In With Apple you must use a real device or ios13 simulator. ios14 simulators have a known bug where they hang Sign In With Apple". And we all move on with our lives (hopefully with app approvals...)

**Comment by FRizzonelli** [comment]
@mikehardy Life is beautiful. Well thank you for your time Mike. I've submitted a new version and hope to get it approved!

**Comment by raymondctc** [comment]
> @FRizzonelli yep! That's exactly it. It feels dumb to type but I don't get rejected, I have a reviewer note that says "If you test Sign In With Apple you must use a real device or ios13 simulator. ios14 simulators have a known bug where they hang Sign In With Apple". And we all move on with our lives (hopefully with app approvals...)

@milkehardy do you have any official issue link mentioned about this bug? As I encountered this during app submission occasionally. I would like to explain this to the reviewer with a more solid argument.

**Comment by mikehardy** [comment]
All the information I have is contained in this issue, and was simply discovered by testing various combinations here.

**Comment by TreemboLuisDev** [comment]
Any updates on how to correct this? Apple just rejected my app and saying them to use iOS 13 doesn't work.

**Comment by mikehardy** [comment]
@TreemboLuisDev do you see any updates? I do not see any updates. It's open source, if there were updates, they'd be right here. What you have discovered in testing on iOS14? If you discover a solution please let us know

**Comment by rockstarrabbitri** [comment]
I have the same issue. But my app wasn't sent to review yet. On my iPhone with iOS 16.5 I don't meet the issue but on iPhone with iOS 15.6 it happens sometimes but not always.
Is there any updates?
