### ISSUE TITLE
appleAuth.isSupported always false

### ISSUE THREAD

**Issue by VictorKolb** [invertase/react-native-apple-authentication#19]
Hi! Thanks for great plugin!

I faced with strange behaviour. appleAuth.isSupported always false. 
Phone 6s, iOS 13.2.3, 
macOS 10.15.2, 
react-native 0.61.2

**Comment by Salakar** [comment]
Interesting, not sure why this would be false unless the device isn't iOS 13+; the logic happens on native here:

https://github.com/invertase/react-native-apple-authentication/blob/master/ios/RNAppleAuthentication/RNAppleAuthModule.m#L43

And read in JS here: https://github.com/invertase/react-native-apple-authentication/blob/master/lib/AppleAuthModule.js#L39

**Comment by VictorKolb** [comment]
@Salakar maybe I can try to logging native part somehow?

**Comment by VictorKolb** [comment]
I put `NSLog(@"%@", @available(iOS 13 .0, *) ? @"IOS13.YES" : @"IOS13.NO");` into my `AppDelegate.m` and got `IOS13.YES` on Xcode console.

**Comment by VictorKolb** [comment]
Oh, my bad! I forgot `pod install`. Maybe I send pr to update documentation?

**Comment by traviswimer** [comment]
@VictorKolb I'm really confused what is happening here. To get this to work I had to add this to my Podfile:
```
pod 'RNAppleAuthentication', :path => '../node_modules/@invertase/react-native-apple-authentication'
```
Is that what you did as well?

As far as I know, this shouldn't be necessary with Auto-linking, so I'm really confused why this doesn't work automatically. 

Can anyone confirm if this is a bug in the library or if I just have something weird in my setup?

**Comment by mikehardy** [comment]
@traviswimer something weird in your setup I believe, it was not necessary for me

Probably missing one of the two lines that pull in the Podfile auto-linking code and then execute it:
- pull in here: https://github.com/invertase/react-native-apple-authentication/blob/master/example/ios/Podfile#L3
- execute it (auto-link) here: https://github.com/invertase/react-native-apple-authentication/blob/master/example/ios/Podfile#L37

Note that it appears the example has the pod defined, but notice the reference is to `../../` - that's just to reference the raw code during dev. In my work project I have no reference

**Comment by traviswimer** [comment]
@mikehardy Good call, I was missing line 3. I guess this just happened to not effect other Auto-linked libraries I'm using. 
¯\\\_(ツ)\_/¯

**Comment by sahil290791** [comment]
What is difference between **isSupported** and **isSignUpButtonSupported**?
