### ISSUE TITLE
On Android it doesn't ask to hide or share my email and as a result it always returns private email.

### ISSUE THREAD

**Issue by maulikdhameliya** [invertase/react-native-apple-authentication#190]
I am implementing the apple signin on android, but when I enter apple signin and password, it doesn't ask to share or hide my email and directly returns private email when I decode JWT Token.

Below screenshot was taken from [this blog](https://johncodeos.com/how-to-add-sign-in-with-apple-button-to-your-android-app-using-kotlin/) where it asks for it on native android. 
Blog link https://johncodeos.com/how-to-add-sign-in-with-apple-button-to-your-android-app-using-kotlin/

![image](https://user-images.githubusercontent.com/12501230/105487728-948da680-5cd6-11eb-93e9-bf025825cb8b.png)

**Comment by mikehardy** [comment]
I believe this is how Apple Sign in works, that's their widget, not ours, this is just what we get when we call their APIs.
If I am incorrect, and you can see some API that we're using incorrectly please propose a PR to correct and I'll happily incorporate it
