### ISSUE TITLE
Support for square button?

### ISSUE THREAD

**Issue by hugoh59** [invertase/react-native-apple-authentication#191]
As shown in here, https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/buttons/#:~:text=By%20default%2C%20the%20Sign%20in,with%20Apple%20Buttons%20(web). 
A button without the text.

**Comment by mikehardy** [comment]
If we do not already provide it, we will happily merge a PR implementing a wrapper for any underlying styles that are missing
