### ISSUE TITLE
Uppercase for iOs

### ISSUE THREAD

**Issue by sn4f** [invertase/react-native-apple-authentication#192]
Hi guys im going to set this button as uppercase and..
is there such an option? how can i do this?

@apple comment
https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/buttons/
`In general, preserve the capitalization style of the title. By default, all variants of the button title capitalize the first word — that is, Sign or Continue — and Apple; all other letters are lowercase. Avoid changing this style unless your interface uses only uppercase.`

**Comment by mikehardy** [comment]
Hi there! There is no option for this with the built in button styles that we wrap+expose from the iOS native libraries. You would do this by making a custom UI element in react-native same as you would any other button. Good that you linked the HIG docs as that indicates you will hopefully not get any picky App Store Review people rejecting your app for not following the guidelines with the custom button vs their provided ones. Haven't heard of that happening but it is of course their prerogative. Good luck with your project
