### ISSUE TITLE
Hangs on for ios 14 for simulator and real devices

### ISSUE THREAD

**Issue by htuzel** [invertase/react-native-apple-authentication#193]
Hello,

It is not only for the simulator. It happens on physical devices, too. My code is working well with ios 13 but for ios 14 it hangs on the simulator and the physical device (I am using test flight.)

Also, my application is rejected because of that.

There is no error log, it is just not working.

**Comment by mikehardy** [comment]
duplicate: #141 - opening new issues does not help.
We can reopen the old issue if needed but we **must** have a reproduction.
I do not reproduce this, I just tested it a few hours ago.
No reproduction -> no ability to fix even if I/we want to...

**Comment by htuzel** [comment]
Hello @mikehardy,
Firstly, I am aware that it is an open-source repo, and thank you to create this great repo. But, I think it is a real issue and you may get more info if you can keep this issue open for a while.

Thank you.

**Comment by mikehardy** [comment]
I will reopen the original issue, I will not manage duplicate issues
Please post **anything** we can use to reproduce, and we will give it a shot, otherwise, the issue will lie dormant.

**Comment by skizzo** [comment]
@htuzel this happens to me too on iOS 15.5 simulator. Did you solve this?
