### ISSUE TITLE
identityToken sometimes null

### ISSUE THREAD

**Issue by karlpower6** [invertase/react-native-apple-authentication#194]
Probably not an issue with this library but wondering what kind of situation could cause the `identityToken` to be `null` when `performRequest()` succeeds? 

We're seeing it returned as `null` around 50% of the time while `authorizationCode`, `nonce` and `user` have values.

- "react-native": "0.61.4",
- "@invertase/react-native-apple-authentication": "^2.0.2",
- iOS 13.3.1 and upwards

**Comment by mikehardy** [comment]
I've not noticed this (not to say it is not happening!) personally, so I have no special insight. I'm usually the only responder here though, I suggest asking on stackoverflow or perhaps there are some lurkers here that have seen this and could respond...

**Comment by bobinrinder** [comment]
We're experiencing it too, we haven't made updates to the app in days and just today it started flooding in out of nowhere, zero occurrences before... 😱

**Comment by bennom** [comment]
Same for us. But this doesn't seem to be related to this library in particular. We are using this library on our mobile apps, **but our web platform** is having the same issue: "Invalid token specified". On web we are using the SDK from here `appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js`.

Yet we cannot give more detailed information, sadly.

**Comment by rajtejani** [comment]
I'm also experiencing this isssue.
![WhatsApp Image 2021-03-01 at 9 43 23 PM](https://user-images.githubusercontent.com/49932204/109594539-fd1f3d00-7b38-11eb-9a79-d8da38db0bfb.jpeg)

**Comment by DIGITALSQUAD** [comment]
Same here. 
I looked up my server's log, and found that some users succeed but some users failed. 

I found [an apple developers thread about this issue.](https://developer.apple.com/forums/thread/675004)
This might be a problem with the Apple servers and some users says that already resolved and some says not yet.
I tried on my server with my apple id and succeeded, but not sure already resolved for other users.

**Comment by karlpower6** [comment]
@DIGITALSQUAD
Thanks for sharing this issue. It seems to be the relevant one.

I would mention that for us, we do not see some users failing and others succeeding. It's more like a lottery, where we can get a token for a user 10 seconds after a previous auth request for the same user returns an object without a token.

**Comment by mikehardy** [comment]
Given this module is actually quite simple in it's Objective-C code - just wrapping the platform API and that's effectively it - with no release here, this *should* be an upstream issue so I am not surprised at @DIGITALSQUAD 's apple thread reference and was in fact expecting that.

Unfortunately I think the actual resolution here is "wait impatiently while Apple fixes it"

**Comment by bobinrinder** [comment]
FYI: For us it seems to have resolved itself with no changes.

**Comment by mikehardy** [comment]
Thanks for the report - I'm going to close this since I think it wasn't actionable here either way and is (very thankfully) apparently resolved.

The joy of distributed systems, especially when part of it is not in your control at all :-)
