### ISSUE TITLE
Can't change text value?

### ISSUE THREAD

**Issue by dzpt** [invertase/react-native-apple-authentication#197]
What's about other languages? I want to change "Sign in with Apple" text

**Comment by mikehardy** [comment]
Hi there!
1) you don't really need to, it will naturally show up in the user's language if you use the Apple provided buttons
2) go right ahead! as long as you manually construct your own button (with your own translations) that looks like it follows the Apple design guidelines, they'll approve your app, no problem. You don't have to use the apple provided buttons at all

**Comment by dzpt** [comment]
@mikehardy hi Mike, what's about font? I've tried to change it on textStyle but didn't work.
is that in design guideline of Apple to use specific font so i can't change it?

**Comment by mikehardy** [comment]
You can read the design guidelines and tell me. Apple guidelines are authoritative, I'm just some person on the internet.
