### ISSUE TITLE
undefined is not an object (evaluating '_reactNativeAppleAuthentication.AppleAuthRequestOperation.LOGIN')

### ISSUE THREAD

**Issue by 3DJakob** [invertase/react-native-apple-authentication#199]
I'm trying to implement this module however whenever I use the sample code and press the sign in button I get the error `Possible Unhandled Promise Rejection (id: 5):
TypeError: undefined is not an object (evaluating '_reactNativeAppleAuthentication.AppleAuthRequestOperation.LOGIN')` 

With the code:
```
        try {
            const appleAuthRequestResponse = await appleAuth.performRequest({
                requestedOperation: AppleAuthRequestOperation.LOGIN,
                requestedScopes: [
                  AppleAuthRequestScope.EMAIL,
                  AppleAuthRequestScope.FULL_NAME
                ],
              });
              const { identityToken } = appleAuthRequestResponse;
              console.log(identityToken, 'identityToken')


        } catch (error) {
          if (error.code === AppleAuthError.CANCELED) {
            // user cancelled Apple Sign-in
        
          } else {
            // other unknown error
          }
        }
```

I cannot seem to find anyone with the same issue... I have gone through the setup guide multiple times and also followed other tutorials. I have made sure to add the sign-in capability and also manually added a provisioning profile that includes the sign-in. Anyone any ideas?

**Comment by mikehardy** [comment]
How did it work when you used the example? It should work - then when you copy the example code in basically without changing, it should work?

I'm guessing the native module is not installed correctly, a common react-native occurrence. You don't indicate what platform or version or show any files that might help though, so I can't guess further.

If the example works, the module works though - implying this is a project-specific problem and not a module issue, so I'm going to close this. If you can provide a minimal reproducible example showing a bug in the module we can open and triage more

**Comment by 3DJakob** [comment]
I understand that you closed this issue I was more or less just trying to get help using it. For future reference what was wrong with the code is that I used `appleAuth.AppleAuthRequestOperation.LOGIN` instead of `appleAuth.Operation.LOGIN`. Presumably this was at some point renamed and I simply used a outdated tutorial.

**Comment by mikehardy** [comment]
I would file this under "use typescript", and I'm joking a bit, but also it eliminates these kinds of errors completely

**Comment by expertcoder17** [comment]
@mikehardy I am using react native js and getting same error So can you guide me how can i resolved that Its very urgent for me.Please help me asap.

**Comment by mikehardy** [comment]
I'm on vacation. The example app works. The module works. Keep checking your code and project...
