### ISSUE TITLE
AppleAuthProvider is not existing

### ISSUE THREAD

**Issue by joshuadiezmo** [invertase/react-native-apple-authentication#2]
![Screen Shot 2019-12-05 at 11 51 45 PM](https://user-images.githubusercontent.com/8644115/70251302-33e19880-17ba-11ea-89fc-8b634e98bc18.png)

**Comment by mikehardy** [comment]
Is this a firebase issue really? If the example here works, the module works. If you want to integrate with firebase I believe you must apply a patch that is available from the linked react native firebase issue, and possibly in these docs

**Comment by mikehardy** [comment]
Hey @joshuadiezmo react-native-firebase v6 and v5 support it with current (just-released) releases now. Either v6.2.0 or v5.6.0. Cheers!
