### ISSUE TITLE
Support for coloured backgrounds for the button

### ISSUE THREAD

**Issue by iaxelrad** [invertase/react-native-apple-authentication#201]
As I understand, you cannot set a background color for the button which isn't black or white. 
Is there goung to be such an option in the future?

**Comment by mikehardy** [comment]
No. Apple provides those buttons, we do nothing related to them.

If you must style things, you will need to create a button from scratch as mentioned in the other 10 issues https://github.com/invertase/react-native-apple-authentication/issues?q=is%3Aissue+button+style+

Also as mentioned in those issues, Apple may reject your app if you do not follow their style guidelines.
