### ISSUE TITLE
Android Build Error

### ISSUE THREAD

**Issue by tolgaberk** [invertase/react-native-apple-authentication#202]
> Task :invertase_react-native-apple-authentication:compileDebugKotlin FAILED
> /node_modules/@invertase/react-native-apple-authentication/android/src/main/java/com/RNAppleAuthentication/webview/SignInWebViewDialogFragment.kt: (63, 13): Unresolved reference: webViewClient

Hi, this error is appeared out of literally nothing. i was in the office last night and builds were successfull. and today i can not have a successful build. do you have any idea what might've caused it ? 

## React native info
>System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 465.03 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 26, 28, 29, 30
      Build Tools: 26.0.2, 28.0.3, 29.0.2, 30.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1.1 4.1.1
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Question
And also i am not actually using apple auth on the android side. i use google auth so apple forces me to use apple auth but i don't use it on the android side as i said. is there any way that i can strip it out from only android side? if there is would you point me to that direction. i would really appreciate it.

Thanks.

**Comment by mikehardy** [comment]
Strange, does this reproduce with the example app included in this repo?
Random build errors for me usually mean it is time to run `npx react-native-clean-project`
You could strip it out I guess, but if this fails there will likely be some other sort of build failure. That said probably just an `rm -rf node_modules/react-native-apple-authentication/android` would do it, though you'd want to persist that via patch-package or similar

**Comment by harashvaradhan** [comment]
Same here, I got this error yesterday evening on Android. Though on iOS it was working fine. Today morning when I ran it again on Android without any code change the error was gone. What I can remember is I have only started with fresh metro bundler this morning.

**Comment by mikehardy** [comment]
Okay - with lack of reproduction, and apparently environmental / project-specific reasons causing it, while my project is building fine, I'm going to close this as unactionable

**Comment by tolgaberk** [comment]
i have figured out what was causing it. there was a package in the project with compileSdkVersion as 23. this error was because of that. and almighty android studio was giving me this irrelevant error. sorry to bother you and thank you for fast response 👍🏼 . if anyone faces random build error such as this. just check all the packages compileSdkVersion and targetSdkVersion in their build.gradle.

**Comment by mikehardy** [comment]
interesting - I have seen mixed kotlin/java projects give random errors around build settings similar to that. How frustrating!

**Comment by tolgaberk** [comment]
> > 我已经弄清楚是什么原因造成的。项目中有一个包 compileSdkVersion 为 23。这个错误就是因为这个。全能的 android studio 给了我这个无关紧要的错误。抱歉打扰您，感谢您的快速回复👍🏼 . 如果有人面临这样的随机构建错误。只需检查 build.gradle 中的所有包 compileSdkVersion 和 targetSdkVersion。
> 
> Hello, I have the same problem. My compilesdkversion and targetsdkversion are both 29. How do you solve it?

You need to check your project dependencies for difference in compileSdkVersion

**Comment by mikehardy** [comment]
It is not even possible to publish to the play store unless your targetSdkVersion is 30, so 29 is effectively unsupported throughout the ecosystem at this point.

That said, you may use this to have gradle roll through *all* depedencies and force all things to line up to your expectations:

https://github.com/invertase/react-native-firebase/blob/3d5d00d6b1ed7cf9e1afbe62f16b1c77e2bf7693/tests/android/build.gradle#L88-L98

**Comment by zxwGH** [comment]
> 除非您的 targetSdkVersion 为 30，否则甚至不可能发布到 Play 商店，因此此时整个生态系统实际上不支持 29。
> 
> 也就是说，您可以使用它来让 gradle 滚动_所有_依赖项并强制所有事情符合您的期望：
> 
> https://github.com/invertase/react-native-firebase/blob/3d5d00d6b1ed7cf9e1afbe62f16b1c77e2bf7693/tests/android/build.gradle#L88-L98

Oh, I see. Thank you
