### ISSUE TITLE
Get additionalUserInfo before signInWithCredntial

### ISSUE THREAD

**Issue by jsunwoo** [invertase/react-native-apple-authentication#203]
Hi,

I appreciate your work before asking my question.

As I know it, Apple only gives user info(such as email, name) for the first sign-in.

So I save it on my database when user made their first sign-in like below.

```javascript
async function onAppleButtonPress() {
    try {
      setLoading(true);

      const appleAuthRequestResponse = await appleAuth.performRequest({
        requestedOperation: appleAuth.Operation.LOGIN,
        requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
      });

      if (!appleAuthRequestResponse.identityToken) {
        throw 'Apple Sign-In failed - no identify token returned';
      }

      const credentialState = await appleAuth.getCredentialStateForUser(
        appleAuthRequestResponse.user,
      );

      const {identityToken, nonce} = appleAuthRequestResponse;
      const appleCredential = auth.AppleAuthProvider.credential(
        identityToken,
        nonce,
      );

      const result = await auth().signInWithCredential(appleCredential);

      if (result.additionalUserInfo.isNewUser) {
        const loadedEmail = appleAuthRequestResponse.email;

        const loadedFullName = `${
          appleAuthRequestResponse.fullName.familyName
        }${appleAuthRequestResponse.fullName.givenName}`;

        await firebase
          .database()
          .ref('users/' + result.user.uid)
          .set({
            email: loadedEmail,
            name: loadedFullName,
            uid: result.user.uid,
            numOfKeys: 1,
          });

        Alert.alert(
          'Message',
          `Welcome to scene`,
        );
      }

      navigation.resetRoot();
    } catch (error) {
      if (error.code === '1001') {
        console.log('Apple Auth Canceled');
      } else {
        console.log('Apple need to check Error');
      }
    } finally {
      setLoading(false);
    }
  }
```

But the issue I have is when the user canceled sign-in while sign-inning, Apple ID is already enrolled.

Then, I can't get user info also can't save it on my database.

So, if it is possible, I'd like to check whether it is a new user before sign-in.

If there is no user info and also it's a new user, I want to let the user ask to delete Apple ID first.

Is it possible to make it happen?

Any helps would be grateful.

**Comment by mikehardy** [comment]
Hmm - to make sure I understand:

- user chooses to use sign in with apple
- user starts process and authorizes the signin
- user cancels (somehow?) the signin after they granted the app access to the apple id but before they returned to the app?
- now the app has permission (and maybe a firebase auth user entry?), but no entry with information in your database

I think that's right? But I think it may not have an auth entry in your scenario as you specifically mention https://rnfirebase.io/reference/auth/additionaluserinfo#isNewUser if I understand correctly

So this is the case where isNewUser === true, but you have no user information

You can get the email address via decoding a token I think: https://github.com/invertase/react-native-apple-authentication/issues/160#issuecomment-730253423 (that was not iOS specific but maybe is generally available and you may use it in your case?)

If you have the email address you can get sign in methods that work for an email via https://rnfirebase.io/reference/auth#fetchSignInMethodsForEmail

That might be a way to do t?

**Comment by jsunwoo** [comment]
In 3rd step you mentioned, the user cancels sign-in like below.

https://user-images.githubusercontent.com/18051496/114144201-09749200-9950-11eb-8770-28b737a3f3a3.mp4

After the user cancels the sign-in, Apple Id is made already.

So appleAuthRequestResponse can't get information properly(bring null value).

> You can get the email address via decoding a token I think: #160 (comment) (that was not iOS specific but maybe is generally available and you may use it in your case?)

Yes, I tried this already, but this can bring user email not the user name.

To sum up,

1. New user tried to sign in by Apple
2. But canceled sign in by accident (like video)
3. tried to sign-in again

Can I get user info from this case?
Or I want to let users know to delete Apple ID in their device.

Thank you for your reply Mike

**Comment by mikehardy** [comment]
for step 2 in your comment (`But canceled sign in...`), as a user interface design it seems that the "window of opportunity" where this could happen would be minimized if the button was disabled during the operation I think?

That may be why I have not experienced this in my app

I do not believe there is any way to do anything but get the email via decode, then check firebase auth to see if there are any providers that can sign in with that email

**Comment by jsunwoo** [comment]
I see. Thank you for considering.
