### ISSUE TITLE
List of available scopes

### ISSUE THREAD

**Issue by zendevil** [invertase/react-native-apple-authentication#204]
In the example in the README,  we have the following:

```
  const appleAuthRequestResponse = await appleAuth.performRequest({
    requestedOperation: appleAuth.Operation.LOGIN,
    requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
  });
```
I'd like to know what are all the possible scopes available. Are these the only scopes available? Is there a way to get a unique id from apple as the scope and to also get a photo, like you get in Google Auth?

**Comment by mikehardy** [comment]
> I'd like to know what are all the possible scopes available. 

Those are the possible scopes

> Are these the only scopes available? 

No

> Is there a way to get a unique id from apple as the scope and to also get a photo, like you get in Google Auth?

No

This was a quick search for the answer https://duckduckgo.com/?t=canonical&q=sign+in+with+apple+scopes - the documentation is always available to consult
