### ISSUE TITLE
can't get user's details after authentication 

### ISSUE THREAD

**Issue by mercyAis** [invertase/react-native-apple-authentication#208]
import React,{Component} from 'react';
import { SafeAreaView, StyleSheet, View, Text } from 'react-native';
import appleAuth, { AppleButton } from '@invertase/react-native-apple-authentication'
export default class Applelogin extends React.Component{
 
 async onAppleButtonPress() {
     try {
      // make sign in request and return a response object containing authentication data
      const appleAuthRequestResponse = await appleAuth.performRequest({
        requestedOperation: appleAuth.Operation.LOGIN,
        requestedScopes: [
          appleAuth.Scope.EMAIL,
          appleAuth.Scope.FULL_NAME
        ],
      });
 
      const credentialState = await appleAuth.getCredentialStateForUser(appleAuthRequestResponse.user);      
        if (credentialState === appleAuth.State.AUTHORIZED) {}
            // successfully verified, handle sign in 
            if(appleAuthRequestResponse.email){
                let name = appleAuthRequestResponse.fullName
                let appleResponse= {
                  email: appleAuthRequestResponse.email,
                  first_name: name.givenName,
                  last_name: name.familyName
                }
                await AsyncStorage.setItem("appleSignin",JSON.stringify(appleResponse))
                var appl=await AsyncStorage.getItem("appleSignin")
                alert("AsyncStorage",appl)
            }else{
             console.log(appleAuthRequestResponse);
            }
      }catch(e){
        console.log(e);
      }  
  }
 
 
render(){
return(
    <SafeAreaView style={{flex:1}}>

        <AppleButton
             buttonStyle={AppleButton.Style.WHITE}
             buttonType={AppleButton.Type.SIGN_IN}
             style={styles.appleButton}
             onPress={this.onAppleButtonPress.bind(this)}
        />
    </SafeAreaView>
)}
}
 
const styles = StyleSheet.create({
  appleButton: {
    width: '80%',
    height: 45,
    alignSelf:'center',
    shadowColor: '#555',
    shadowOpacity: 0.5,
    shadowOffset: {
      width: 0,
      height: 3
    },
    marginBottom:10
  }
});

**Comment by mikehardy** [comment]
They only come back the first time, the issues list has piles of related issues. Did you search for them?

**Comment by mercyAis** [comment]
I have tried other solution but none of then worked for me. Is there any way you could look at my code and let me know what I'm doing wrong here? Thankyou!

**Comment by mikehardy** [comment]
No, sorry. This module works for everyone else so your problem is project-specific. I only have time to troubleshoot problems in the module itself. I suggest using the example app as a playground to test.

**Comment by KrisLau** [comment]
@mercyAis If it's after the first login, it will always return null as seen here in the [FAQ](https://github.com/invertase/react-native-apple-authentication#faqs).

**Comment by nikitph** [comment]
@mercyAis have you been able to get this to work?

**Comment by vatsmanu** [comment]
anyone able to resolve this? I too am facing similar issue, getting email id in response but not name or any other detail

**Comment by PerezCodeT** [comment]
I have the same problem 🫤

**Comment by juniordeleon013** [comment]
I have the same problem, guys.

**Comment by Romick2005** [comment]
You should start reading readme or at least first sentence at FAQs
