### ISSUE TITLE
Login not work in released Android app with the message "index.android.bundle"

### ISSUE THREAD

**Issue by LeeMoonki** [invertase/react-native-apple-authentication#209]
There is something wrong in apple login and I could not solve it... Here is the issue story. Before all, the following issue happen only in android.

First, I can login to apple in development environment. But **when I publish it into play store, the apple login failed with following message** (And also I could not login in AWS device farm using apk file. i.e, after release the login not work) :

```
{
  line: 1419,
  column: 349,
  sourceURL: "index.android.bundle"
}
```

I found several pages for the message and I apply a suggestion : [Unable to load script from assets index.android.bundle on windows](https://stackoverflow.com/questions/44446523/unable-to-load-script-from-assets-index-android-bundle-on-windows/53326616#53326616)

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>
</manifest>
```
But not work again.

The target sdk is **29**

If you give me any idea, it will be great help !

---
## environment
"@invertase/react-native-apple-authentication": "^2.1.0",
"react": "16.13.1",
"react-native": "0.63.4",

`android/build.gradle`
```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
        googlePlayServicesAuthVersion = "16.0.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        classpath("com.google.gms:google-services:4.1.0")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
```

**Comment by mikehardy** [comment]
Test release mode locally I think.
If you can verify this with the example app in release mode we may reopen and examine but I use this module (and have since the beginning) and it is fine in the play store, this will be a project-specific problem and won't result in a change to the module, so I'll close it
