### ISSUE TITLE
android build fails

### ISSUE THREAD

**Issue by aigen-admin** [invertase/react-native-apple-authentication#211]
After installing it, app met a problem to start on a android device but it's fine on IOS.

* react-native: 0.63.4
* @invertase/react-native-apple-authentication": 2.1.2,
* error message: Method addObserver must be called on the main thread.

When I just uninstall the module '@invertase/react-native-apple-authentication', it is working fine.

Any advice would be appreciated.

**Comment by traingethermarc** [comment]
Hi there.
a simple work-around would be to "exclude" `@invertase/react-native-apple-authentication` from android. Just add a `react-native.config.js `

```
module.exports = {
  dependencies: {
    '@invertase/react-native-apple-authentication': {
      platforms: {
        android: null
      }
    },
  }
};

```

**Comment by mikehardy** [comment]
I have no exclusion in my up to date (currently react-native 0.64.1 - so, okay I'm one patch back) project.
It compiles fine.
It runs fine.

If you can post a minimal reproducible example we can investigate, without it, I'll close as "can't reproduce" as I believe the module is working fine, though sure, there may be an incompatibility - we just need something that shows the problem

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by aigen-admin** [comment]
Thanks for the reply!

This error was occured once I add "@invertase/react-native-apple-authentication" and build my app on android devices.
so I post my package.json

`

{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.0",
    "@expo/webpack-config": "^0.12.44",
    "@invertase/react-native-apple-authentication": "^2.1.2",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-clipboard/clipboard": "^1.7.0",
    "@react-native-community/async-storage": "~1.11.0",
    "@react-native-community/cli": "^4.13.0",
    "@react-native-community/datetimepicker": "^3.0.4",
    "@react-native-community/hooks": "^2.6.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-firebase/app": "^11.5.0",
    "@react-native-firebase/auth": "^11.5.0",
    "@react-native-firebase/database": "^11.5.0",
    "@react-native-firebase/firestore": "^11.5.0",
    "@react-native-firebase/iid": "^11.5.0",
    "@react-native-firebase/messaging": "^11.5.0",
    "@react-native-firebase/storage": "^11.5.0",
    "@react-native-picker/picker": "^1.9.8",
    "@react-native-seoul/kakao-login": "^3.0.7",
    "@react-native-seoul/naver-login": "^2.1.0",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/native": "^5.7.2",
    "@react-navigation/stack": "^5.8.0",
    "axios": "^0.19.2",
    "expo": "~39.0.2",
    "expo-asset": "~8.1.7",
    "expo-constants": "^9.3.5",
    "expo-image-picker": "^8.4.0",
    "expo-notifications": "^0.7.2",
    "expo-permissions": "^9.3.0",
    "expo-status-bar": "~1.0.2",
    "expo-updates": "~0.3.2",
    "formik": "^2.2.0",
    "iconv-lite": "^0.6.2",
    "lodash.isequal": "^4.5.0",
    "moment": "^2.29.1",
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-geocode": "^0.2.2",
    "react-native": "~0.63.3",
    "react-native-btr": "^1.1.5",
    "react-native-calendars": "^1.403.0",
    "react-native-collapsible": "^1.6.0",
    "react-native-elements": "^3.0.0-alpha.1",
    "react-native-fast-image": "^8.3.4",
    "react-native-geolocation-service": "^5.2.0",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-image-crop-picker": "^0.36.0",
    "react-native-image-resizer": "^1.4.0",
    "react-native-image-viewing": "^0.2.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-loading-spinner-overlay": "^2.0.0",
    "react-native-maps": "^0.27.1",
    "react-native-modal": "^11.5.6",
    "react-native-modal-datetime-picker": "^9.1.0",
    "react-native-modalbox": "^1.7.1",
    "react-native-modalize": "^2.0.8",
    "react-native-paper": "^4.8.1",
    "react-native-permissions": "^3.0.1",
    "react-native-picker-select": "^8.0.2",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "~2.10.1",
    "react-native-send-intent": "^1.2.2",
    "react-native-splash-screen": "^3.2.0",
    "react-native-stars": "^1.2.2",
    "react-native-svg": "^12.1.0",
    "react-native-svg-charts": "^5.4.0",
    "react-native-toast-message": "^1.4.9",
    "react-native-unimodules": "~0.11.0",
    "react-native-web": "~0.13.12",
    "react-native-web-swiper": "^2.1.7",
    "react-native-webview": "^10.8.3",
    "react-native-wheel-picker-android": "^2.0.6",
    "react-navigation": "^4.4.2",
    "rn-fetch-blob": "^0.12.0",
    "run": "^1.4.0",
    "styled-components": "^5.1.1",
    "uuid": "^8.3.1",
    "yup": "^0.29.3"
  },
  "private": true,
  "name": "myapp"
}

`


Any kind advice would be apprecied.

Best Regards,
Kimpro

**Comment by mikehardy** [comment]
You did not follow my request here:

> If you can post a minimal reproducible example we can investigate,

So my statement is the result:

>  I'll close as "can't reproduce" as I believe the module is working fine

**Comment by Sydney-o9** [comment]
This may help others - https://github.com/invertase/react-native-apple-authentication/issues/277

**Comment by Ali-Rzaa** [comment]
> Hi there. a simple work-around would be to "exclude" `@invertase/react-native-apple-authentication` from android. Just add a `react-native.config.js `
> 
> ```
> module.exports = {
>   dependencies: {
>     '@invertase/react-native-apple-authentication': {
>       platforms: {
>         android: null
>       }
>     },
>   }
> };
> ```

 Worked for me, Thanks @marcibk  👍 :)
