### ISSUE TITLE
Android - only white screen

### ISSUE THREAD

**Issue by hrdyjan1** [invertase/react-native-apple-authentication#212]
**Problem**
At the moment I connected this library to the project, did the initial setup for android, the apple sign-in did not work properly.

**Steps**
In the code base, I added the function onAppleButtonPress.  In the function I used first function `appleAuthAndroid.configure` with exactly same `clientId` from my Apple Service ID. After this configuration, it will be called `appleAuthAndroid.signIn`. Then there will be a white page for a second. And finally the white page disappeared and the response is:

`[["nativeStackAndroid", []], ["userInfo", null], ["message", "E_SIGNIN_CANCELLED_ERROR"], ["code", "EUNSPECIFIED"], ["line", 2223], ["column", 45], ["sourceURL", "http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false"]]`

I also tried `redirectUri` with random characters, which means:

![image](https://user-images.githubusercontent.com/28002757/121299211-5c89a780-c8f5-11eb-8cf6-f0177d02d840.png)

I also tried `clientId` with random characters, which will be:

![image](https://user-images.githubusercontent.com/28002757/121299339-8cd14600-c8f5-11eb-925d-a3b34c21f4ff.png)

I accept any ideas.

**Comment by mikehardy** [comment]
Try the example app?

**Comment by hrdyjan1** [comment]
Example app has this response:
![image](https://user-images.githubusercontent.com/28002757/121463993-565a0080-c9b3-11eb-9918-0bc8c6c7e9a9.png)

**Comment by hrdyjan1** [comment]
Any other ideas, that might solve the problem?

**Comment by mikehardy** [comment]
Unsure, but  @dburdan implemented it in #136 - I would they are using it, perhaps they have ideas?

**Comment by dburdan** [comment]
@hrdyjan1 Does the return URL you setup with your Apple service ID exactly match the URL you provide to `appleAuthAndroid.configure`? I'd double-check the [readme troubleshooting](https://github.com/invertase/react-native-apple-authentication#case-1-1) to see if you missed a step.

**Comment by hrdyjan1** [comment]
It matches exactly the URL to the same I wrote to `appleAuthAndroid.configure`. Maybe I could try some URL, that works for others.

**Comment by hrdyjan1** [comment]
Finally, ClientId was wrong ❌. Now I have a chance to make it real on Android.

**Comment by hrdyjan1** [comment]
On android: 🟩
The final step makes the same mistake as I described above.
Now I am able to do the Apple sign-in. Do the verification. Press trust this browser. Do you want to continue ... press `continue`. And than:
```
{
	"nativeStackAndroid", [],
	"userInfo", null,
	"message", "E_SIGNIN_CANCELLED_ERROR",
	"code", "EUNSPECIFIED",
	"line", 2831,
	"column", 45,
	"sourceURL", "http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=cz.czc.app&modulesOnly=false&runModule=true"
}
```

On iOS: ⬛
There is a different error: `client_id mismatch`.
Where is the location to specify clientId on iOS?

**Comment by mikehardy** [comment]
Happy to take PRs to resolve issues / extend functionality / clarify documentation but as current maintainer the library currently handles my use cases, which means I do not have an interest in volunteering unpaid labor myself for use cases I don't need.

Happy to take those PRs and merge them though if anyone paying attention to this issue is motivated to develop them.

In the meantime closing this as stale
