### ISSUE TITLE
How to get accessToken and refreshToken?

### ISSUE THREAD

**Issue by CptMaumau** [invertase/react-native-apple-authentication#216]
Hi, I am able to sign in both on Android and iOS but the returned object doesn't include accessToken and refreshToken which I need to send to my backend. Any method to get them? Do I have to fetch them separately?

**Comment by Romick2005** [comment]
I think you need to send just **identityToken**

**Comment by colin11091** [comment]
I think direct request to get access token 
https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens
