### ISSUE TITLE
Is onCredentialRevoked correctly documented?

### ISSUE THREAD

**Issue by josegoval** [invertase/react-native-apple-authentication#217]
I was reading the [step three of ios setup](https://github.com/invertase/react-native-apple-authentication#3-event-listener), but does it work correctly?

I found [an article](https://rossbulat.medium.com/react-native-sign-in-with-apple-75733d3fbc3) that explains the next code:
```js
let authCredentialListener = null;
useEffect(() => {
  // this might be declared like const though, but won't change it to reference the article before
  authCredentialListener = appleAuth.onCredentialRevoked(async () => {
    //user credentials have been revoked. Sign out of account
  });
  return (() => {
   if (authCredentialListener.remove !== undefined) {
      authCredentialListener.remove();
    }
  })
}, []);
```

So, if in the step three the example only allows to revoke if the component App is unmount, in other words, app is closed, there's no way this might happen during execution time.

Is there something am understanding wrong? 

Thanks.

**Comment by Romick2005** [comment]
Yes you get it wrong. As if you read [step three of ios setup](https://github.com/invertase/react-native-apple-authentication#3-event-listener) documentation more carefully you will notice the line:
`// onCredentialRevoked returns a function that will remove the event listener. useEffect will call this function when the component unmounts`

So basically this like `authCredentialListener.remove();` just remove attached listener and have nothing with credentials revoke.

**Comment by josegoval** [comment]
> Yes you get it wrong. As if you read [step three of ios setup](https://github.com/invertase/react-native-apple-authentication#3-event-listener) documentation more carefully you will notice the line:
> `// onCredentialRevoked returns a function that will remove the event listener. useEffect will call this function when the component unmounts`
> 
> So basically this like `authCredentialListener.remove();` just remove attached listener and have nothing with credentials revoke.

So it's a wrapper!! Thank you so much! I already understood :)!

**Comment by Romick2005** [comment]
So you need to close this issue.
