### ISSUE TITLE
Deprecation warning - API 'variant.getJavaCompile()' is obsolete 

### ISSUE THREAD

**Issue by KrisLau** [invertase/react-native-apple-authentication#218]
### Issue
Getting this error when I build my application:
```
> Configure project :react-native-apple-authentication
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
```
Also not sure if this is my bad but the latest versions are not on NPM or Yarn? The latest on those are v2.0.0 but looking here on Github, the latest release seems to be v2.1.2.

### Environment info
react-native-apple-authentication: 
`v2.0.0`

react-native info: 
```
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
    Memory: 2.24 GB / 15.89 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: Not Found
  Languages:
    Java: 11.0.10
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.64.0 => 0.64.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mikehardy** [comment]
Hi there!

- warning, not error. Still useful, I'll keep this open for inspection, but it is not an error and that's an important distinction
- releases - 2.1.2 latest here https://github.com/invertase/react-native-apple-authentication/releases/tag/v2.1.2 + on the actual package name linked on our npm badge and described in the readme https://www.npmjs.com/package/@invertase/react-native-apple-authentication

Perhaps you saw this, which is at 2.0.0 but is not this package: https://www.npmjs.com/package/react-native-apple-authentication

**Comment by KrisLau** [comment]
My bad, looks like I mixed up the two packages! Once I swapped over to this one, the warning disappeared. Sorry for all the trouble!

**Comment by KrisLau** [comment]
My bad, looks like I mixed up the two packages! Once I swapped over to this one, the warning disappeared. Sorry for all the trouble!

**Comment by mikehardy** [comment]
Ah! Happy to see we don't have a deprecation to chase down, forward ports are usually  not hard but do eat time. Thanks for reporting back, Cheers

**Comment by KrisLau** [comment]
No problem and sorry for the confusion!
