### ISSUE TITLE
@invertase/react-native-apple-authentication  response not coming from appleAuth.performRequest to get token  forever loading

### ISSUE THREAD

**Issue by rasikaVillvay** [invertase/react-native-apple-authentication#219]
and after cancel login   i's return The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1001.) # @
![Screenshot 2021-07-09 at 11 30 42](https://user-images.githubusercontent.com/73985261/125030966-917e4b00-e0a9-11eb-8abd-3bd8b2f4db0e.png)

**Comment by mikehardy** [comment]
Please search issues lists in open source repositories before posting issues.
This is in fact pinned to the top of the list
Duplicate #193
