### ISSUE TITLE
appleAuth.getCredentialStateForUser giving error code =1000

### ISSUE THREAD

**Issue by fareszoghbi1** [invertase/react-native-apple-authentication#22]
please help when ever am calling this function this error pop up

      const credentialState = await appleAuth.getCredentialStateForUser(
        user
      );

**Comment by lucasferreiraestevam** [comment]
Open Xcode and add Sign In With Apple in ( Signing & Capabilities )

**Comment by Desintegrator** [comment]
getting same error 
`[Error: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)]`
"Sign In With Apple" enabled in Xcode

**Comment by QaysTrad** [comment]
I had the same issue, and I have solved it by adding the capability to Xcode

press on your project name in xcode, 

then press on the tab 'Signup & capabilities',

then press '+ Capability' and add 'sign up with apple'

**Comment by mikehardy** [comment]
This appears to be project setup error. Discussion can continue but it is not actionable for the module

**Comment by Natteke** [comment]
Tried everything, cleaned project, reinstalled all dependencies and same...
![image](https://user-images.githubusercontent.com/24633723/82805490-cb33c880-9e8c-11ea-9b00-b338591a5051.png)
![image](https://user-images.githubusercontent.com/24633723/82805543-d71f8a80-9e8c-11ea-981b-f5764ea9de65.png)
![image](https://user-images.githubusercontent.com/24633723/82805578-e3a3e300-9e8c-11ea-85c1-a40050d8c8ed.png)
```

    const appleAuthRequestResponse = await appleAuth.performRequest({
        requestedOperation: AppleAuthRequestOperation.LOGIN,
        requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
    });

    console.dir(appleAuthRequestResponse);

    const credentialState = await appleAuth.getCredentialStateForUser(appleAuthRequestResponse.user);
    
    console.dir(credentialState);
```
