### ISSUE TITLE
Apple login works Only Once

### ISSUE THREAD

**Issue by puneetkansal04** [invertase/react-native-apple-authentication#221]
I am using apple login. And it is working once on real device. I Think it is saving credentials and 2nd time it is not working. It is showing pop with message 

Do you want to Sign in to "App" your Apple ID is this.

And when I do signin then nothing happens. As it is showing choosing email on the first time but after first sign in it starts showing this popup and sign in stops working.

**Comment by endlesstech** [comment]
Yes, same. If log in again, I didn't get the name and email. All are null. I added name and email scopes.

**Comment by mikehardy** [comment]
Literally the first FAQ on the README
