### ISSUE TITLE
_reactNativeAppleAuthentication.appleAuthAndroid.configure is not a function

### ISSUE THREAD

**Issue by lieberscott** [invertase/react-native-apple-authentication#223]
Trying to use the package but getting the following error:
```
_reactNativeAppleAuthentication.appleAuthAndroid.configure is not a function. (In '_reactNativeAppleAuthentication.appleAuthAndroid.configure({
                clientId: "com.myapp.app",
                redirectUri: ""
              })', '_reactNativeAppleAuthentication.appleAuthAndroid.configure' is undefined)
```

Here is my function, it's copied from the example on the home page.
```
const doAppleLogin = async () => {
    try {
      // Initialize the module
      appleAuthAndroid.configure({
        clientId: "com.mypp.app",
        redirectUri: ""
      });

      const response = await appleAuthAndroid.signIn();
      if (response) {
        console.log(response)
      }
    } catch (error) {
      console.log("error");
    }
  };
```

I have the package installed and am importing it at the top.

Anyone know why this could be happening? I'm currently trying to use this in an Expo managed project - could this be why?

**Comment by mikehardy** [comment]
Don't use this package. https://docs.expo.io/versions/latest/sdk/apple-authentication/

**Comment by lieberscott** [comment]
@mikehardy Thanks for the really quick reply. I just uninstalled the Expo package you linked to and removed it from my project, but I'm still getting the error

**Comment by mikehardy** [comment]
@lieberscott I may have been unclear: do not use *this* package here, 'react-native-apple-authentication' if you are using Expo. Expo projects should use the expo package I linked above. Quoting my response above but more clear (I hope):

> Don't use `react-native-apple-authencation` for Expo. Use https://docs.expo.io/versions/latest/sdk/apple-authentication/

**Comment by lieberscott** [comment]
@mikehardy Gotcha now

**Comment by royalvirendra** [comment]
TypeError: undefined is not a function (near '..._reactNativeAppleAuthentication.appleAuthAndroid.configure...')

i am getting this error
