### ISSUE TITLE
How to get user details(name, email) in second time login using react-native-apple-authentication 

### ISSUE THREAD

**Issue by prakashmathpal** [invertase/react-native-apple-authentication#224]
Hi,
i am using react-native-apple-authentication library in my react native app for apple login. I am getting correct user details in first time login. When I am log out and then login with apple then I get user details null.

my code is for get user details
const appleAuthRequestResponse = await appleAuth.performRequest({
requestedOperation: appleAuth.Operation.LOGIN,
requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
});

**Comment by Romick2005** [comment]
Please read documentation before asking a question. https://github.com/invertase/react-native-apple-authentication#faqs
Short apple will return user full info only first time, so you need to store it. Next login requests will return user null, but there will be apple user id that will match with initial store user data that have user details.

**Comment by mikehardy** [comment]
@Romick2005 is exactly right - it's a bit weird (in my humble opinion) but that's the way the API works. Separately - thank you @Romick2005 for your help answering questions, I really appreciate it!
