### ISSUE TITLE
Create custom style for IOS

### ISSUE THREAD

**Issue by manastasiou** [invertase/react-native-apple-authentication#225]
According to [Apple documentation](https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/buttons/), user can define a custom button. Is there any way to achieve it?

**Comment by mikehardy** [comment]
Yes there is! You just stop using the buttons here, and you make a regular react-native button.
This has been covered before, searching before posting is always appreciated: https://github.com/invertase/react-native-apple-authentication/issues?q=+custom+button+
