### ISSUE TITLE
Did not get any profile data after auth once.

### ISSUE THREAD

**Issue by endlesstech** [invertase/react-native-apple-authentication#228]
I didn't get any login data after auth one. The username and email are null. I already added scopes [Email and FullName].

**Comment by Salakar** [comment]
https://github.com/invertase/react-native-apple-authentication#faqs - (1)

**Comment by ithustle** [comment]
@Salakar, after following this steps:

```
For testing purposes, to be receive these again, go to your device settings; Settings > Apple ID, iCloud, iTunes & App Store > Password & Security > Apps Using Your Apple ID, tap on your app and tap Stop Using Apple ID. You can now sign-in again and you'll receive the full name and `email.
```
still not returning fullname and email. Any other tips?
