### ISSUE TITLE
[QUESTION] How cancel (close) login dialog on android?

### ISSUE THREAD

**Issue by 890f2151c2be69c51db72017546d00fd** [invertase/react-native-apple-authentication#229]
Hi, 
When user click on social button login dialog appear. but what if user wants to cancel (close) it without entering credentials? is it possible somehow.  ANDROID ONLY

**Comment by mikehardy** [comment]
If you use this module, and you generate the login request, your application has relinquished control. You don't have the ability to cancel anything, I don't think. The user can just hit the back button I believe.

What did you try, and how did it go?

**Comment by 890f2151c2be69c51db72017546d00fd** [comment]
after testing Facebook and Google social login I absolutely forgot the button back :-D. it works of course.
