### ISSUE TITLE
FACEID or TOUCHID option

### ISSUE THREAD

**Issue by Breners** [invertase/react-native-apple-authentication#230]
How to disable the faceid and touchid option for the user when logging in?

**Comment by mikehardy** [comment]
As near as I can tell, you don't. I don't believe it is a valid option in the interface - stated differently, I see no API that allows configuration of which sign in types are provided

https://developer.apple.com/documentation/sign_in_with_apple/implementing_user_authentication_with_sign_in_with_apple

If I am wrong in any way - please post a comment with a pointer to the API where we may provide types of sign in that are acceptable, and we can reopen this for PRs that would hook to it
