### ISSUE TITLE
iOS - Please choose a different app identifier to set up related consent

### ISSUE THREAD

**Issue by tastafur** [invertase/react-native-apple-authentication#231]
**Problem**

I follow this guide to the point that in the active app identifier "Sign In with Apple" I mark "Group with an existing primary App ID" and add the corresponding "Primary App ID", I give it to save in the modal and then I give it to save on the certificates screen and it gives me this error and I don't understand why, I would appreciate any help

https://github.com/invertase/react-native-apple-authentication/blob/master/docs/INITIAL_SETUP.md

![Captura de pantalla 2021-08-20 a las 14 41 39](https://user-images.githubusercontent.com/11853181/130234652-38b83078-8ca4-4106-9e43-17bb80a85377.png)

**Comment by mikehardy** [comment]
I think this will be better on stackoverflow, I would definitely post there.
If you can show a reproducible code example here that demonstrates a bug in the module, that's what our issues list is for
User support on project-specific problems will always be best on stackoverflow where there's a much larger community available to respond

**Comment by tastafur** [comment]
@mikehardy I do not agree because what fails is the initial configuration guide for the module to work, which is written together with the module

**Comment by tastafur** [comment]
I made a mistake in a step and that's why it didn't work

**Comment by margrudniak** [comment]
i have the same problem, on which step are you talking about?

**Comment by jeongjuwon** [comment]
@margrudniak 

I have the same. I think that you are first experience at develop apple login. 

As a mentioned in https://github.com/invertase/react-native-apple-authentication/blob/main/docs/INITIAL_SETUP.md

> If you're enabling an App ID for the first time or for a new app. enable the App ID as primary.

That's the key!!
