### ISSUE TITLE
Stuck in apple login button in iOS , its not giving any error, nothing on console too

### ISSUE THREAD

**Issue by visheshagomic** [invertase/react-native-apple-authentication#232]
async function onAppleButtonPress(updateCredentialStateForUser) {
   console.warn('Beginning Apple Authentication');
 
   // start a login request
   try {
     const appleAuthRequestResponse = await appleAuth.performRequest({
       requestedOperation: appleAuth.Operation.LOGIN,
       requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
     });
 
     console.log('appleAuthRequestResponse', appleAuthRequestResponse);
 
     const {
       user: newUser,
       email,
       nonce,
       identityToken,
       realUserStatus /* etc */,
     } = appleAuthRequestResponse;
 
     user = newUser;
 
     fetchAndUpdateCredentialState(updateCredentialStateForUser).catch(error =>
       updateCredentialStateForUser(`Error: ${error.code}`),
     );
 
     if (identityToken) {
       // e.g. sign in with Firebase Auth using `nonce` & `identityToken`
       console.log(nonce, identityToken);
     } else {
       // no token - failed sign-in?
     }
 
     if (realUserStatus === appleAuth.UserStatus.LIKELY_REAL) {
       console.log("I'm a real person!");
     }
 
     console.warn(`Apple Authentication Completed, ${user}, ${email}`);
   } catch (error) {
     if (error.code === appleAuth.Error.CANCELED) {
       console.warn('User canceled Apple Sign in.');
     } else {
       console.error(error);
     }
   }
 }

**Comment by mikehardy** [comment]
Hi there - Probably #141 please examine that issue and confirm

**Comment by visheshagomic** [comment]
There is a bug I guess  in ios 14

**Comment by mikehardy** [comment]
ios 14 simulators at least. it is remarkable that it is still an issue 🤷

**Comment by mikehardy** [comment]
@karthikmandava7 you include no information on what you try, and thus cannot expect any answer that is truly useful. https://stackoverflow.com/help/how-to-ask

it works on ios 13 simulators. It works on iOS16 (currently in beta or RC status as I type this) simulators. It works on real devices.

It works nowhere else

**Comment by paprikka** [comment]
Thanks for the comments @mikehardy. Just wanted to confirm that Apple SSO run _via simulator_ works on iOS13 and 16, but **not** on iOS 14 and 15. Is that correct?


The scenario I have in mind is:

Deps:

```json
"@react-native-firebase/app": "^15.2.0",
"@react-native-firebase/auth": "^15.2.0",
"@invertase/react-native-apple-authentication": "^2.2.2",
"react-native": "0.68.2",
```

```Xcode Version 13.4.1 (13F100)```

1. follow the basic tutorial from here: https://rnfirebase.io/auth/social-auth#apple
2. sign in via simulator (iOS 14.x)


Expected result:
1. user is signed in

Actual result:
1. the UI gets stuck at the native password prompt (just the spinner shows up)

Everything works fine when running on a real device.

**Comment by salihgun** [comment]
trying to add firebase callback url to apple identifiers worked for me

![Screenshot 2023-01-17 at 00 51 35](https://user-images.githubusercontent.com/47421572/212771145-1ada615f-5201-4420-a662-12da56029041.png)

**Comment by AnisUrRahman1014** [comment]
I am a bit confused. Where exactly are we supposed to add those 

> trying to add firebase callback url to apple identifiers worked for me
> 
> ![Screenshot 2023-01-17 at 00 51 35](https://user-images.githubusercontent.com/47421572/212771145-1ada615f-5201-4420-a662-12da56029041.png)
