### ISSUE TITLE
Not getting User Object in Response Android Apple Login

### ISSUE THREAD

**Issue by BajajSaajan** [invertase/react-native-apple-authentication#237]
Hi Team! 

I'm using this plugin for apple login in android, iOS Platform. It's working well in iOS but while login in android platform I am not able to get user object in response once login is done or window is closed.

{"code": "XXXXX", "id_token": "XXX", "nonce": "XXX", "state": "XXX"}

Kindly help

**Comment by mikehardy** [comment]
Sorry, that's not a personal use case of mine and I'm not sure anyone else will answer, so I am mostly answering to say that any help you get will most likely come from your own efforts: do the typical react-native module debugging thing of reaching into node_modules, opening up the javascript files there around the method you have a problem with, and add console.log statements all over the place. Reach into the related kotlin files and add system output all over the place that logs all the arguments and all the return values then watch your console and `adb logcat` and figure it out. There's always a reason...or maybe the API just doesn't work the way you think it should?

**Comment by BajajSaajan** [comment]
Its work as expected but only thing which Ii want to discussed what should I do after this step in android case. any help would be appreciated. 

  // Open the browser window for user sign in
  const response = await appleAuthAndroid.signIn();

**Comment by Romick2005** [comment]
I think you should make a request to your backend to get/create your app specific user. Smth like this:
![image](https://user-images.githubusercontent.com/17779660/133567014-ff2c2f56-518b-43c4-a63d-ff00a1bb5e24.png)

**Comment by BajajSaajan** [comment]
@Romick2005 Thanks for the help. Its working for me before but problem is now I am not get user object earlier it was coming and write code something like this
  const response = await appleAuthAndroid.signIn();
    if (response) {
                    const code = response.code; 
                    const id_token = response.id_token; 
                    const user = response.user;          
     }
if you see here I am excepting user object but i am not able to get.. also if i want to convert id_token through JWT but I am not able to achieve.

**Comment by Romick2005** [comment]
Then I think you need to read readme. Apple give user object only one, next login you will get only apply id.

**Comment by BajajSaajan** [comment]
@Romick2005 I have read it everything but if I am first time user still I am not able to get it.

**Comment by BajajSaajan** [comment]
@Romick2005 I'm closing this issue. thanks for the time :)

**Comment by rajatgyl** [comment]
@mikehardy @BajajSaajan @Romick2005 

I am also facing this issue, I am able to get everything on Android except the user object, and I am aware that apple will only give user details on first login but I am not getting it on the first login too.

Please help.

**Comment by Romick2005** [comment]
If your app do login at least one time, then next login attempt will not return user data nor for iOS or Android. You need to unlink your app as in readme. Or you can create new apple account and check it. Please let us know the results.

**Comment by BajajSaajan** [comment]
> @mikehardy @BajajSaajan @Romick2005
> 
> I am also facing this issue, I am able to get everything on Android except the user object, and I am aware that apple will only give user details on first login but I am not getting it on the first login too.
> 
> Please help.

User Object will only comes in first time. You have to save details at your server side because let's suppose if user uninstall the application or install it again you will not get the details or let's suppose you login though apple with same account but different phone that time you will also not get.

**Comment by Romick2005** [comment]
@rajatgyl Any news?

**Comment by rajatgyl** [comment]
Hey @Romick2005, @BajajSaajan @mikehardy 
Thank you so much for you responses, I have now got the user response on Android too, previously I was doing it with the same Apple ID since there is no option on Android to stop the app from using the Apple ID therefore I had to create a new one and got the response.
Thanks again for responding. 🙂
