### ISSUE TITLE
Not getting User Object in Response Android Apple Login

### ISSUE THREAD

**Issue by rajatgyl** [invertase/react-native-apple-authentication#238]
Please refer to the below issue I want to reopen it as I did not get any solution to this anywhere.....

https://github.com/invertase/react-native-apple-authentication/issues/237#issue-997038891

https://github.com/invertase/react-native-apple-authentication/issues/237#issuecomment-920913023

**Comment by mikehardy** [comment]
I am traveling and have no time to solve your project problem, others seem to use it fine, sorry

**Comment by mikehardy** [comment]
dupe of #237, conversation continued there
