### ISSUE TITLE
Not getting an response after clicks on continue button.

### ISSUE THREAD

**Issue by Naveenhubino** [invertase/react-native-apple-authentication#247]
Am using this package for my web application after implementing, am getting the popup asking for username and password after to that am getting a message like 
**Do you want to continue using app with your Apple ID?**
on click to **continue or cancel** am not getting any response. 

Can anyone solved this issue share me how to achieve.

**Comment by mikehardy** [comment]
A guess: are you using an emulator, and that emulator is not an ios 13 emulator? If so, this is a known issue #141
If that is not the issue, then there is not enough information to guess further, sorry

**Comment by Naveenhubino** [comment]
@mikehardy Thnks for your response. In the above issue, i mentioned that am using this package for my web application in react. For more details am attaching screenshot too.

Code:
         ``
 <AppleSignin
                      authOptions={{
                        /** Client ID - eg: 'com.example.com' */
                        clientId: "client id",
                        redirectURI:
                          "some url",
                        usePopup: true,
                      }} // REQUIRED
                      uiType="dark"
                      className="apple-auth-btn"
                      noDefaultStyle={false}
                      buttonExtraChildren="Continue with Apple"
                      onSuccess={(response) =>
                        console.log("rrrrrrrrrrr", response)
                      } // default = undefined
                      onError={(error) => console.log("err", error)}
                      skipScript={false} 
                      iconProp={{ style: { marginTop: "10px" } }} 
                      render={(props) => (
                        <button
                          {...props}
                          style={{ border: "none", backgroundColor: "#423867" }}
                        >
                          <img src={apple} alt="apple" />
                        </button>
                      )}
                    />
``

![49142BED-A62D-4034-A85D-2BBD7A4CE9E3](https://user-images.githubusercontent.com/83056724/142973572-b75c5708-d51e-429c-a47c-687c9b2b80f9.JPG)

**Comment by mikehardy** [comment]
Oh, sorry, wasn't even aware this worked on web. You might be the first user there, all I can suggest is instrumenting the code in nide modules so you see all the API calls the module makes as well as any parameters and return values, standard troubleshooting really, sorry I don't have anything concrete to offer

**Comment by nandorojo** [comment]
I can try to debug this on web too.

**Comment by mikehardy** [comment]
@nandorojo that would be *most* welcome, I'm stretched pretty thin right now and don't have time to give it attention. Been collaborating with @criszz77 to shim fbsdk and google signin for API stability across web + ios/android but haven't tackled this at all yet. Very interested in it for: https://github.com/invertase/react-native-firebase-authentication-example

**Comment by nandorojo** [comment]
Sweet. I'm probably only going to use Apple as my social provider (we currently use phone auth).

We're using RNFB - it's amazing! I don't really know how OAuth works at all so I'll have to see if I can find any insights here. Will do my best and comment any findings here today.

**Comment by mikehardy** [comment]
@nandorojo I've seen you on a few other react-native-web repos trying to help bridge gaps here and there, I think a few of your answers and comments + PRs etc have helped me directly :-). You might really like the shims / craco-config stuff in that example template I referenced. It lets you do "RNFB" API calls on react-native-web, the example really does run out of the box. Just not with apple auth...yet :-)

**Comment by nandorojo** [comment]
@mikehardy glad to help wherever I can. this cross-platform stuff is hard...
