### ISSUE TITLE
AppleButton doesn't show on iOS 12.5.5

### ISSUE THREAD

**Issue by auliakbarh** [invertase/react-native-apple-authentication#248]
I have an iPhone 5s device with iOS 12.5.5, and the AppleButton is not showing in my React Native app. But on the simulator, it runs fine. Is there a minimal version of the iOS device to use Apple Sign-In?

**Comment by auliakbarh** [comment]
I've read the following issues:
https://github.com/invertase/react-native-apple-authentication/issues/138

Is there a way to implement Apple Sign-In on iOS version 12?

**Comment by Romick2005** [comment]
Have you checked [#166](https://github.com/invertase/react-native-apple-authentication/issues/166)? Can you please give it a try if it works for you?

**Comment by mikehardy** [comment]
Yeah, at that point, the iOS device is just a "web capable computer", so the Web way is the way to go.

**Comment by auliakbarh** [comment]
I've checked #166 and still doesn't work.

How can I implement the web way?

**Comment by Romick2005** [comment]
To check if this works, you need to install forked version until it is merged into the main module.
package.json
`
    "@invertase/react-native-apple-authentication": "git+https://github.com/Romick2005/react-native-apple-authentication.git",
`
And then read how to use [here](https://github.com/Romick2005/react-native-apple-authentication#1-initial-set-up-2)

**Comment by mikehardy** [comment]
@Romick2005 is right and as current slightly overburdened maintainer :wave: just want to apologize it hasn't gotten the attention it deserves yet. From the time I spent on examining it previously my take was "this looks like the right way to go..." so normally going off on a fork would be risky but in this case I expect that PR or something very close to it (based off the PR, just with minor fixups perhaps - typical PR process) will be merged, so shouldn't be as risky

**Comment by mikehardy** [comment]
Happy to take PRs to resolve issues / extend functionality / clarify documentation but as current maintainer the library currently handles my use cases, which means I do not have an interest in volunteering unpaid labor myself for use cases I don't need.

Happy to take those PRs and merge them though if anyone paying attention to this issue is motivated to develop them.

In the meantime closing this as stale
