### ISSUE TITLE
Not smooth

### ISSUE THREAD

**Issue by Justin9606** [invertase/react-native-apple-authentication#250]
I really do not how to explain it but I am showing the video in here. When you click the cancel or continue after that it is not closing modal smoothly, it is shaking. It is not working like a native apple auth.
Please help to fix this bug
Thanks

https://user-images.githubusercontent.com/54047658/145162138-cd28b94c-1dfd-41c8-90cd-711101e87502.MP4

**Comment by mikehardy** [comment]
Is this the example app? Without knowing *exactly* how it's displayed, I'm not sure how you're getting this, so there's no reliable basis to triage the problem and propose fixes from a single set of code. As far as I know that *is* a native auth. You've seen how the API works?  

We just say "hey Apple, could you do an auth?"

https://github.com/invertase/react-native-apple-authentication/blob/73a30393e4fc31659d2d084751e60dc5e660db37/ios/RNAppleAuthentication/RNAppleAuthModule.m#L90-L93

And....that's it. It's an Apple modal. It dismisses in Apple code. We just get a callback with a result, no UI code in the module involved other than showing the button.

**Comment by Justin9606** [comment]
> Is this the example app? Without knowing _exactly_ how it's displayed, I'm not sure how you're getting this, so there's no reliable basis to triage the problem and propose fixes from a single set of code. As far as I know that _is_ a native auth. You've seen how the API works?
> 
> We just say "hey Apple, could you do an auth?"
> 
> https://github.com/invertase/react-native-apple-authentication/blob/73a30393e4fc31659d2d084751e60dc5e660db37/ios/RNAppleAuthentication/RNAppleAuthModule.m#L90-L93
> 
> And....that's it. It's an Apple modal. It dismisses in Apple code. We just get a callback with a result, no UI code in the module involved other than showing the button.

**Comment by Justin9606** [comment]
> Is this the example app? Without knowing _exactly_ how it's displayed, I'm not sure how you're getting this, so there's no reliable basis to triage the problem and propose fixes from a single set of code. As far as I know that _is_ a native auth. You've seen how the API works?
> 
> We just say "hey Apple, could you do an auth?"
> 
> https://github.com/invertase/react-native-apple-authentication/blob/73a30393e4fc31659d2d084751e60dc5e660db37/ios/RNAppleAuthentication/RNAppleAuthModule.m#L90-L93
> 
> And....that's it. It's an Apple modal. It dismisses in Apple code. We just get a callback with a result, no UI code in the module involved other than showing the button.

@mikehardy 
Thanks for the response. I followed the firebase apple login guide and I used the @invertase/react-native-apple-authentication package.
Yes this is the example app.

**Comment by mikehardy** [comment]
That's just how it works as near as I can tell. I just checked it on my production app and the *system-provided modal* has two parts, a top part and a bottom part. As you authenticate, the bottom part disappears first (for some reason? No idea Apple...) then the second part slides down to take it's space, then the second part goes away.

You may examine the code I linked and play with it yourself, but as far as I can tell, we have zero control over this. Which means I have to close it as won't fix, since there's nothing actionable about it.

If you examine the code and I'm wrong, we can reopen and I'd be happy to merge a relevant PR

**Comment by MatthewPattell** [comment]
https://developer.apple.com/forums/thread/693381

**Comment by mikehardy** [comment]
Looks like it's fixed in most 15.4.1? From that link:

> Also had this issue on ≈15.1-15.3 devices, but after update on 15.4.1 that problem with animation of Apple Sign-in dialog has gone... looks like a bug with iOS.

I continue to be amazed at how slipshod the whole sign in with apple thing is, yet we are *forced* to do it. I still can't get it to work on any emulator except ios13 :shrug:
