### ISSUE TITLE
Can I get user name after second login

### ISSUE THREAD

**Issue by aigenn** [invertase/react-native-apple-authentication#252]
Step
Even if Apple only returns the full name and email on the first login, I can get email from the following code.
      const { identityToken, nonce } = appleAuthRequestResponse;
But the user name can't get anymore if user step back from other sign up process such as address and brithdate on our app.
I know this can be resolved if user tap 'Stop Using Apple ID'  on their smartphone but we can't push.

Can you please help to resolve this issue?

Thanks!

**Comment by mikehardy** [comment]
No you cannot get the user name again, this is by design. It's just how Apple does it.
Store the username.
