### ISSUE TITLE
Firebase still linked user's private email even though hide email is selected

### ISSUE THREAD

**Issue by KrisLau** [invertase/react-native-apple-authentication#255]
Not even sure where to start with this haha

```
  async function loginWithApple() {
    try {
      setAttemptedLoginMethod('apple');
      if (!appleAuth.isSupported) {
        Toast.show(
          'Sign in with Apple is only available on devices with iOS 13 or higher.',
        );
      } else {
        // Start the sign-in request
        const appleAuthRequestResponse = await appleAuth.performRequest({
          requestedOperation: appleAuth.Operation.LOGIN,
          requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
        });

        // Ensure Apple returned a user identityToken
        if (!appleAuthRequestResponse.identityToken) {
          Toast.show('No identity token returned');
        }

        // Create a Firebase credential from the response
        const {identityToken, nonce, fullName} = appleAuthRequestResponse;
        const appleCredential = auth.AppleAuthProvider.credential(
          identityToken,
          nonce,
        );

        // Sign in the user with the credential
        return auth().signInWithCredential(appleCredential);
      }
    } catch (error) {
      switch (error.code) {
        case appleAuth.Error.UNKNOWN:
          Toast.show('An unknown error occurred.');
          break;
        case appleAuth.Error.CANCELED:
          Toast.show('Apple sign in cancelled.');
          break;
        case appleAuth.Error.INVALID_RESPONSE:
          Toast.show('An invalid response was returned from the server.');
          break;
        case appleAuth.Error.FAILED:
          Toast.show('Apple sign in failed.');
          break;
        default:
          Toast.show(error.message);
          break;
      }
    }
  }
```

**Comment by mikehardy** [comment]
🤔 
Can you attest that you started with a completely clean slate? Stated more specifically, the user had removed the app completely from their icloud / sign in with apple app list and that the user profile on the firebase side was also removed? In the past I have definitely seen the apple private relay mails come through for apple users that hide their email, in my work projects, so at least in the semi-recent past I have evidence this is working. That means the repro steps need to be really really complete + specific

**Comment by KrisLau** [comment]
@mikehardy  So my steps were:

1. Focus on iOS simulator, go to toolbar and click on Devices > Erase All Content & Settings.
2. Restart the app.
3. Go to firebase console > delete user using three dot menu.
4. Go back to newly started app and login using apple login.
5. Click Hide Email.
6. Look on console and see the user's private email is revealed.

Im not sure about removing the app from icloud / apple app list. I tried to follow [this article](https://www.idownloadblog.com/2021/01/15/apps-using-apple-id-sign-in-with-apple/) but there were no apps under Password & Security

**Comment by KrisLau** [comment]
Oops nevermind I managed to delete the app from Password & Security but only from my Mac and then it worked!
