### ISSUE TITLE
send user info directly to your server after successful authentication

### ISSUE THREAD

**Issue by MarufSharifi** [invertase/react-native-apple-authentication#267]
How can I send user Info directly to my server after successful registration, without getting it and sending it by myself.
I mean apple send user info to a specific URL instead of giving me in response of sign in.

is that possible @mikehardy ?

**Comment by mikehardy** [comment]
You don't, I think. This is a native module and the callback is directly into your native app, so your native app regains control and has to do whatever it is you need it to do (like, posting to a server or similar)
