### ISSUE TITLE
[iOS] Issue on first open

### ISSUE THREAD

**Issue by RenatoSerra22** [invertase/react-native-apple-authentication#269]
react-native: 0.67.4
invertase/react-native-apple-authentication: 2.1.5

Platform: iOS real device only

I'm facing an issue where on first open trying to login i get `The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)`
If i force close the app and then open and try again it works fine.
The same thing started happening with my facebook login.

Any clues on what i could be doing wrong?

**Comment by RenatoSerra22** [comment]
it was a mistake on my part on how i setup dynamic links

**Comment by mikehardy** [comment]
Dynamic links are *hard* to get set up just truly perfectly. Really hard. Glad you found the issue!

**Comment by carlosoro** [comment]
@RenatoSerra22 Happy to know that you managed to solve your issue. Could you please elaborate on what the problem was with your dynamic links implementation? We are having the same problem and maybe your experience can help us

**Comment by nikonhub** [comment]
Also interested. We've started to randomly seeing these errors. Can't find anything to how to reproduce.
