### ISSUE TITLE
Can I translate the button text "Continue with Apple" to portuguese?

### ISSUE THREAD

**Issue by rabriol** [invertase/react-native-apple-authentication#27]
Hi,

I'm recently using your component to implement Sign In for Apple (Iphone).

But my app is in Portuguese (Brazil), is it possible to translate?

**Comment by Ehesp** [comment]
The text is generated via the Apple SDK, so not manually - however, if the device language is in a language, I believe the button text changes based on that.

**Comment by mikehardy** [comment]
It definitely does, my app is Spanish and English, and it translates to Spanish when the device is in Spanish

**Comment by rabriol** [comment]
Thank you @mikehardy and @Ehesp
