### ISSUE TITLE
not working on release build ios

### ISSUE THREAD

**Issue by UzairSoken** [invertase/react-native-apple-authentication#270]
Hi ,I have implemented apple login in iOS, It works perfectly on debugging mode but when  i generate a release build or upload it to test flight it doesn't work , I have also added  sign-in capabilities for release build,

Any recommended solution ?

**Comment by mikehardy** [comment]
Triple check your configs, no one else has this problem which implies it is project specific, in your project. I recognize that does not seem helpful but knowing everyone has this working tells you it's not a module problem so at least you know where to look

Thus is not an actionable issue, it will not result in any changes to this module so I'll close it but comments are always open of course
