### ISSUE TITLE
Error on Button Click

### ISSUE THREAD

**Issue by xwebart** [invertase/react-native-apple-authentication#274]
LOG (TypeError: undefined is not an object (evaluating '_reactNativeAppleAuthentication.AppleAuthRequestOperation.LOGIN')]

Can anyone help me with this please ?

**Comment by mikehardy** [comment]
You appear to have improperly installed the native module somehow. Javascript attempted to call it, and it didn't exist. Perhaps a missing pod install or something prior to testing.
This will *not* be actionable in this module, it's a project-specific integration error - as such it's not actionable here and I'll close it, with apologies. Carefully following the installation instructions should get you through

**Comment by xwebart** [comment]
Thank you i will try again

**Comment by xwebart** [comment]
Anyway, i addressed the issue, the app code that i bought was from code canyon, the developers added version 2.x but the code was old for version 1.xx so t he code was trying to use 

`requestedOperation: AppleAuthRequestOperation.LOGIN,` as version 1.x but the version installed used `requestedOperation: appleAuth.Operation.LOGIN,`

Anyway thank you for help!

**Comment by mikehardy** [comment]
Very interesting - never heard of code canyon but yeah - using code across major versions without forward porting will be an unhappy experience. Your error message is almost *always* a native module integration issue, I didn't think to check versions. Hopefully the changelog / release notes helped. Good luck on your project

**Comment by xwebart** [comment]
[](https://codecanyon.net/)

**Comment by xwebart** [comment]
https://codecanyon.net/
