### ISSUE TITLE
Apple Signin not providing email for login second time

### ISSUE THREAD

**Issue by rausn222** [invertase/react-native-apple-authentication#279]
While we use to login for the second time in iOS devices, it is not giving email to us, rather its giving dummy email.

**Comment by mikehardy** [comment]
You may find this interesting? #252

**Comment by mikehardy** [comment]
(basically, you get the identifying information from the user **one time only**, that is just the way Apple designed it, save it carefully...)

**Comment by mikehardy** [comment]
Did you read the linked issue?

Apparently you can get the email

```
I can get email from the following code.
const { identityToken, nonce } = appleAuthRequestResponse;
```

If you decode the token, the email is in there. But it's a lot easier to store it and then assume Apple gives you nothing, since they basically give you nothing by their design

**Comment by anatooly** [comment]
Apple designed is great. User first time register — fullName is return, then Delete Account, and register secondary, fullName not returned, because user not manual delete it's credentials app from Settings.

**Comment by Romick2005** [comment]
That is because you do not revoke apple login token on user remove.

**Comment by Romick2005** [comment]
You can check closed issues. Then you will find smth like: https://github.com/invertase/react-native-apple-authentication/issues/282
