### ISSUE TITLE
[!] There are multiple dependencies with different sources for `RNAppleAuthentication` in `Podfile`:

### ISSUE THREAD

**Issue by tapashm42** [invertase/react-native-apple-authentication#280]
[!] There are multiple dependencies with different sources for `RNAppleAuthentication` in `Podfile`:

- RNAppleAuthentication (from `../node_modules/@invertase/react-native-apple-authentication`)
- RNAppleAuthentication (from `../node_modules/@invertase/react-native-apple-authentication/RNAppleAuthentication.podspec`)

System configuration:

XCode Version: 13.4
Mac OS: Monterey
Chip: Apple M1 Pro

`pod 'RNAppleAuthentication', :path => '../node_modules/@invertase/react-native-apple-authentication/RNAppleAuthentication.podspec'
`

**Comment by mikehardy** [comment]
So, if you add a module in modern react-native, the module's podspec is automatically connected to the module via auto-linking

If you then also manually link the thing with a specific `pod` line, you'll have it twice

Remove the manual installation, and let auto-linking do it's thing, I tihnk

https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
