### ISSUE TITLE
Migration to new architecture

### ISSUE THREAD

**Issue by ParsaNasirimehr** [invertase/react-native-apple-authentication#285]
Hi. This is more of a question than a bug. My team is considering the effort it will take to move our project to the new architecture and i'm looking at our third party list, deciding how much work needs to be done for it to be migrated and if anyone is considering it or not.

**Comment by mikehardy** [comment]
Hi there! Hasn't been considered here at all yet - PRs are welcome though

**Comment by mikehardy** [comment]
One thing perhaps worth noting is that firebase-ios-sdk v9+ requires `use_frameworks!` in the Podfile, and currently new architecture does not support that at all, plus react-native 0.69+ (coming soon) also does not support it yet as an actual regression from 0.68 even with old architecture.

I believe firebase auth is one of the main use cases of sign in with apple (it is for invertase of course...) so there's lots to do even apart from turning on new architecture 

https://github.com/reactwg/react-native-releases/discussions/21#discussioncomment-2924919

**Comment by ParsaNasirimehr** [comment]
Thank you Mike. That does make sense.
