### ISSUE TITLE
IdentityToken can be null in some scenarios

### ISSUE THREAD

**Issue by brascene** [invertase/react-native-apple-authentication#29]
Hi, first of all thank you for this lib, and just one question, as I can see from your documentation and Apple Sign example this field **identityToken** can be null im some scenarios, so I wonder what are those scenarios (what causes them), and how should we handle them, by retrying the sign process?
Thanks in advance!

**Comment by mikehardy** [comment]
This would be better on StackOverflow - this module effectively works but is just a side project for all the maintainers, not much discussion will occur
