### ISSUE TITLE
There is no response on click of Sign in with Apple button.

### ISSUE THREAD

**Issue by karthikmandava7** [invertase/react-native-apple-authentication#291]
It seems suddenly stopped responding on click in real devices, any idea what is the issue, previously it was working fine and even we made live the feature. There is no error or warning. It's very difficult to identify the issue

**Comment by mikehardy** [comment]
Hi there! No one can help without the required information unfortunately: https://stackoverflow.com/help/how-to-ask

I just tested my work app where I have this integrated and it is working fine for me

You can imagine what you would need to troubleshoot, if someone brought you this problem - we can reopen if you can either reproduce this with the example app or provide the information
