### ISSUE TITLE
RN 0.69.1 compatibility issue

### ISSUE THREAD

**Issue by changhoi** [invertase/react-native-apple-authentication#294]
Hello,

I think it is not be compatible with the reactnative 0.69.1 version. The following build error appears:

```
e: /project/path/node_modules/@invertase/react-native-apple-authentication/android/src/main/java/com/RNAppleAuthentication/webview/SignInWebViewDialogFragment.kt: (105, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
```

```json
{
  ...
  "dependencies": {
    "@invertase/react-native-apple-authentication": "^2.2.1",
    "react": "18.0.0",
    "react-native": "0.69.1",
    ...
  }
  ...
}
```

**Comment by jamesxabregas** [comment]
Take a look at issue #277 where this has already been discussed. 

The solution is to add this line to your `android/build.gradle` file.

    dependencies {
        // ... 
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"   // <--- THIS
    }

**Comment by mikehardy** [comment]
Yes, duplicate #277
