### ISSUE TITLE
	Gradle sync failed: No variants found for ':invertase_react-native-apple-authentication'. Check build files to ensure at least one variant exists.

### ISSUE THREAD

**Issue by rStarNarayan** [invertase/react-native-apple-authentication#296]

**Comment by mikehardy** [comment]
No information that could be used for a reproduction is presented, so closing, sorry

Search: stackoverflow how to ask

Try running the example here on your mach, report results

**Comment by rastuch** [comment]
@mikehardy @rStarNarayan, same here, for some reason gradlew not recognizes a default versio of kotlin. Helps for me: 
`android/build.gradle in root react native project

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 22
        compileSdkVersion = 31
        targetSdkVersion = 31
        // Only using Android Support libraries
        androidXAnnotation = "1.1.0"
        androidXBrowser = "1.0.0"
        kotlinVersion = "1.5.31" //Add here but i think 1.7.0 will be better
    }
`
