### ISSUE TITLE
Manually setup

### ISSUE THREAD

**Issue by jsmile1994** [invertase/react-native-apple-authentication#3]
I'm currently using react-native 0.59.9. I setup this manually, but not success. Please support us with manual setup steps.
Thank you!

**Comment by mikehardy** [comment]
I think you'll need cocoapods. Then run react-native link and pod install and try it?

**Comment by thinnakrit** [comment]
Upgrade to react-native 0.60+ and update Xcode 11 for use Apple auth,
the Apple auth support iOS 13 only.

**Comment by pacozaa** [comment]
@jsmile1994 same here

**Comment by Salakar** [comment]
> Upgrade to react-native 0.60+ and update Xcode to version 11 for use Apple auth,
> the Apple auth support iOS 13 only.

@thinnakrit is correct here. This will only work on React Native 0.60+ due to the iOS 13 & Xcode 11 requirements. We'll get something added to the readme (cc @russellwheatley)

**Comment by mikehardy** [comment]
Ah! I had forgotten that ios13/xcode11 was react-native 0.60 only. It is a painful transition from 0.59 but definitely worth it, and I guess you can't avoid it if you want apple sign in

**Comment by Salakar** [comment]
This is now in the readme thanks to @russellwheatley 🎉 

Will close this issue now, thanks.
