### ISSUE TITLE
AppleButton SIGN_UP style cause invariant violation however appleauth.isSignUpButtonSupported is returning true

### ISSUE THREAD

**Issue by amitbravo** [invertase/react-native-apple-authentication#30]
1.  I am testing on iphone SE device with 13.3 
2. appleauth.isSignUpButtonSupported is returning true 
3. AppleButton SIGN_UP style cause invariant violation 
![IMG_1178](https://user-images.githubusercontent.com/16644357/72321360-b4ed5300-36c9-11ea-8b60-84625571e2bf.png)

**Comment by mikehardy** [comment]
I don't think that's a valid combination of type + style - the options are here: https://github.com/invertase/react-native-apple-authentication/blob/master/ios/RNAppleAuthentication/RNAppleAuthButtonViewManager.m

Question: option 1) is it missing as in Apple does not offer that button, or option 2) is it missing in that Apple offers it but if is not wired up here, or option 3) something else unknown?

Could you try hacking in node_modules in that file I linked above to alter for example white outline sign **in** to actually try to display white outline sign **up** from the Apple low-level APIs to see if the button shows? If it does then the answer is option 2 and a PR would fix it, if it does not then it is option 1 and maybe a PR that guards against impossible combinations is needed. If option 3 more research...

**Comment by mitsuharu** [comment]
I think that "SignUp and WhiteOutline" may be missing.

https://github.com/invertase/react-native-apple-authentication/blob/master/ios/RNAppleAuthentication/RNAppleAuthButtonViewManager.m#L121-L134

- I replace class name "RNAppleAuthButtonViewManagerWhiteSignUp" to "RNAppleAuthButtonViewManagerWhiteOutlineSignUp" at L123, L124, L125. "WhiteSignUp" is already defined in L66.

- I use iOS 13.2.2 simulator. This simulator somehow defines __IPHONE_OS_VERSION_MAX_ALLOWED to __IPHONE_13_0, then `#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_13_2` does not work. I remove "#if ...", add "if(@available(iOS 13.2, *))" into "- (UIView *)view".

**Comment by mikehardy** [comment]
Interesting - thanks for trying some things!

Regarding the 13.2 thing, the 'SignUp' style is 13.2 only, not 13.0 so it must be guarded for the higher API level, all the rest of the types and styles are 13.0+

https://developer.apple.com/documentation/authenticationservices/asauthorizationappleidbuttontype/asauthorizationappleidbuttontypesignup?language=objc

It does seem that there are 4 valid types and 3 valid styles, so for 13.0 there should be 3*3 (= 9) options and for 13.2 there should be 3 more

PRs happily accepted!

**Comment by mikehardy** [comment]
I believe this is resolved by #32 which I just merged, if not we can reopen
