### ISSUE TITLE
com.apple.AuthenticationServices.AuthorizationError error 1001.

### ISSUE THREAD

**Issue by nikitph** [invertase/react-native-apple-authentication#301]
This has just started showing up for us. Does anyone know why it has started happening? the scenario is that of a user using our app for first time and signing up using apple.

```javascript
  postAppleLogin: (params: SocialRequest) => any,
) => {
  try {
    setLoading(true);
    setLoadingMessage('Signing in with Apple');
    const appleAuthRequestResponse = await appleAuth.performRequest({
      requestedOperation: appleAuth.Operation.LOGIN,
      requestedScopes: [appleAuth.Scope.FULL_NAME, appleAuth.Scope.EMAIL],
    });

```

**Comment by mikehardy** [comment]
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by mikehardy** [comment]
It's vague, all apple error codes are vague and either not documented at all or poorly if at all. That's apple :shrug: 
My link on how to ask is *still* valid. You provide no details on what test you are actually running in what environment and what versions, but you want to discuss. It wastes time, yours and mine.

It's probably just a non-working simulator version. It only works on ios13 or ios16, ios14+15 do not work with apple authentication

But you don't specify at all what you are doing so :shrug:

**Comment by nikitph** [comment]
This is a production bug. I m simply trying to login on a real device. And the funny thing is this entire flow was working yesterday, We have had error reports on Sentry where its failing with 1001 on this line and its reproducing on a real device. So a minimal reproducible example is essentially to simply generate a request like the following and it fails with an 1001. If you want a MRE repo to understand and center on the problem, i have already done that for you. 

```
const appleAuthRequestResponse = await appleAuth.performRequest({
      requestedOperation: appleAuth.Operation.LOGIN,
      requestedScopes: [appleAuth.Scope.FULL_NAME, appleAuth.Scope.EMAIL],
    });
```

**Comment by nikitph** [comment]
If this much info is insufficient for you to make progress, don't sweat it for the time being. If this is a widespread problem, i m sure others will see this thread and update it accordingly. Then we can resolve it in a collaborative manner. Otherwise we will do some debugging on our end.

**Comment by mikehardy** [comment]
What version are you using?
What version of the iOS operating system is it happening on?
Are you able to reproduce with the example here in repo?

**Comment by topheroes** [comment]
Hello,

Same bug here. 
Tried version 2.1.2 and 2.2.2
iOS version 16.0.3 (20A392)
The example shows the same bug too.

**Comment by mikehardy** [comment]
@topheroes do you see this on a real device, if so which one, and do you see anything interesting in Console.app while this occurs?

**Comment by topheroes** [comment]
@mikehardy It's real device, IPhone 8
The logs are like follows:

```
2022-10-25 10:04:00.629574+0300 testing[1157:66125] [javascript] Beginning Apple Authentication
2022-10-25 10:04:08.648304+0300 testing[1157:66314] [siwa] Authorization failed: Error Domain=AKAuthenticationError Code=-7003 "(null)" UserInfo={AKClientBundleID=com.test.test}
2022-10-25 10:04:08.648605+0300 testing[1157:65877] RNAppleAuth -> didCompleteWithError
2022-10-25 10:04:08.649219+0300 testing[1157:65877] The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1001.)
2022-10-25 10:04:08.661206+0300 testing[1157:66125] [javascript] User canceled Apple Sign in.
```

**Comment by mikehardy** [comment]
7003 is very sparsely documented as a code, here's about the only thing I found https://developer.apple.com/forums/thread/700734 - so...maybe something to do with the provisioning profile and the UUID of the device itself, enrolled in the account? Or the profile for the app? I'm guessing wildly here, I have nothing to really back that up.

Note that the higher level "1001" error hides all these sub-errors underneath, so this may not be relevant to the original poster as they may have a different sub code.

**Comment by johndpope** [comment]
just double check 
`**Ensure that you pass the clientID as the web service ID, not the native app bundle. Since the project utilizes the service ID for authenticating web and android.**`

**Comment by FadiAboMsalam** [comment]
@nikitph  am facing same issue on certain devices on ios 16.5 any update on/ if you fixed it somehow 🤔

**Comment by nikitph** [comment]
@FadiAboMsalam It just stopped happening for us without any changes 🤷🏽‍♂️ i m really sorry i dont have any specific advice for you. We have a sentry observer to inform us immediately this starts happening again

**Comment by FondueBug** [comment]
Facing the same exact issue after updating to IOS 16.5, tried to update to  16.7 and its still the same issue, apple team also got this issue and they rejected the app.

**Comment by mikehardy** [comment]
With apologies, given the on/off nature of the error, and that it is not happening for everyone - as maintainer - this does not look actionable. The library is working or it would break for everyone, correct? So, this is something particular to projects and apple back-end.

Feel free to continue the discussion but unactionable issues are closed so that the open issues list is only actionable items

**Comment by RobertMrowiec** [comment]
I've got the same error, but it shows only if user CANCELLED the login - so I'm just skipping it. Maybe that's your case too?

**Comment by mzruiz** [comment]
I found [this Error](https://github.com/invertase/react-native-apple-authentication/blob/ac98c6243debe3fb2f5358cf5eafc7d186693829/lib/AppleAuthModule.js#L40) obj in the codebase that shows 1001 as CANCELLED.

**Comment by mikehardy** [comment]
@mzruiz PRs happily accepted
