### ISSUE TITLE
fullName always return null in the first login or any

### ISSUE THREAD

**Issue by windcloudit** [invertase/react-native-apple-authentication#304]
In my case, the _full name_ always return null on the first Sign In although I was do everything in the guide of this lib like as
```
 // Note: it appears putting FULL_NAME first is important, see issue #293
    requestedScopes: [appleAuth.Scope.FULL_NAME, appleAuth.Scope.EMAIL], 
```
or 
`Settings > Apple ID, iCloud, iTunes & App Store > Password & Security > Apps Using Your Apple ID, tap on your app and tap Stop Using Apple ID.`

But all of them do not help they always return null, my app was rejected by apple by can not get _full name_, Could you help me please, I have actually been stuck here for a long time. Thank you so much.

**Comment by YuddiPrase** [comment]
try it in real device dude

**Comment by mikehardy** [comment]
duplicate. reopened the main one.
If this is important to you - *dig in*, **do the work** to really troubleshoot, and bring it up with Apple as needed, please
