### ISSUE TITLE
missing feature: Make it possible to change apple login button text

### ISSUE THREAD

**Issue by adamSplendex** [invertase/react-native-apple-authentication#306]
Hey,

A simple but super important part of this little lib is missing, that is changing the Apple login text. We are developing apps for international clients and many of them wants their social login buttons translated to their language.

Now it is not possible with this lib, and sadly we already implemented the full auth login and such, but because of this we need to use another solution(which takes time) 

Expected behaviour: 

Apple Login Button's text should be changeable with a prop.

Thanks,

Adam
CTO @ Splendex.io

**Comment by mikehardy** [comment]
Hi there "CTO @Splendex" - those are system-generated dialogs, we simply ask the operating system to "start the auth process" and the system takes it from there

So they will show up in the current system language.

I use this module in a multi-language app *and the dialogs show in up in the system language*

There's no action here, it works, and if it does not work, then it's an Apple bug - you should file with them that they are missing a translation in to some language

**Comment by adamSplendex** [comment]
Thanks for the fast reply :) 

![image](https://user-images.githubusercontent.com/107463190/197528214-dbf0f6cf-e86d-4e2d-8abc-3a1a749fb2c3.png)


I meant for changing this text 

We made it work with another solution, like this: 

<img width="286" alt="image" src="https://user-images.githubusercontent.com/107463190/197529462-b31efcab-d6c4-48f0-8a8b-eec57304c3ba.png">


All in all it would be a nice to have thing here too.

Have a great week,

cheers

**Comment by mikehardy** [comment]
I addressed that:

> those are system-generated dialogs, we simply ask the operating system to "start the auth process" and the system takes it from there

Getting in to a competitive programming competition with Apple where we try to wrap all their functionality but with facility to internationalize text they have already internationalized at the system level seems like an extremely inefficient use of time.

Flow is: We ask system to start apple authentication flow, system starts showing system dialogs translated in system by Apple 

That's pretty efficient as Apple has lots of people working on their system and they handle the translation

I don't see a feature gap here

**Comment by adamSplendex** [comment]
All rightie, I get you, then something must have been weird with the language detection on the system layer because for us it was always English on all simulators and all devices (with nonenglish language as system lang).

Thank you for your time!

Kind regards,

Adam

**Comment by firstChairCoder** [comment]
> adamSplendex

Hi, @adamSplendex 
May I please ask how you were able to achieve it without just leaving it up to the system?
