### ISSUE TITLE
Had a problem with gradle-plugin

### ISSUE THREAD

**Issue by evaei** [invertase/react-native-apple-authentication#308]
I am using RN version 0.64 and this module version is 2.1.2 I also tried updated to latest version but it not working 
last Friday It was working fine.

![image](https://user-images.githubusercontent.com/45438331/200262359-4d77cb4a-cf24-43b7-ae73-fc56472daf33.png)

How can I solve this problem

**Comment by rawatnaresh** [comment]
adding this solution fixed it for me https://github.com/facebook/react-native/issues/35210#issuecomment-1304536693
```js
def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

allprojects {
    configurations.all {
        resolutionStrategy {
            // Remove this override in 0.66, as a proper fix is included in react-native itself.
            force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
        }
    }
```
