### ISSUE TITLE
Issue building in Android

### ISSUE THREAD

**Issue by rbjamaca** [invertase/react-native-apple-authentication#309]
I am using RN version 0.64 and the package version I'm using is the latest version (2.2.2) and I get this error message when building for android.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/58159983/200269495-9df2b058-c2fc-4f23-9fc2-1abdab5e2705.png">

**Comment by lylysunshinee** [comment]
same issue

**Comment by rawatnaresh** [comment]
please check https://github.com/facebook/react-native/issues/35210#issuecomment-1304536693
