### ISSUE TITLE
iOS: crash on first time login

### ISSUE THREAD

**Issue by doomsower** [invertase/react-native-apple-authentication#314]
User tried to login to our app for the first time, but the app has crashed after face verification step. On the second attempt he managed to log in. 

In sentry, the error shows up as
```
EXC_BAD_ACCESS

objectAtIndex: > onAppleIDButtonPress >
Attempted to dereference garbage pointer 0x10.
```

iPhone XS Max  // iOS 15.4.1 // `@invertase/react-native-apple-authentication@2.2.2` // `react-native@0.68.5`

**Comment by mikehardy** [comment]
Hi there! Not enough information to say anything conclusive, sorry
