### ISSUE TITLE
Need help, I can't find "ios" directory

### ISSUE THREAD

**Issue by Griiid** [invertase/react-native-apple-authentication#318]
Hello, I'm new to React Native, I read README, the installation part said:

```shell
yarn add @invertase/react-native-apple-authentication
(cd ios && pod install)
```

I have executed:

```shell
yarn create expo-app AppleSignIn
yarn add @invertase/react-native-apple-authentication
```

I didn't see `ios` directory, so I can't execute `cd ios && pod install`

What should I do?

**Comment by mikehardy** [comment]
If you are using expo, use their apple sign in module https://docs.expo.dev/versions/latest/sdk/apple-authentication/
