### ISSUE TITLE
Getting 'maven' not found with gradle 7.3.3

### ISSUE THREAD

**Issue by thevikas** [invertase/react-native-apple-authentication#320]
> A problem occurred evaluating project ':react-native-apple-authentication'.
> Plugin with id 'maven' not found.
> 

Please suggest.

**Comment by mikehardy** [comment]
Suggestion: https://search.brave.com/search?q=Plugin+with+id+%27maven%27+not+found

It is a project-specific problem, you'll have to resolve it
