### ISSUE TITLE
Two factor authentication flow in android

### ISSUE THREAD

**Issue by MVeitchW** [invertase/react-native-apple-authentication#321]
I am developing an App with react native for Android and IOS, when I use the library to sign in with apple on android I am redirect to a sign in window, the problem appears when i put my credentials, it asks me for two factor authentication as i was on IOS or a Mac.
I followed the given guide from here and apple.

![Screenshot 2023-04-27 153325](https://user-images.githubusercontent.com/131791061/234959370-08255501-5d93-4586-b30a-de075076b6e7.png)

**Comment by mikehardy** [comment]
Hi there - with apologies this isn't a use case of mine, I simply don't offer signin with apple on android devices.
If this is something you need to support you'll need to do the work to extend the library through your own development efforts. I'd be happy to take a PR that implemented it though
Cheers!
