### ISSUE TITLE
Support new RN architectures and Fabric render

### ISSUE THREAD

**Issue by xrustic2020** [invertase/react-native-apple-authentication#323]
Hello there!

We've switched to using the new react-native architecture with the new "[Fabric](https://reactnative.dev/docs/the-new-architecture/landing-page)" renderer, but it looks like @invertase/react-native-apple-authentication doesn't support it...

Whether the library is planned to be updated, taking into account the support of the new architecture react-native (Fabric)?

![Simulator Screenshot - iPhone 14 Plus - 2023-05-29 at 21 27 48](https://github.com/invertase/react-native-apple-authentication/assets/59570719/31808267-c00f-47ef-ad45-39be3933c583)

**Comment by affansk** [comment]
@xrustic2020  please wait for 0.72 release. i guess there they have added some mechanism where you can use new architecture with non migrated package

**Comment by hmhdworks** [comment]
Hi, any update on fabric support

**Comment by kyadalu1** [comment]
Try this https://www.youtube.com/watch?v=nZZodVliHi4

**Comment by efstathiosntonas** [comment]
@kyadalu1 this will be aired on 27th Sept. lol

**Comment by JoseLion** [comment]
I was able to render on fabric by adding the following config to my `react-native.config.js`:
```js
/**
 * @type import("@react-native-community/cli-types").Config
 */
module.exports = {
  project: {
    ios: {
      unstable_reactLegacyComponentNames: [
        "RNAppleAuthButtonViewManagerBlackContinue",
        "RNAppleAuthButtonViewManagerBlackSignIn",
        "RNAppleAuthButtonViewManagerBlackSignUp",
        "RNAppleAuthButtonViewManagerWhiteContinue",
        "RNAppleAuthButtonViewManagerWhiteSignIn",
        "RNAppleAuthButtonViewManagerWhiteSignUp",
        "RNAppleAuthButtonViewManagerWhiteOutlineContinue",
        "RNAppleAuthButtonViewManagerWhiteOutlineSignIn",
        "RNAppleAuthButtonViewManagerWhiteOutlineSignUp",
      ],
    },
  },
};
```

Even though `<AppleButton />` does render, the `onPress` event is not triggered upon pressing the button. Has anyone ever experienced this before? I'm not 100% sure this happens on fabric only, but I'm sure it is a problem with the `AppleButton` component because the AppleAuth workflow normally starts when I trigger the callback from a regular `Button` component.

> Registering legacy components will not be necessary in React Native v0.74.0 as the [Interop Layer is automatic](https://github.com/react-native-community/cli/blob/main/docs/projects.md#projectiosunstable_reactlegacycomponentnames).

### Environment
- **react-native:** 0.73.6
- **@invertase/react-native-apple-authentication:** ^2.3.0
- **Device:** iPhone 13 Pro (iOS 17.3.1)

**Comment by brentvatne** [comment]
@JoseLion - have you tried this since in 0.74? hopefully the issues you encountered in the interop layer should be resolved

**Comment by efstathiosntonas** [comment]
@mikehardy hi, now that 0.76 is out, are there any plans on adding Fabric support? thanks

**Comment by mikehardy** [comment]
Definitely will get this updated yes - Notifee was a higher priority repo for me and I just got that one done in time, this one is next and unfortunately just a little behind but I'll get it

**Comment by mikehardy** [comment]
I detected no issues when I worked through the rn76 upgrade process for the test app and checked it on iOS macOS and visionOS at least, in #357 

Is there something particular that isn't working for people? 

Note this is in fabric enabled / bridgeless enabled mode - if there is something I'm missing please provide as much detail as possible so I can reproduce, thank you

**Comment by mikehardy** [comment]
React native test app dies concurrent root by default and it works so...I think it's ready. If no one has a specific reason (sounds like no...) then I'll merge and do a PR to the rn directory and update the readme etc

**Comment by efstathiosntonas** [comment]
this should be updated too: https://reactnative.directory/?search=apple+authentication
