### ISSUE TITLE
 Task :app:processReleaseResources FAILED

### ISSUE THREAD

**Issue by Saliheen** [invertase/react-native-apple-authentication#324]
Task :invertase_react-native-apple-authentication:compileReleaseKotlin
w: D:\Projects\dev\help-app\node_modules\@invertase\react-native-apple-authentication\android\src\main\java\com\RNAppleAuthentication\webview\SignInWebViewClient.kt: (15, 21): 'constructor Handler()' is deprecated. Deprecated in Java
w: D:\Projects\dev\help-app\node_modules\@invertase\react-native-apple-authentication\android\src\main\java\com\RNAppleAuthentication\webview\SignInWebViewDialogFragment.kt: (42, 40): 'getParcelable(String?): T?' is deprecated. Deprecated in Java

**Comment by mikehardy** [comment]
You'll note that those are prefixed with 'w'
That is, they are warnings.
They should not fail your build. You likely have some other thing going on
Either way, not nearly enough information to go on - web search "stackoverflow mvce"
