### ISSUE TITLE
Specify clientId on iOS

### ISSUE THREAD

**Issue by Geoffrey63** [invertase/react-native-apple-authentication#331]
Hello, 
On `AndroidConfig`, we can indicate the clientId to use but not on iOS. 
I would like to use SignIn With Apple with a clientID that is different from my app bundle identifier. 
(The apple Service that i want to use has been created on another Apple team and user migration seems complicated) 
Is there a way to do so using this library? 
Thank you.

**Comment by mikehardy** [comment]
With apologies, I don't know. But the source is open, feel free to give it a try and if you get something working, PRs are happily accepted. Not a use case of mine as maintainer though, so I don't have free time to spend on it, sorry

**Comment by sidSingh90** [comment]
@Ge0ffreyS  Is this fixed , or anyone can specify how it was fixed ?
