### ISSUE TITLE
Make it possible to custom button text on Android

### ISSUE THREAD

**Issue by tonytony2020** [invertase/react-native-apple-authentication#332]
As @mikehardy mention in #306
> So they will show up in the current system language.

But it doesn't work on Android, is it possible to custom button text on Android?
I would like to submit a PR if you accept my custom button text change proposal.

**Comment by mikehardy** [comment]
If you need custom text in Android I recommend you use standard react components to create a button that meets apple human interface guidelines and use your standard text internationalization system to fill it with the required text

**Comment by mikehardy** [comment]
Fixed in #333 - thanks!
