### ISSUE TITLE
May I ask why the user's information is null

### ISSUE THREAD

**Issue by zhenzhongplus** [invertase/react-native-apple-authentication#339]
![WechatIMG653](https://github.com/invertase/react-native-apple-authentication/assets/96850336/24f22be8-a067-47ca-be1d-1a74463d8623)
![WechatIMG654](https://github.com/invertase/react-native-apple-authentication/assets/96850336/2e55879d-bc54-4b02-a6a4-1cdc7d8b1664)

**Comment by mikehardy** [comment]
FAQ 1
https://github.com/invertase/react-native-apple-authentication?tab=readme-ov-file#faqs
