### ISSUE TITLE
Credential State request returned with error: Error Domain=AKAuthenticationError Code=-7001 "(null)"

### ISSUE THREAD

**Issue by kevwang19** [invertase/react-native-apple-authentication#34]
Hey guys, I am using this library to handle apple sign in, and when I call 

```
const appleAuthRequestResponse = await appleAuth.performRequest({
        requestedOperation: AppleAuthRequestOperation.LOGIN,
        requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
      }).then(async(data)=>{
        console.log(data)
        const credentialState = await appleAuth.getCredentialStateForUser(data.user)
        console.log(credentialState)
        if (credentialState === AppleAuthCredentialState.AUTHORIZED) {
          
        }
      })
```

to get the authentication state of the current user, I get the above error in the title saying the credential state is null. However, when I log the data that is returned from performRequest, I can see all the info like token, email, name. 

In the data object that is returned, I notice that the key 'state' = null, but the key 'realUserStatus' = 1. When I log credentialState into the console when running on a real device, it shows up as 1. So does that mean this part - getCredentialStateForUser only works on real devices and not the simulator? And that in the simulator, it is returning the key 'state', while on an actual device, it is returning the key 'realUserStatus'?

Any help is appreciated!

**Comment by kevwang19** [comment]
Also on another note, there's the behavior on the simulator of repeatedly asking me about my email and name preferences upon apple signin, and re-entering my password, while on an actual device, it only asks for the device's passcode...? Is this the expected behavior?

**Comment by Desintegrator** [comment]
same issue

**Comment by mattdamon108** [comment]
I have an exactly same issue

**Comment by san-lee-ai** [comment]
got the same error but only in the simulator, working fine in the real iphone.

**Comment by mikehardy** [comment]
In general I would only trust the results from a real device, PRs to the docs would be appreciated if they don't specify this. That it works on simulator at all is almost coincidence (similar to cloud messaging / token features)
