### ISSUE TITLE
borderRadius style is not working on iOS.

### ISSUE THREAD

**Issue by pranay-jain-invimatic** [invertase/react-native-apple-authentication#345]
<AppleButton
                  buttonStyle={AppleButton.Style.BLACK}
                  buttonType={AppleButton.Type.CONTINUE}
                  style={{
                    width: width * 0.8, 
                    height: 45,
                    borderRadius: 22,
                    marginTop: 10,
                    borderWidth: StyleSheet.hairlineWidth
                  }}
                  textStyle={{
                    color: colors.white,
                    fontSize: 19,
                  }}
                  leftView={
                    <Image source={require('../../../assets/apple_icon.png')} style={{ width: 20, height: 20, marginRight: 10, marginTop: 3 }} />  
                  }
                  onPress={() => {
                  console.log("Button Tapped")
                  }}
                />

**Comment by mikehardy** [comment]
I don't believe that is passed through, I believe you want cornerRadius

https://github.com/invertase/react-native-apple-authentication/blob/13c71505e2e6f3101ba6059bdf36b03c05162298/ios/RNAppleAuthentication/RNAppleAuthButtonViewManager.m#L61

**Comment by pranay-jain-satech** [comment]
Thanks @mikehardy cornerRadius works
