### ISSUE TITLE
Currently not working under iOS 18

### ISSUE THREAD

**Issue by imp87** [invertase/react-native-apple-authentication#346]
Tried to use under iOS 18, but got an error says that its only working under iOS 13 or later.

Do you will add Support for iOS 18 in the future?

**Comment by mikehardy** [comment]
Please do not delete the issue template if you want to access support, in this repo or really any other repo, as it provides the information needed

Please include the exact steps to reproduce an error, if you have a question about an error

Please include the exact text of the error message produced by the last command step used to reproduce the error, if you have a question about an error

**Comment by ArthurCNR** [comment]
Same problem here.

iOS 17.2

`[Error: AppleAuth is not supported on the device. Currently Apple Authentication works on iOS devices running iOS 13 or later. Use 'AppleAuth.isSupported' to check device is supported before calling any of the module methods.]`

**Comment by rwitchell** [comment]
if you have come here having the same problem, and you are running your app in a simulator: guard your button with the `appleAuth.isSupported` function, like this:

```
<View className="flex-row justify-between">
        {appleAuth.isSupported ? (
          <AppleButton
            buttonStyle={AppleButton.Style.WHITE}
            buttonType={AppleButton.Type.SIGN_IN}
            style={{
              width: 160, // You must specify a width
              height: 45, // You must specify a height
            }}
            onPress={() => handleSignInWithApple()}
          />
        ) : null}
      </View>
```
