### ISSUE TITLE
flutter: Instance of 'AuthorizationResult' flutter: Sign in failed: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)

### ISSUE THREAD

**Issue by dsmailpuneet** [invertase/react-native-apple-authentication#35]
If a device or simulator logged in with apple credential then Sign in with Apple working proper, but if device or simulator not logged in with apple credential and try to login using Sign in with Apple then Alert comes  with two options Cancel and Setting ,if tapping on Setting option then it takes you a screen where you enter Apple Email and password and Behind it, It throws an Error  like below,
flutter: Sign in failed: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)

**Comment by Salakar** [comment]
This is a repository for React Native, not flutter.

**Comment by mikehardy** [comment]
At the same time - I have seen this in react-native. It succeeds the second time, if the first time involved the user not being setup at all and having to do the full apple account setup on the phone.

It's an underlying API issue, not the library's fault, I don't think.

**Comment by ZeerakHameem32** [comment]
@mikehardy Hi, +1. It works second time. Now the device is configured it's working fine. I'll check on some other device will update here.
