### ISSUE TITLE
CFBundleExecutable key error in AppAuthCore_privacy.bundle

### ISSUE THREAD

**Issue by neeleshyadav253** [invertase/react-native-apple-authentication#355]
Asset validation failed
Unexpected CFBundleExecutable Key. The bundle at 'Payload/projecy.app/AppAuthCore_Privacy.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue. (ID: 713ed61d-349c-4e8e-9fd1-8562709f486e)

**Comment by mikehardy** [comment]
I don't see based on information provided what thus has to do with this repository
