### ISSUE TITLE
Apple auth identity token null.

### ISSUE THREAD

**Issue by shreyaspapi** [invertase/react-native-apple-authentication#36]
I am using this function and getting null in identityToken. 

    onAppleButtonPress() {
        appleAuthRequestResponse = appleAuth.performRequest({
          requestedOperation: AppleAuthRequestOperation.LOGIN,
          requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
        });
      
        const { identityToken, nonce } = appleAuthRequestResponse;
      
        if (identityToken) {
            appleCredential = firebase.auth.AppleAuthProvider.credential(identityToken, nonce);
      
            userCredential = firebase.auth().signInWithCredential(appleCredential);
      
          console.log('Firebase authenticated via Apple, UID: ${userCredential.user.uid}');
        } else {
          // handle this - retry?
          console.log(appleAuthRequestResponse) // -> result = {"_40": 0, "_55": null, "_65": 0, "_72": null}
        }
      }

Can anyone help?

**Comment by mikehardy** [comment]
Hi there - you've already closed this but it is a classic: any time you see something like `{"_40": 0, "_55": null, "_65": 0, "_72": null}` you're looking directly at a Promise instead of resolving it and looking at the result. You need an await or next

**Comment by shreyaspapi** [comment]
Yes I closed the issue I solved it, await wasn't working but by cleaning the whole React native and building it again worked! With await of course. 

Thank you!
