### ISSUE TITLE
Crash after press button any times.

### ISSUE THREAD

**Issue by thinnakrit** [invertase/react-native-apple-authentication#4]
![Screen Shot 2562-12-06 at 09 20 27](https://user-images.githubusercontent.com/11704846/70291671-6fa64d80-180e-11ea-89ea-f02566064183.png)

- react-native 0.61.4
- react 16.9.0
- xcode 11
- ios 13

**Comment by thinnakrit** [comment]
Fix this!
don't use ```auth.performRequest``` on Class.
I move ```auth.performRequest``` to Saga for class function

**Comment by Salakar** [comment]
Closing as no longer an issue for you.

**Comment by MorgadoKnivet** [comment]
This problem is caused because a capabilities has not been added in XCode. See print.

![Screen Shot 2019-12-07 at 20 49 24](https://user-images.githubusercontent.com/34779500/70382402-54d0f780-193a-11ea-8bb0-d8e7eafb4627.png)
