### ISSUE TITLE
I need the change language text button from: en, to: pt-br

### ISSUE THREAD

**Issue by RenanAlvesBCC** [invertase/react-native-apple-authentication#40]
i need translate the english text button, how i do this? 
![Captura de Tela 2020-02-20 às 10 15 40 AM](https://user-images.githubusercontent.com/26460802/74937031-088a4500-53ca-11ea-9bbe-1d85dfe7f289.png)

**Comment by Ehesp** [comment]
I believe it automatically changes based on the device language.

**Comment by RenanAlvesBCC** [comment]
@Ehesp am try change my device language to test button text language, but don`t work.

**Comment by Pascip** [comment]
You have to change your development language. 
The first answer here describes how to do that: https://stackoverflow.com/questions/25871815/changing-the-development-language-in-xcode

**Comment by mikehardy** [comment]
It is done in the apple code based on the device language. Nothing this library can do or you need to do. Works for me in testing real and simulator devices. Post a video showing system language settings and a test screen with button showing wrong language from app restart to demo if possible
