### ISSUE TITLE
[DOCUMENTATION] Expand installation section to include pod directions

### ISSUE THREAD

**Issue by SeanMcP** [invertase/react-native-apple-authentication#42]
## Description

Add directions to run `pod install` after adding the dependency. The new [#installation section](https://github.com/invertase/react-native-apple-authentication#installation) would look something like this:

```md
## Installation

\```bash
yarn add @invertase/react-native-apple-authentication
\```

Once the dependency is added, install the pod from within your project's `ios` directory:

\```bash
cd ios/ && pod install
\```

You will not have to manually link this module as it supports React Native auto-linking.
```

## Reasoning

I was unable to get the library working, because I forgot to install the pods. Additionally, issues #13 and #19 could potentially have been avoided had the documentation included the pod instructions.

---

I am willing to make these changes, but I wanted to open this issue to give the maintainers an opportunity to comment and discuss.

**Comment by SeanMcP** [comment]
For the record, [I too had to add a line to the `Podfile`](https://github.com/invertase/react-native-apple-authentication/issues/19#issuecomment-576785212) to get the library working:

```rb
pod 'RNAppleAuthentication', :path => '../node_modules/@invertase/react-native-apple-authentication'
```

Perhaps this step should be included in the installation section as well.

**Comment by Stas-Buzunko** [comment]
+1 for adding pod install to installation guide

**Comment by mikehardy** [comment]
This (adding the non-auto-linking line) is not needed for most, certainly not for the example so we don't have a reproduction

Plus I think it's moot, react-native CLI for 0.62 runs a pod install

**Comment by SeanMcP** [comment]
> This ... is not needed for most

But it is needed for some, and not everyone can immediately update to the latest version of react-native.

**Comment by SeanMcP** [comment]
@mikehardy Closing this is a real bummer. Adding a line to the docs that will help some users seems so reasonable.

**Comment by mikehardy** [comment]
No PR I can recall, it's a volunteer project @SeanMcP - if wishes in issues lists were ponies I'd need a big ranch :-)

**Comment by SeanMcP** [comment]
> I am willing to make these changes, but I wanted to open this issue to give the maintainers an opportunity to comment and discuss.

@mikehardy The offer stands, but I don't want to take the time if it won't be accepted.

**Comment by mikehardy** [comment]
I'd like to better understand *why* this would be needed - ever - before accepting a PR, as it's my understanding (based on actual experience in work projects and this example) that it is not ever needed. That way the docs expansion would be of the form "if your project has XYZ characteristics you will need to manually link like so ...". If it's just in there as an undirected "try this" it'll just be the start of a pile of misc workarounds that build and make the doc unwieldy. Even then I would consider it but as an explicit "Miscellaneous Troubleshooting" section behind one of those github markdown `details` arrows that hides it by default

Which is to say, I want to help users, but keeping the docs clean is also a help and this is unexplained phenomena so shouldn't cause clutter without the effort to understand it

**Comment by SeanMcP** [comment]
I think doc cleanliness is a valuable consideration.

Truthfully I don't know the exact circumstances that required adding the dependency to the `Podfile` and a `pod install`. But we just pushed a release to the App Store with `react-native@0.61.5` last week that required both steps.

Is there any information I could provide that would help unravel the mystery?

**Comment by mikehardy** [comment]
A clean reproduction posted on github is by far the best away
