### ISSUE TITLE
Auth pop-up doesn't show

### ISSUE THREAD

**Issue by yarism** [invertase/react-native-apple-authentication#44]
When I try to open the auth pop-up nothing happens, I only get "com apple authenticationservices authorizationerror error 1000" which doesn't really say anything when searching for it... Any thoughts?

![Skärmavbild 2020-03-09 kl  15 28 19](https://user-images.githubusercontent.com/1689831/76222803-61a40680-621b-11ea-9665-6fae2b606bb9.png)

`  
    onAppleButtonPress = async () => {
    console.log(AppleAuthRequestOperation);
    console.log(appleAuth);
    console.log(AppleAuthRequestScope)
    // sign in request

    try {
      const responseObject = await appleAuth.performRequest({
        requestedOperation: AppleAuthRequestOperation.LOGIN,
        requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
      });
      
      console.log(responseObject);

      //authorization state request
      const credentialState = await appleAuth.getCredentialStateForUser(responseObject.user);
    
      if (credentialState === AppleAuthCredentialState.AUTHORIZED) {
        //user is authorized
      }
    }
    catch (error) {
      console.log(error)
    }

  }`

**Comment by mikehardy** [comment]
Nothing worth searching for? That error code is very popular here :-)
#9 
#22 

Lots of ideas in there as to what could be wrong

**Comment by yarism** [comment]
> Nothing worth searching for? That error code is very popular here :-)
> #9
> #22
> 
> Lots of ideas in there as to what could be wrong

Not really though since I have gone through those a few times and it doesn’t really say what is the issue in my setup.

**Comment by mikehardy** [comment]
We can't debug everyone's individual project problems, sorry. It's worth noting that everyone has resolved this eventually, or never had it happen, so it *must* be in your project setup. Perhaps try again with a clean throwaway iOS app configured on Apple's site, in combo with the example here.

**Comment by yarism** [comment]
I understand that but it’s also the only place I could find an answer on this or at least an idea.

**Comment by yurakruhlyk** [comment]
@yarism Hi, you found a solution? Because I get the same issue and my solution was added Capability Sign in with Apple for Debug. Try maybe it will help you.
