### ISSUE TITLE
Signin with Apple not working if the Apple ID is Mobile Number.

### ISSUE THREAD

**Issue by vevnkataSukumar** [invertase/react-native-apple-authentication#46]
Sign-in with Apple not working if the Apple ID is Mobile Number. If i try to use Sign-in with apple if Apple ID is Email id Working fine. But if apple ID is Mobile number Apple SignIn not working.

**Comment by mikehardy** [comment]
Hi there! Can you reproduce this with the native library calls? Have you checked the apple forums? We are not doing anything special between the two cases - there is no differentiation between them at all so I suspect this is an upstream issue not related to the module

**Comment by Pavaneshpratap** [comment]
requirement : email id is mandatory for the social login
PROBLEM : Apple id is phone number, so therefore in the response we get empty string in email {email:""},
so is there any possible way that apple login generate any random email id for those apple id with mobile number 
is it possible ?

**Comment by Romick2005** [comment]
The same is try for facebook login when profile does not have email. So you need to deal with this on your own.
