### ISSUE TITLE
"RNAppleAuthButtonViewManagerWhiteContinue" was not found in the UIManager

### ISSUE THREAD

**Issue by co2nut** [invertase/react-native-apple-authentication#48]
![image](https://user-images.githubusercontent.com/4594000/76612774-f11d2280-6557-11ea-80fc-fcdebbc4b630.png)

**Comment by mikehardy** [comment]
Please don't post images, text is highly preferred.
You skipped the template.

There is a related issue, not all of the combinations are supported but might be supportable, you may experiment with trivial changes inside node_modules to see how it goes #30 Y #23

**Comment by jeanffc** [comment]
Try:

```cd ios && pod install && cd ..```

**Comment by suraneti** [comment]
@co2nut  please follow my pull request to solve a problem #56.

**Comment by losikov** [comment]
* I have the same error on Android.
* On iPad with iOS 12.4.5 the Apple button is not seen, and there's no such issue. I don't have other devices to check.

[Expo implementation](https://docs.expo.io/versions/latest/sdk/apple-authentication/) has **AppleAuthentication.isAvailableAsync()**, and it allows explicitly know if it is supported or not to show the button.

Platform.OS === 'ios' can be just a temporary workaround, but not sure it works 100%.

**Comment by suraneti** [comment]
@losikov You have to update your iPad to iOS 13.0 or later to using Apple Sign-in.

**Comment by losikov** [comment]
> @losikov You have to update your iPad to iOS 13.0 or later to using Apple Sign-in.

I'm aware that it is supported on iOS 13 and alter, and I'm testing using it. I do expect it still works (not crash, and hide the button) on devices where it is not supported. As I said, Platform.OS === 'ios' is a workaround to fix Android crash, but it doesn't cover iOS family.

I specially run on old iPad to check what happens.

**Comment by suraneti** [comment]
@losikov my solution is checking `Platform.OS === 'ios' && Platform.Version >= '13.0'` to display sign in button.

**Comment by mikehardy** [comment]
Am I missing something? https://github.com/invertase/react-native-apple-authentication/blob/master/docs/interfaces/_lib_index_d_.rnappleauth.module.md#issupported

**Comment by ahmadzahidglixen** [comment]
Has anyone found a solution for this?

**Comment by suraneti** [comment]
@ahmadzahidglixen what is your Xcode version?

**Comment by ahmadzahidglixen** [comment]
@suraneti Version 11.4

**Comment by suraneti** [comment]
@ahmadzahidglixen try this method
1. Clean project (Product -> Clean), removed derived data, react-native --reset-cache, removed node_modules.
2. Re-install package, pod deintegrate, and pod install.

Additional question: does an error occur on Android?

**Comment by ahmadzahidglixen** [comment]
@suraneti I've tried:
uninstalling the package
installing it.
removing Pods & reinstalling them.

but it's no use.
I'm testing this on Simulator.

For android, no I'm not gonna use it on Android.

**Comment by suraneti** [comment]
@ahmadzahidglixen what is your React Native version and did you follow this [setup guide](https://github.com/invertase/react-native-apple-authentication/blob/master/docs/INITIAL_SETUP.md).

**Comment by ahmadzahidglixen** [comment]
@suraneti react native's version: 0.61.2.
Yes I followed this guide.

**Comment by suraneti** [comment]
@ahmadzahidglixen try this https://github.com/invertase/react-native-apple-authentication/issues/23#issuecomment-575120292.

**Comment by ahmadzahidglixen** [comment]
@suraneti tried these steps.
Still the same error:
Invariant Violation: requireNativeComponent: "RNAppleAuthButtonViewManagerBlackContinue" was not found in the UIManager.

**Comment by mikehardy** [comment]
> There is a related issue, not all of the combinations are supported but might be supportable, you may experiment with trivial changes inside node_modules to see how it goes #30 Y #23

**Comment by ahmadzahidglixen** [comment]
@mikehardy Which changes inside the node_modules?
Are you talking about changes inside RNAppleAuthButtonViewManager.m?

**Comment by ahmadzahidglixen** [comment]
Is this because of simulator? or iOS version 13.4?

**Comment by suraneti** [comment]
@ahmadzahidglixen I testing iOS 13.4 on a simulator, it works fine.

**Comment by mikehardy** [comment]
With no reproduction or logs there is not much we can do, but I will happily reopen this with actionable information, and of course conversation can always continue

Just want to set the tone in this repo for an issues list that is in control and doesn't have non-actionable stuff

**Comment by rishiankush** [comment]
I did everything and followed `npx react-native-clean-project clean-project-auto && yarn && cd ios && pod install` but did not work out for me
![simulator_screenshot_21BFF86E-4A80-4EC3-B3A0-DAF76BE06FA4](https://user-images.githubusercontent.com/25289937/125754170-09e7c0ac-5faa-4366-a6c0-c30ab114a0d6.png)

**Comment by erulabs** [comment]
@rishiankush I've got the same issue - feel like I've tried wiping and re-installing in every possible way. If I find a cure I'll post - did you ever solve this?

**Comment by Alxmerino** [comment]
I've done the same, uninstall and install everything and it doesn't work for me. I'm also using the simulator and can't run on the actual device because of missing Team Certs.

**Comment by mlaythe** [comment]
uninstalling everything + clearing cache didn't help me, but simply running `npx expo run:ios` fixed my issue

I was only running `expo start` before and then selecting the simulator, but guessing `expo run:ios` does the linking/building? 🤷 and the simulator is running iOS 16.4 so you don't need iOS 13 for it to work for the simulator
