### ISSUE TITLE
An email and fullName return null on some devices on same iCloud account.

### ISSUE THREAD

**Issue by suraneti** [invertase/react-native-apple-authentication#57]
I have tested on my devices that syncing the same iCloud and face the problem that the seconds' devices cannot get an email and full name when the first device signed in.

Scenario:
 1. Sign in on iOS simulator at first (worked).
 2. Sign in on iPhone 7 device (worked).
 3. Sign in on iPhone 11 Pro device (not worked, get null data).

**Comment by mikehardy** [comment]
You must in your back-end code save the result of the first sign in. The underlying APIs are documented to only ever return the personal identifying information the first time.

**Comment by efstathiosntonas** [comment]
@mikehardy sorry for bumping an old & closed issue, if i store the first time user info on backend, what is the unique "key" that can be retrieved later if user decides to log out and log in again? Does apple provide us some unique identifier per user?

**Comment by mikehardy** [comment]
I believe you get a unique identifier though I haven't tried it - my personal project integration is with firebase and they just handle it. It is my understanding from other issues here that the token Apple returns actually has the email every time if you unpack it / inspect it? If you scan the issues/PRs there *should* be mention of it though I don't have a pointer to that right at hand
