### ISSUE TITLE
'React/RCTUtils.h' file not found in RNAppleAuthModule.m

### ISSUE THREAD

**Issue by TuJobs** [invertase/react-native-apple-authentication#58]
i run pod install , laster in xcode errors appear 'React/RCTUtils.h' file not found in RNAppleAuthModule.m
react-native: 0.60.4
Xcode:11.3.1

**Comment by TuJobs** [comment]
![Screen Shot 2020-03-31 at 5 19 16 PM](https://user-images.githubusercontent.com/28697810/78015588-cb738400-7373-11ea-941e-b0a2bbb1564c.png)

**Comment by mikehardy** [comment]
did you run pod install?

**Comment by TuJobs** [comment]
Yes. i clean node_module, clean pod, clean cache. i run yarn install and pod install. auto linking not working with me . i must add pod:
 'RNAppleAuthentication', :path => '../node_modules/@invertase/react-native-apple-authentication'
to podfile

**Comment by mikehardy** [comment]
How did it go when you ran the example included here?

**Comment by TuJobs** [comment]
+) i yarn add @invertase/react-native-apple-authentication
 +) i must add to podfile:
'RNAppleAuthentication', :path => '../node_modules/@invertase/react-native-apple-authentication
+)  i clean node_module, clean pod, clean cache. 
+) i run yarn install and pod install
=> This is all I do

**Comment by mikehardy** [comment]
I think this may be fixed by #50 - if you can reproduce this still we will reopen

Just want to set the tone in this repo for an issues list that is in control and doesn't have non-actionable stuff
