### ISSUE TITLE
Automatic merge when existing account with email&password provider on Firebase

### ISSUE THREAD

**Issue by TheJonk** [invertase/react-native-apple-authentication#64]
Hi! First of all I'm aware that this question probably should be targeted towards firebase auth module, but I'm posting this here to see if anyone else have stumbled upon this issue.

When I perform this code snippet and choosing "Share my Email" and I already have an existing “email & password-provider” on Firebase with the same email as the one I have on my Apple ID, the providers automatically merge. 

```
const appleAuthRequestResponse = await appleAuth.performRequest({
				requestedOperation: AppleAuthRequestOperation.LOGIN,
				requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
})
const { user, email, nonce, identityToken } = appleAuthRequestResponse
const appleCredential = firebase.auth.AppleAuthProvider.credential(identityToken, nonce)
const userCredential = await firebase.auth().signInWithCredential(appleCredential)
```

If I instead were to use for example Facebook sign in through react-native-fbsdk to sign in with these lines: 

```
const credential = firebase.auth.FacebookAuthProvider.credential(accessToken)
firebase.auth().signInWithCredential(credential)
```

the auth module correctly throws an error ‘auth/account-exists-with-different-credentials’ since it detects that an account already occupies the email-address on firebase.

The issue is that I cannot stop the merge from happening during the sign in flow, unless I manually prevent it by looking up the authenticated Apple email's firebase login providers in-between the request and the sign-in. 

I’d wish to be able to handle an error such as auth/account-exists-with-different-credentials even when signing in with Apple, but unfortunately nothing gets thrown.

Is this behaviour intended?

Edit:
react-native-firebase version 5.6.0
Firebase/Auth version 6.15.0

Kind Regards, Jonathan

**Comment by mikehardy** [comment]
That's all firebase IMHO - I have seen the same. I do what you mention and toss a dialog explaining the privacy implications in between apple sign-in and sending it to firebase for that reason

**Comment by TheJonk** [comment]
> That's all firebase IMHO - I have seen the same. I do what you mention and toss a dialog explaining the privacy implications in between apple sign-in and sending it to firebase for that reason

Do you think this is a bug or intended? I'm debating whether I should post a bug issue or just make a feature request.

**Comment by mikehardy** [comment]
I wouldn't guess intentions, I have no idea - I do know they (the firebase team) has been very responsive to me in the past when I've posted things, so it can't hurt to post and ask on their github repos

**Comment by TheJonk** [comment]
> I wouldn't guess intentions, I have no idea - I do know they (the firebase team) has been very responsive to me in the past when I've posted things, so it can't hurt to post and ask on their github repos

Thank you for your replies. I will post the question to the firebase team :)
