### ISSUE TITLE
What is difference between isSupported and isSignUpButtonSupported?

### ISSUE THREAD

**Issue by sahil290791** [invertase/react-native-apple-authentication#66]
I am unable to find any documentation on these methods.

As per my understanding isSupported is for using any Module method and isSignUpButtonSupported is to check if AppleButton can be rendered.

Please close this issue if my understanding is correct.

**Comment by yuzhakovvv** [comment]
@mikehardy according to Apple documentation the only difference between "Continue ...", "Sign In ..." and "Sign Up ..." is in button title. So why "isSignUpButtonSupported" and "isSupported" depend on different iOS versions?

Source: https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/buttons/

**Comment by mikehardy** [comment]
@yuzhakovvv look very very very carefully at the SDK values on top right of the dev pages

https://developer.apple.com/documentation/authenticationservices/asauthorizationappleidbutton/buttontype/signup

They introduced signup in 13.2+. So in general sign in works with 13.0+, but signup is 13.2+ only.

**Comment by yuzhakovvv** [comment]
Ok, thanks! But how these restrictions affect methods in this package?

**Comment by mikehardy** [comment]
Have you tried it? Try then ask, in general, for efficiency
They don't, with the exception of that button style.
