### ISSUE TITLE
IOS 13.4.1

### ISSUE THREAD

**Issue by pyeonjaesik** [invertase/react-native-apple-authentication#67]
In IOS 13.4.1
login failed.
please fix this error
https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple113/v4/8c/20/4e/8c204eaf-e9f5-42d0-20c0-cc491d1c17aa/attachment-3582241554334320164Screenshot-0415-114049.png?accessKey=1587279411_4816623304056872455_WPRXqJzJgYQjngq%2FjkM4O1vbvnXXSIa2mHQDxM%2FzZFYFlSTB5THLpyzRqOAQVlp7M9Qk0NagPBv5%2BVpiSM85BlpAnckBiksQ59161nNivkMuOUsIYvwXDxtaa2EorTUVSur%2FgmPS4vQso4mUbm0kVMhFJtrBXGjHKLTweCXA8xIlm3ukhxsLZQD7fzShz0RdnZ%2FePsf27G7%2FTzsEhQcEuQ%3D%3D

**Comment by mikehardy** [comment]
That sounds really demanding and includes none of the actual details (please post them as text, not links to images)
