### ISSUE TITLE
Use of undeclared identifier 'ASAuthorizationAppleIDButtonTypeSignUp'; did you mean 'ASAuthorizationAppleIDButtonTypeSignIn'?

### ISSUE THREAD

**Issue by doublelam** [invertase/react-native-apple-authentication#68]
After yarn add @invertase/react-native-apple-authentication and cd ios, pod install dependencies, encountered this issue when building on Xcode
![image](https://user-images.githubusercontent.com/12025501/79945524-7f15f280-84a0-11ea-9df5-66067805ed44.png)

**Comment by doublelam** [comment]
after upgrading Xcode, its fixed

**Comment by joelkree** [comment]
I have the same problem.
Xcode v11.0 and Mac OS Mojave 10.14.6. Is there another option other than upgrade for Catalina and update Xcode?

**Comment by mikehardy** [comment]
Developing for iOS implies having up to date Xcode I think, as a basic assumption. I'm not aware of any alternatives.

**Comment by joelkree** [comment]
Maybe Mac OS Catalina would be something worth mentioning in the prerequisites? I updated my mac to Catalina to update Xcode and it's working fine now on Xcode 11.5. 11.0 is the max for Xcode on Mojave

**Comment by mikehardy** [comment]
Sounds about right - PRs happily accepted :pray: github makes it trivial for docs updates, it's all in the browser auto-forks etc

**Comment by qwertzguy** [comment]
I did the suggestion from Xcode and replaced the occurrences by `ASAuthorizationAppleIDButtonTypeSignIn` and it worked

**Comment by mikehardy** [comment]
@qwertzguy if you're not running current Xcode, you will have lots of related troubles. Rather than change the working code here I urge you to upgrade Xcode to current (12.2 as of quite recently) so that APIs apple mandates you use are available to you.

**Comment by syedamirali14** [comment]
ASAuthorizationAppleIDButtonTypeSignin fixed it for me instead of ASAuthorizationAppleIDButtonTypeSignUp

**Comment by mikehardy** [comment]
@syedamirali14 don't do that, update your Xcode! 12.4 is current best for react-native projects. 12.5 will be as soon as a couple build issues in react-native are sorted out.
