### ISSUE TITLE
First time login (with apple sign in) fails

### ISSUE THREAD

**Issue by klaaz0r** [invertase/react-native-apple-authentication#71]
Something I noticed is that when people login the first time with Apple login the module will crash, this is on devices in production and happens on all iOS versions. 

I know that you only get credentials/user data on first signin but what is causing this problem?

**Comment by Ehesp** [comment]
Do you have any logs?

**Comment by NichAga** [comment]
Happens to me on iOS 13.4.1 (the latest one), working fine with the previous version, with "Hide my email"

**Comment by klaaz0r** [comment]
@Ehesp it's hard to get a log because it happens in production and only for first time apple logins (in general)

**Comment by mikehardy** [comment]
With no reproduction or logs there is not much we can do, but I will happily reopen this with actionable information, and of course conversation can always continue

Just want to set the tone in this repo for an issues list that is in control and doesn't have non-actionable stuff
