### ISSUE TITLE
Error Domain=AKAuthenticationError Code=-7073

### ISSUE THREAD

**Issue by SmartArray** [invertase/react-native-apple-authentication#72]
Running on Simulator iOS 13.4.1 with Official RN Example Code I get this error message printed in console:

`2020-05-02 06:42:11.584241+0200 CryptoTrivia[11707:461992] [core] Credential State request returned with error: Error Domain=AKAuthenticationError Code=-7073 "(null)"`

```
const appleAuthRequestResponse = await appleAuth.performRequest({
	requestedOperation: AppleAuthRequestOperation.LOGIN,
	requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
});

// It happens here
const credentialState = await appleAuth.getCredentialStateForUser(appleAuthRequestResponse.user);

if (credentialState === AppleAuthCredentialState.AUTHORIZED) {
```

I could not find anyone else having the SAME issue (`AKAuthenticationError Code=-7073`).

I've added the Capability in Signing & Capabilities as well as in the certificate configuration page on developer.apple.com.

Any ideas?

### EDIT:
It works on the real device, but the authorized scopes Array in the `appleAuthRequestResponse` is `[]`, although I requested both `AppleAuthRequestScope.EMAIL` and `AppleAuthRequestScope.FULL_NAME`.
Interestingly the fake email address was returned successfully along with the correct name.
Is that intended behavior?

**Comment by radetsky** [comment]
Same issue, but apple documentation said that apple responses with email and full name only first try on a real device. Simulator asks password every time and gets all information every time. I found this thread. 
https://stackoverflow.com/questions/57714339/sign-in-with-apple-different-behaviour-simulator-vs-iphone
Anyway I recommend using a real device to test SIWA using this library. 
PS. I'm not a maintainer. Same user.

**Comment by mikehardy** [comment]
In general I would only trust the results from a real device, PRs to the docs would be appreciated if they don't specify this. That it works on simulator at all is almost coincidence (similar to cloud messaging / token features)

**Comment by dwarfland** [comment]
What was the solution here? im getting the same error, on device (login itself works, but getUserCredentials after app restart fails with it; see https://developer.apple.com/forums/thread/655050?login=true&page=1#626860022). This thread is the only place I fund referencing the exact same error code...
thanx!
