### ISSUE TITLE
authorizationCode invalid

### ISSUE THREAD

**Issue by gustavoferreirads** [invertase/react-native-apple-authentication#76]
After got the authorizationCode when I try to get authorization token in the backend, I have received invalid_grant 400, my all apple configuration is correct because using the web flow I have got the authorization token, seems that the authorizationCode received from this lib is invalid

**Comment by mikehardy** [comment]
How did it work for you when using the example code? (read as: show us a reproducible example)
We have a lot of users now, and it works for everyone else so this is likely project specific

**Comment by gustavoferreirads** [comment]
Sorry guys, the problem was mine. I was using service id to generate client_secret and inside the options for the authorization token request as well, instead of to use App id. The code was generated for the mobile then we have to use app_i. Thank you for the support

**Comment by ZaikinaEvgeniya-2** [comment]
if use service id to generate client_secret  you can login from android
if use app id to generate client_secret  you can login from ios

**Comment by thecodecafe** [comment]
@ZaikinaEvgeniya-2 but on the server do I use the APP ID or Client ID when decrypting the identity token of the user if the user logged in on iOS.
