### ISSUE TITLE
identity token field not matching

### ISSUE THREAD

**Issue by redwit-dev** [invertase/react-native-apple-authentication#77]
```appleAuthRequestResponse.identityToken``` is not properly matched.
in jwt, I decoded my token.
```
{
  "iss": "https://appleid.apple.com",
  "aud": "com.company.app",
  "exp": 1588957075,
  "iat": 1588956475,
  "sub": "000008.0bbbaaaaaaaa56134f871.1510",
  "nonce": "random_string",
  "c_hash": "hash-string",
  "auth_time": 1588956475,
  "nonce_supported": true
}
```
I think "sub" should be our app bundle id.
"sub", "iss", "aud" , ... field is not matching as apple docs explain.
how can I get proper token?

**Comment by mikehardy** [comment]
I would be surprised if this was a problem with the module itself, I don't recall it doing anything here. Have you tried diving in to the native code and instrumenting it there to see if this module is doing anything wrong, or if it's just unexpected behavior from the Apple library? If there's a deviation in upstream docs vs the Apple library, there's no action item for us.

If you can show where in the code we are doing something wrong, then everyone would appreciate a PR to fix it I'm sure

**Comment by redwit-dev** [comment]
thanks to replying,
I've searched for many hours. 
I think this module is not wrong, ( issuer, aud, sub is correct )
I just want to verify this token from my nodejs server. (for oauth)
but apple sites gives just unkind response "invalid_client".

I POST to "https://appleid.apple.com/auth/token",
with client_id : ```"com.company.app"```, client_secret : ```appleAuthRequestResponse.identityToken```, and grant_type for "refresh_token"

idontknowwhy I failed for verifying the token.

if you have a way to solve this problem, please let me know..

by the way, sorry for misunderstanding, I will close if u want.

thank you

**Comment by mikehardy** [comment]
I believe there was another post in the issue list about validating on the server side, have you checked the issues list and/or PRs here? I think there was even the idea to update the docs for future folks - looks like #73  ? Not sure if that is on target for you or not

**Comment by redwit-dev** [comment]
Yes, I checked that PR, but I want to verify identify_token with OAuth.
( by sending request to apple side server )
I will find a solution.. 

I just want to know something that 'client_secret' refered from [(https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens)] is matched with the ```identityToken``` from this module response.

**Comment by yanush** [comment]
I'm also having difficulties understanding what should be posted to apple's server to generate and validate the tokens.
here is apple's documentation: 
https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens

It seems some of the fields are missing while others just don't match the requirements.
Was anyone able to do it? It's not enough having just a client sign-in since anyone can tamper it.
Any help would be highly appreciated!

**Comment by mifi** [comment]
I did something like this to validate tokens: https://github.com/GoStartupsLtd/Apple-Login-Token-Validator/blob/master/index.js

**Comment by yanush** [comment]
Mifi, how can I be sure the client hasn't sent me a fake details? I don't see any private key usage in your solution

**Comment by mifi** [comment]
That code validates the jwt using apple's public key which it fetches from apple

**Comment by yanush** [comment]
Ok perfect. I will try it, thanks!

**Comment by redwit-dev** [comment]
thank you!! @mifi
