### ISSUE TITLE
Is it required to Logout or just simple clear the app's store when logging off

### ISSUE THREAD

**Issue by aravi365** [invertase/react-native-apple-authentication#79]
I tried implementing the Apple signin without logout, and works without any issues on the simulator. Haven't tried it on a real device yet. Just curious to know will it be an issue when a release build is taken.

**Comment by mifi** [comment]
I tried to implement the logout function, but if the user is not already logged in with Apple, then calling `await appleAuth.performRequest({ requestedOperation: AppleAuthRequestOperation.LOGOUT })` will cause a login prompt instead...

**Comment by mifi** [comment]
Ohh I found this: https://github.com/invertase/react-native-apple-authentication/issues/10#issuecomment-611532131

So yea, logout seems to be not necessary, and is not even used by Apple in their example app.

**Comment by mikehardy** [comment]
@mifi exactly
