### ISSUE TITLE
Auto linking didn't work

### ISSUE THREAD

**Issue by littleV** [invertase/react-native-apple-authentication#82]
On version ^1.0.0
React Native ^0.60

I usually uses npm to manage packages, for this project I installed yarn. 

However, auto linking didn't happen to me, I had to add the following line in my Podfile:
```
pod 'RNAppleAuthentication', :path => '../../node_modules/@invertase/react-native-apple-authentication'
```
Use your own relative path for node_modules.

**Comment by littleV** [comment]
Also I had to enable Sign In with Apple in Xcode to make this work: https://help.apple.com/xcode/mac/11.0/#/dev50571b902

Just a reference for developers here.

**Comment by mikehardy** [comment]
Auto-linking works in our experience - in my actual project, and in the example. If you can post a reproducible example to github, we can reopen this and follow it.

Enabling sign-in with apple to use this is fundamental and is in the documentation https://github.com/invertase/react-native-apple-authentication/blob/master/docs/INITIAL_SETUP.md
