### ISSUE TITLE
[HELP] [QUESTION] "Sign-Up Not Completed" error

### ISSUE THREAD

**Issue by filipef101** [invertase/react-native-apple-authentication#83]
When trying to login on either a device or simulator I get this message. The appleAuth.performRequest promise never resolves, and the login dialog doesn't close.

With passcode or faceId it gives a "Sign-Up Not Completed" message and then shows again the continue button. Without (password), just shows the continue button again.

What could be setup wrong on my side?

**Comment by filipef101** [comment]
was a mismatch in the bundle id, would be nice if apple showed any error in the logs :)

**Comment by alejandrorbradford** [comment]
@filipef101 how did you solve this? i'm getting this same error even in native Swift

**Comment by filipef101** [comment]
Yeah, was something with mu bundle id, dont really remeber, do you have a pros and debug apple id? Try prod if so
