### ISSUE TITLE
Apple ID prompt can still be interacted with while waiting for request

### ISSUE THREAD

**Issue by yenda** [invertase/react-native-apple-authentication#84]
In the code calling after `performRequest`, the user gets the AppleID prompt popping at the bottom of the screen. If he presses `continue with passcode` a passcode prompt opens up, and after user enters the passcode, the password prompt closes and is back to the previous prompt until the AppleAuthRequestResponse comes.

The issue is that the user can still interact with the prompt while it's waiting for the response, and for instance if he presses `continue with passcode` again it will open a new passcode modal

**Comment by mikehardy** [comment]
Interesting! Good find if true - can you think of a way to prevent this behaviour? This repository is moved forward almost entirely by user contributions so we would love a PR for this if you can get one working.

**Comment by mikehardy** [comment]
I think the solution at this point is to block your UI with a spinner or similar in app code.
I do this and it works, if other behavior is wanted propose a design for the app to maintain auth status internally with some sort of timeouts or ways to override hopefully (so apps don't get completely stuck)
