### ISSUE TITLE
Appropriate way to ignore this in React Native Web?

### ISSUE THREAD

**Issue by haveamission** [invertase/react-native-apple-authentication#87]
So I want to use react-native-apple-authentication in my iOS app, however I do not want to even load it when building for the web or Android app.

Currently I am getting the following error when trying to launch Expo as such:

expo start -w

```
/Users/andy/Desktop/Projects/PandaistOfficial/Frontend/Expo/node_modules/@invertase/react-native-apple-authentication/lib/AppleButton.js 55:9
Module parse failed: Unexpected token (55:9)
You may need an appropriate loader to handle this file type.
| }) {
|   const NativeComponent = getNativeComponentForStyleAndType(buttonStyle, buttonType);
>   return <NativeComponent {...props} />;
| }
|
```

I am at this point not currently importing or otherwise using the library.

How do I only conditionally use this library depending on whether or not I am building for iOS?

**Comment by mikehardy** [comment]
If you are using expo, you may find that they have an apple sign in module that is more convenient?

**Comment by haveamission** [comment]
@mikehardy  Oh interesting, thanks, I'll check that out.

Another solution I found that worked was adding this to my app.json:

```
    "web": {
      "build": {
        "babel": {
          "include": [
            "@invertase/react-native-apple-authentication"
          ]
        }
      }
    }
```

**Comment by mikehardy** [comment]
I may be wrong (if so we can reopen) but if that workaround works, and expo people do have a module (last I checked it existed and worked great - I used it for a bit myself, just switched to this one because it is a little more firebase-comfortable), this is okay to close
