### ISSUE TITLE
Sign Up Not Completed for reviewer

### ISSUE THREAD

**Issue by porzioj** [invertase/react-native-apple-authentication#93]
Hi guys,

First please take in count it is not the same case as issue #83 :-)
Apple's reviewer is saying Sign in does not works
![attachment-11786310053490606996Screenshot-0614-062117](https://user-images.githubusercontent.com/10049383/84607238-28161380-ae7a-11ea-9bdd-03605c938fbd.png)

But on my side it works on many devices via TestFlight but not on Apple's reviewer phone so my point would be more to know if you already faced that with reviewers and if you have any idea on how I could solve that.
It looks like it is coming from Apple Sign In system and would like to reproduce it.
Do you have any idea on how to reproduce ?
And if anyone already faced this problem which is blocking he review ?

Thanks

**Comment by mikehardy** [comment]
It's working for me, app review passed as recently as last Monday (6 days ago)

**Comment by porzioj** [comment]
Hi @mikehardy thanks for your answer, 
Could the problem be related to internet connection ?
On my first attempt apple team was coming back with screenshot like this 
![attachment-5587714687021205720Screenshot-0612-155741_copy (1)](https://user-images.githubusercontent.com/10049383/84608497-c86f3680-ae80-11ea-9c14-31f0296e6569.png)
I don't understand how they test but seems like they have connection problems...

**Comment by mikehardy** [comment]
I have no idea, sorry

**Comment by gonjitti** [comment]
I also faced same issue with react-native-firebase(https://github.com/invertase/react-native-firebase).
I try to find out what happen in review.
![image](https://user-images.githubusercontent.com/10106031/84613574-7c62d700-aefe-11ea-8515-802d527393a0.png)

**Comment by Ehesp** [comment]
Screenshots don't really help sorry. Can you try building a release app and checking out logs etc.

**Comment by gonjitti** [comment]
@Ehesp 
here is part of  logs related RNAppleAuthentication.
Start with `Build target RNAppleAuthentication of project Pods with configuration Release`
(Sorry, I am not Swift Engineer so I cannot find out how to fix fro these logs.)
[Build Target RNAppleAuthentication.txt](https://github.com/invertase/react-native-apple-authentication/files/4783676/Build.Target.RNAppleAuthentication.txt)

**Comment by mikehardy** [comment]
What is the goal of that text file? It just looks like normal compilation to me. Is there some  build error we are looking for? How could you have submitted an app if it did not build?

If the auth failed for the reviewer you need to add lots of logging to the app and hopefully they can give you the execution logs?

**Comment by gonjitti** [comment]
>What is the goal of that text file? It just looks like normal compilation to me. Is there some build error we are looking for? How could you have submitted an app if it did not build?

Yes. these are normal compilation file logs.

>If the auth failed for the reviewer you need to add lots of logging to the app and hopefully they can give you the execution logs?

Now I try to log from reviewer action. I upload these later.

Below is my app code(I hope logging from Firebase Crashlytics).
```
import React from 'react';
import auth from '@react-native-firebase/auth';
import appleAuth, {
  AppleAuthRequestScope,
  AppleAuthRequestOperation,
  AppleAuthError,
  AppleButton } from '@invertase/react-native-apple-authentication';
import crashlytics from '@react-native-firebase/crashlytics';
import FirebaseEventTracker from '../../../lib/FirebaseEventTracker';

// from app
// import Colors from '../../constants/Colors';
// import styles from './styles';

async function onAppleButtonPress() {
  // Start the sign-in request
  const appleAuthRequestResponse = await appleAuth.performRequest({
    requestedOperation: AppleAuthRequestOperation.LOGIN,
    requestedScopes: [AppleAuthRequestScope.EMAIL],
  });

  // Ensure Apple returned a user identityToken
  if (!appleAuthRequestResponse.identityToken) {
    throw new Error({
      message: 'Apple Sign-In failed - no identify token returned',
      code: 'no identityToken'
    });
  }

  // Create a Firebase credential from the response
  const { identityToken, nonce } = appleAuthRequestResponse;
  const appleCredential = auth.AppleAuthProvider.credential(identityToken, nonce);

  // Sign the user in with the credential
  return auth().signInWithCredential(appleCredential);
}

export default function AppleLoginButton() {
  return (
    <AppleButton
      buttonStyle={AppleButton.Style.WHITE}
      buttonType={AppleButton.Type.SIGN_IN}
      style={{
        shadowColor: 'rgba(0,0,0, .4)',
        shadowOffset: { height: 1, width: 1 },
        shadowOpacity: 1,
        shadowRadius: 1,
        paddingTop: 14,
        paddingBottom: 14,
        height: 52,
        margin: 7,
        justifyContent: 'center',
        alignItems: 'center',
        fontWeight: 'bold',
        flexDirection: 'row',
      }}
      onPress={() => onAppleButtonPress().then(() => {
        FirebaseEventTracker.loginSuccess('apple');
      }).catch((error) => {
        // キャンセルならば無視
        if (error.code === AppleAuthError.CANCELED) {
          crashlytics().log('Apple sign-in cancelled');
        }
        FirebaseEventTracker.loginFailed('apple', error.code);
        crashlytics().recordError(error);
      })}
    />
  );
}
```

**Comment by porzioj** [comment]
Hi guys,

Just to update you on my problem, I sent the same build 4 time and as suspected problem was on Apple's reviewer side besause the 4th time it passed without knowing why.
Will close this, hope it will helps if someone got this problem?

**Comment by mikehardy** [comment]
That is crazy. I have similar non-deterministic pass/fail with Apple review, but so far not because of sign-in! Pretty frustrating as a dev. Glad you're moving forward, good luck with your project

**Comment by porzioj** [comment]
Yes really frustrating when Apple reviewers are not able to make working their own signing system..
Anyway hope you will solve your problems for review too!
Good luck @mikehardy

**Comment by gonjitti** [comment]
I think so too. Thank you for your help.
It is not related to this repository so I continue to solve this problem with Apple reviewer, thank you.

**Comment by brooklyntronic** [comment]
Am currently facing same issue in review.  Works on all devices, all login flows (touch, password, face-id) but reviewer keeps rejecting my app.  I cannot replicate the bug.

**Comment by mikehardy** [comment]
I would be so frustrated in your situation, I really understand. But without something reproducible here I'm not sure what we can do. I've seen cases of other types of rejections where phone logs could be had from the reviewer, perhaps if you worked with them and shipped a build with as much logging as possible we could get to the bottom of it? Or perhaps the reviewer just needs to use a VPN (I believe some of that work is offshored, maybe it's as simple as the reviewer having a constrained network)

**Comment by AliRehman7141** [comment]
Hello there I'm also facing this issue I'm getting ```[Error: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1001.)]``` in catch

**Comment by AliRehman7141** [comment]
> Hello there I'm also facing this issue I'm getting `[Error: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1001.)]` in catch

Okay found the solution in ** Troubleshooting** 😁

**Comment by aminosman** [comment]
We are facing this issue, After years of sign in with Apple live in production we randomly got hit with non-stop rejections over this issue. We are unable to reproduce and unsure how to proceed. We have no reports of this issue in production, its a reviewer only issue at the moment. We are running the latest stable version 2.2.2. We have had at least 10 submissions rejected. Any help on how this was reproduced or resolved would be much appreciated.
![Uploading image.png…]()

**Comment by mikehardy** [comment]
I love it when there is an easy answer for these sorts of things, and I can just type it up and help someone, but the 1000 error has lots of sources, and as you note, there has not been a software change here in forever. I'm not aware of the *need* to do a change here either. I'm stumped. Perhaps the reviewer is on a VPN or some sort of network issue similar to that where the Apple servers don't like the reviewer's network? Something else going on? I really don't know. As you mention "you have no reports of this in production"... that is...the code is working. Very confusing 🤔
