### ISSUE TITLE
Refresh operation forces user to login again

### ISSUE THREAD

**Issue by steventnorris-40AU** [invertase/react-native-apple-authentication#95]
Running the below code opens the login popup and forces the user to re-enter their pin or face id. It does not refresh in background. Is this with Apple standards or a bug in the library?

```
appleAuth.performRequest({
  requestedOperation: AppleAuthRequestOperation.REFRESH,
  user: auser
})
```

**Comment by mikehardy** [comment]
Curious. Any more info?
Version info of everything? real device or simulator (definitely test on real device if it was simulator)?
Historically for questions like this the questioner is the questioner ends up having to resolve it - I don't think anyone is an expert yet on the APIs and we've not encountered this particular thing before

In the past searches on apple dev forums / a look at the related expo apple auth module, and/or hacking in some instrumentation on the underlying Obj-C code here and seeing what the API does has been the path to resolve

**Comment by mikehardy** [comment]
@steventnorris-40AU any further info on this re: the comment I left above?

**Comment by tahasabih** [comment]
@steventnorris-40AU did you manage to resolve this issue? We are facing the same thing

**Comment by steventnorris-40AU** [comment]
@tahasabih I have not. The issue became low priority and we simply accepted it as it was for now. This project hasn't resurfaced the need yet.

**Comment by DanielMarkiel** [comment]
Hi @mikehardy,
Is it possible to reopen this issue? We are facing exactly the same problem + we noticed that on real devices using `requestedOperation: AppleAuthRequestOperation.REFRESH,` results in empty `email` and `fullName` fields.

Versions info:
- "@invertase/react-native-apple-authentication": "2.1.0"
- "react-native": "0.63.4"

Tested on simulators - os versions: 13.7, 14.4 - and real devices (iPhone XS, iPhone SE) - os versions: 14.4, 14.3 respectively.

Please let me know if you need more details.

**Comment by mikehardy** [comment]
I can reopen it but to set expectations if there is to fix you'll have to drive it via submission of a PR or it will sit. You can see the cide here vs the apple apis, there isn't a lot to it and it's my understanding we coded it to the docs

**Comment by nextriot** [comment]
This is still happening. The REFRESH request prompts the user to sign in again.

How are people dealing with refreshing the token otherwise? Just persist the user token in local state and force the user to sign in if revoked?

**Comment by Elprior** [comment]
Hello Team,

Same problem here, configuration is:
- RN 0.63.4
- @invertase/react-native-apple-authentication 2.1.2
- real device iPhone X

Whenever we perform a refresh operation, the user is prompted to login, by approving the pop-up and having a successful face id result.

The point is that, along with AWS Cognito that we use for server-side accesses to services, there are automatic refresh that happen under the hood, and then the user is prompted to do something at a time when it feels weird to be prompted (just after login for instance).
The expectation would be that a new token would be obtained silently (ie without user interaction), based on currently authenticated user data.

PS: it's not much of a help, but with Google Sign In (@react-native-google-signin/google-signin), there is an API that does exactly that (signInSilently) and that returns a refreshed token that you can use on server side. I haven't looked at the code to check if this is a library or API specific behavior

**Comment by mikehardy** [comment]
Hmm - I just re-read this whole thread. With apologies, I believe my comment here is still the complete state:

> I can reopen it but to set expectations if there is to fix you'll have to drive it via submission of a PR or it will sit. You can see the code here vs the apple apis, there isn't a lot to it and it's my understanding we coded it to the docs

That is, I do not believe there is an API call that we are either not using (e.g., silent refresh) or that we are using correctly.

I could definitely be wrong but please, please check the code yourself. I personally detest Objective-C and I'm objectively no good at it (just being honest) but this is the smallest Objective-C wrapper ever and even I can understand which implies anyone else reading this comment can also understand it and verify it vs the Apple APIs in case we're missing something

I see this as an independent source coming to the same conclusion for the native SDK https://github.com/lupidan/apple-signin-unity/issues/80#issuecomment-723415986

**Comment by Elprior** [comment]
Hello Mike,

thanks for your quick update, and the pointers to the expected strategy!

We have to cope with Cognito constraints also, so we decided for a simple approach in Apple case, where the handler simply returns the previous token as long as it is valid. After one day, the user is prompted to identify again.

Best regards

**Comment by mikehardy** [comment]
Sorry there's not an answer more along the lines of "oh just do it like this..." ;-)
Seeing as there does not appear to be any way to do it on device this is not actionable so I'm going to close it
Perhaps they will add more / better APIs in the future though

**Comment by nkhosla91** [comment]
Hi, have there been any updates to this? How can I persist a users login and continue to validate tokens/session without prompting the user to sign in again?

**Comment by mikehardy** [comment]
All development is in the open here - what you see in our issues lists / pull requests is what there is

**Comment by Rubon72** [comment]
is it enough to refresh authorizationCode and don't show login again for user ? 
`
appleAuth.performRequest({
  requestedOperation: appleAuth.Operation.REFRESH
})
`

**Comment by maestrolsj** [comment]
we need to find a way how to get refreshed token silently

**Comment by DanielWFrancis** [comment]
I'm confused how everyone is using this library when their users have to re-login every 24 hours. Am I missing something?

**Comment by IKyriazis** [comment]
> I'm confused how everyone is using this library when their users have to re-login every 24 hours. Am I missing something?

Yes, could someone elaborate? I think this is a major feature that is missing. I understand this is an open source package so I do not intend to throw shade on anyone but I'd like to know if silently refreshing the login is implementable another way before I dedicate some time to checking the code out myself. I agree, I find it surprising that although this library is so popular it requires users to re sign in every 24 hours.

**Comment by Romick2005** [comment]
This liv works as expected. There are no 24h auto logout, it could be your code that is not properly implemented.

**Comment by nkhosla91** [comment]
I have been refreshing tokens using a different library through my service. 
https://www.npmjs.com/package/apple-signin-auth
