### ISSUE TITLE
AppleAuth is not supported on this device. 

### ISSUE THREAD

**Issue by adambeck7** [invertase/react-native-apple-authentication#96]
I'm getting this error when attempting to login on the simulator and an iOS device running 13.4: 
`[Error: AppleAuth is not supported on the device. Currently Apple Authentication works on iOS devices running iOS 13 or later. Use 'AppleAuth.isSupported' to check device is supported before calling any of the module methods.]`

Sorry, I know the docs say .60+ is required but I inherited a legacy app that is still running React Native .53 and don't have time to upgrade to .60+ before the June 30 deadline. Is there any way to get Apple Auth working on .53?

**Comment by mikehardy** [comment]
research Xcode 11 support in react-native - it's my understanding the answer is basically no. You may have some luck with react-native 0.59, sparing you a big jump. the "upgrade helper" site should help a lot as well

I just checked and it goes back before 0.53 https://react-native-community.github.io/upgrade-helper/ - go step by step and it's possible

Also note there are other reasons (represented by closed issues here) where this error is falsely reported, in that the module doesn't have a problem but for example it doesn't play nicely with sagas or something

**Comment by adambeck7** [comment]
Thanks. I guess I'll give the upgrade a shot. We upgraded android but there are a ton of dependencies that had conflicts so it was a long process.

**Comment by ahtishamali09** [comment]
@mikehardy i having same issue but my everything is up to date Xcode version is 12.5.1 and RN version is 0.63.4 i am testing on Simulator
