### ISSUE TITLE
onCredentialRevoked not triggered

### ISSUE THREAD

**Issue by 39otrebla** [invertase/react-native-apple-authentication#99]
We are registering `onCredentialRevoked` event as the doc suggests:

```javascript
.onCredentialRevoked(async () => {
  console.warn('If this function executes, User Credentials have been Revoked');
})
```

Though, it does not trigger any event when users revoke App access to their Apple account.

Platform: iOS
React Native: v0.62.2
react-native-apple-authentication: latest version

NOTE: a workaround is to check credential state with `getCredentialStateForUser` when coming back to the foreground and/or upon network state changes, though it would be great to use the listener.

**Comment by mikehardy** [comment]
Can you verify if the APIs themselves (as in, the underlying Objective-C APIs) are called correctly or hooked correctly? It has been our experience with credentials and logout etc that they behave in unexpected ways at the system level and there's nothing the module can do about it - this has been discovered by folks going in and instrumenting the actual Obj-C code to be a bit more verbose about what it's doing and would be the first step to resolution

Also make absolutely sure all testing you do is on real devices, the simulator does not behave well with these APIs either and you will get different results, leading to phantom chasing

**Comment by puneetkansal04** [comment]
I am also trying to revoke apple credential and it is not working for me also. @mikehardy Can you please provide me detail how can i add revoke function so that each time apple credential will revoke and it will show a share email popup.

**Comment by mikehardy** [comment]
I don't think you can do what you want to do
I don't think the underlying Apple APIs support it.

**Comment by mauriciosoares01** [comment]
If you are using  ```onCredentialRevoked``` in the useEffect`s return, try to remove the 'return'

**Comment by rossbulat** [comment]
> If you are using `onCredentialRevoked` in the useEffect`s return, try to remove the 'return'

Having the function in useEffect's return statement is confusing to me too, and is not consistent with [the class component's](https://github.com/invertase/react-native-apple-authentication/blob/master/example/classVersion.js) implementation, where the event listener is initiated on componentDidMount.

In your useEffect implementation the event listener will not be initialised until the component unmounts, so I imagine the event listener will also concurrently unmount too. Surely the listener will not catch any events this way.

**Comment by rossbulat** [comment]
This should work: 

```
 let authCredentialListener = null;
  useEffect(() => {
    // initialise revoke listener
    authCredentialListener = appleAuth.onCredentialRevoked(async () => {
      console.warn('If this function executes, User Credentials have been Revoked');
    });

    return (() => {
      // remove revoke listener
      if (authCredentialListener.remove !== undefined) {
        authCredentialListener.remove();
      }
    })
  }, []);
```

**Comment by noway** [comment]
When is this callback supposed to fire anyway? I implemented it, but how do I test it?

**Comment by noway** [comment]
Nvm, it does seem to trigger when you "stop using apple sign in for the app" in the Settings. rossbulat's code works fine for me (although I used non hooks version)
